### ISSUE TITLE
【建议】深色模式过暗，希望可以调亮一点或者增添新的灰色模式

### ISSUE THREAD

**Issue by alnona** [BewlyBewly/BewlyBewly#1002]

**Comment by DemoJameson** [comment]
+1

**Comment by DemoJameson** [comment]
写了个样式调整视频页和搜索页的背景色 https://userstyles.world/style/18135/bewlybewly
需要安装此脚本使得样式在 Shadow DOM 中生效
https://greasyfork.org/zh-CN/scripts/486849-inject-stylus-in-shadow-dom

**Comment by hakadao** [comment]
深色模式重新配色或再配多一版還有一點麻煩，我目前打算日後開放自定義css來弄

**Comment by hakadao** [comment]
之後設定->外觀最下面可以改css
![image](https://github.com/user-attachments/assets/b5af106e-e7c6-4ca3-bc7c-7975de7b6715)

**Comment by DemoJameson** [comment]
调整背景色示例
```css
:root.dark {
  --bew-bg: hsl(230 12% 8%);
}
```
