### ISSUE TITLE
[enhancement] 添加稍后再看点击视频重定向到详情页而不是稍后再看播放列表的选项

### ISSUE THREAD

**Issue by Moderpach** [BewlyBewly/BewlyBewly#1004]
B站网页端稍后再看自动播放到多分P的视频会吞掉观看记录，故希望添加稍后再看点击视频重定向到详情页而不是稍后再看播放列表的选项。
预期行为可以参考 Bilibili-Evolved 的稍后再看重定向。

Bilibili-Evolved 的稍后再看重定向仅支持B站原生的稍后再看界面，不支持 BewlyBewly 提供的稍后再看界面

**Comment by hakadao** [comment]
原本b站處理就是跳轉都稍後觀看列表的，我不想為了這個問題又加個設定調整
b站那邊處理有吞記錄建議去找b站客服匯報問題
