### ISSUE TITLE
[建议]B站弹幕设置被改变，能否加个新功能改回旧设置

### ISSUE THREAD

**Issue by doxsw** [BewlyBewly/BewlyBewly#1007]
新![image](https://github.com/user-attachments/assets/a6f9322b-4183-41c1-a942-1aa90f46575c)
旧![image](https://github.com/user-attachments/assets/c8704787-a235-4211-b362-75690c077c74)
目前好像只有部分账号的网页版会变成新的设置，只要退出登陆就会变成旧的

**Comment by doxsw** [comment]
![image](https://github.com/user-attachments/assets/618d120b-0a13-447c-b2b3-4e3eedd39c94)
还有这个

**Comment by hakadao** [comment]
bewlybewly只專做自己的頁面，不太想做b站頁面大幅度調整
