### ISSUE TITLE
做一下私信的界面

### ISSUE THREAD

**Issue by Cocoa-C** [BewlyBewly/BewlyBewly#1009]
现在B站私信页面改了，太令人绝望
建议做一下私信界面
可以用自定义的背景功能

**Comment by hakadao** [comment]
不考慮做b站頁面的自定義背景，原因b站其他頁面改背景不僅僅是只改body就可以，還可能對原有文字完成加上背景或調整其他元素透明度使其能看到自定義的背景
單獨適配一個b站頁面的背景的話會有人希望做全站的背景設置

之後會開發自定義css方案給高級玩家調整，目前的話只能先建議用[stylus](https://chromewebstore.google.com/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne)改着先
