### ISSUE TITLE
首页加载空白且获取不到登录状态

### ISSUE THREAD

**Issue by pmman289** [BewlyBewly/BewlyBewly#1016]
### 环境

浏览器 (如 Chrome): Chrome
浏览器版本 (如 126.0.6478.126): 128.0.6613.138
BewlyBewly 版本 (如 0.20.1): 0.30.2

### 问题描述

首页加载空白，表现如下：
![image](https://github.com/user-attachments/assets/2f1afb97-c209-4b76-af84-443d5a2a654d)

发现解决方案如下：
需要勾选扩展程序设置中的自动允许访问以下网站
![image](https://github.com/user-attachments/assets/a3f9c5be-6025-49cc-9a9e-2a173203eff9)

**Comment by hakadao** [comment]
正常為何要禁用啊，禁用之後還怎麼調用原本b站接口啊

**Comment by pmman289** [comment]
> 正常為何要禁用啊，禁用之後還怎麼調用原本b站接口啊

这并不是我禁用的，我注意到chrome插件市场同样有用户报告此问题，可能是chrome自动禁用的，所以提起此issue
