### ISSUE TITLE
【建议】希望导出设置能保存 页面网格布局选择的布局

### ISSUE THREAD

**Issue by DD224ever** [BewlyBewly/BewlyBewly#1020]
### 环境

浏览器 (如 Chrome):
浏览器版本 (如 126.0.6478.126):
BewlyBewly 版本 (如 0.20.1):

### 问题描述

如题，我习惯单列的，每次更新后导入设置还是要进入设置启用页面网格布局切换器把默认布局从四列切换成单列再关闭启用页面网格布局切换器设置。

反倒是现在导出设置能连带着背景图链接一起导出了好评。

**Comment by hakadao** [comment]
我是不想把只是介面調整佈局這一點簡單調整也放進設定再匯出的。設定現在已經很膨大，日後加些其他功能調整都會再三考慮
