### ISSUE TITLE
无法加载扩展

### ISSUE THREAD

**Issue by Towardsthesky** [BewlyBewly/BewlyBewly#1022]
### 环境

浏览器 (如 Chrome):Edge
浏览器版本 (如 126.0.6478.126):129.0.2792.52 (正式版本) (64 位)
BewlyBewly 版本 (如 0.20.1):0.31.0

### 问题描述

在加载已解压缩的扩展时失败，弹出如下提示：
无法为内容脚本加载文件“./dist/contentScripts/index.global.js”。它不是 UTF-8 编码格式。

**Comment by hakadao** [comment]
edge也可以直接在chrome web store下載呀

**Comment by 2334336** [comment]
> edge也可以直接在chrome web store下载呀

商店里的是30.2旧版本

**Comment by VisualSpank** [comment]
chrome是这样的

**Comment by li056259** [comment]
我的edge浏览器也提示这个

**Comment by DD224ever** [comment]
我的vivaldi也是

**Comment by LJC-god** [comment]
我使用谷歌应用商店的扩展 首页不生效 然后下载30.2对应的包然后进行解压加载 生效了但是第二天又失效了 下载最新的包加载时也显示无法为内容脚本加载文件“./dist/contentScripts/index.global.js”。它不是 UTF-8 编码格式。
