### ISSUE TITLE
新版本的自定义字体会导致MacType注入失败

### ISSUE THREAD

**Issue by ITManCHINA** [BewlyBewly/BewlyBewly#1028]
### 环境

浏览器 (如 Chrome): Chrome
浏览器版本 (如 126.0.6478.126):  129.0.6668.71
BewlyBewly 版本 (如 0.20.1): 0.31.3
MacType版本：[Version 2024.9.14](https://github.com/snowie2000/mactype/releases/tag/v1.2024.9.14)

### 问题描述

在开启与关闭开启和关闭自定义字体功能的时候，都会导致MacType无法成功注入系统字体。

解决方案：在开启自定义字体后，在结尾处添加英文逗号`,`即可。

---

对比结果：
| 注入失败 | 注入成功 |
| ------------- | ------------- |
| ![1727288436064](https://github.com/user-attachments/assets/1cff11c4-8db1-4bf0-b288-9dce437f6761) | ![1727288362581](https://github.com/user-attachments/assets/97ac4208-1770-4d59-a4a4-0bddbc4de081) |
| ![1727288450992](https://github.com/user-attachments/assets/e2373e2a-36d1-4329-913a-87eab2d0563e) | ![1727288457287](https://github.com/user-attachments/assets/913e800f-21b6-42c5-8fc1-652b1f13478a) |

解决方案：
![1727288622668](https://github.com/user-attachments/assets/d40fd057-7369-41cb-8b92-4e7ef3de2d7a)

---

## 但仍然存在并未解决的问题：
在视频播放页面加载前后，BewlyBewly会暴力重置Mactype已经渲染好的字体（开关自定义字体以及根据上面的方法修正MacType字体渲染问题，该bug都可以稳定复现）。除了`接下来播放`和`推荐视频的标题和UP昵称`，其它部分（包括Dock栏的菜单内字体）都会被替换为系统默认字体。已尝试将自定义字体修改为`system-ui,`，但视频页的字体依旧会把MacType渲染好的苹方字体替换为微软雅黑。

对比：
| 视频加载中（MacType已渲染好苹方） | 加载完成（被替换回微软雅黑） |
| ------------- | ------------- |
| ![1727289509566](https://github.com/user-attachments/assets/c20ca48c-1f85-41c4-98d4-7b1e39b1ccbd) | ![1727289514364](https://github.com/user-attachments/assets/094d9e6e-59f5-4a46-aa5c-5427bcd62cbe) |

### 预期结果

希望能让自定义字体这个功能更完善一些吧。

**Comment by ITManCHINA** [comment]
再补充一个，弹幕字体也被BewlyBewly替换掉了🥲

**Comment by hakadao** [comment]
bewly預設是英文字型首選，中文字型作為備用
且css那邊也沒有強制用!important暴力修改文字

不知道mactype做了甚麼處理，但是自訂字型的話前面選蘋方還是沒效嗎

https://github.com/BewlyBewly/BewlyBewly/blob/main/src/styles/fonts.scss

**Comment by young-mei** [comment]
> 再补充一个，弹幕字体也被BewlyBewly替换掉了🥲

我也遇到了类似的问题，弹幕字体被强制渲染为Noto Sans，切换字体无效；暂时停用BewlyBewly可解决此问题
希望此问题能尽快得到解决，感谢各位贡献者的付出

**Comment by ITManCHINA** [comment]
> bewly預設是英文字型首選，中文字型作為備用 且css那邊也沒有強制用!important暴力修改文字
> 
> 不知道mactype做了甚麼處理，但是自訂字型的話前面選蘋方還是沒效嗎
> 
> https://github.com/BewlyBewly/BewlyBewly/blob/main/src/styles/fonts.scss

目前尝试使用的参数为`system-ui, -apple-system, BlinkMacSystemFont, 苹方-简, 苹方-繁, 苹方-港,`，问题依旧存在🥲

**Comment by hafterain** [comment]
@ITManCHINA 把你的`system-ui`删掉。

**Comment by ITManCHINA** [comment]
> @ITManCHINA 把你的`system-ui`删掉再看看。

尝试过了，问题依旧存在

**Comment by hakadao** [comment]
把前面system-ui去掉，再把最後單獨加的逗號去掉看看

**Comment by hakadao** [comment]
> > 再补充一个，弹幕字体也被BewlyBewly替换掉了🥲
> 
> 
> 
> 我也遇到了类似的问题，弹幕字体被强制渲染为Noto Sans，切换字体无效；暂时停用BewlyBewly可解决此问题
> 
> 希望此问题能尽快得到解决，感谢各位贡献者的付出

是是想彈幕部份文字也改嗎，彈幕用noto sans和b站之前的字型差別都不大啊

**Comment by ITManCHINA** [comment]
> 把前面system-ui去掉，再把最後單獨加的逗號去掉看看

啊，这样就可以了，Thanks

**Comment by young-mei** [comment]
> > > 再补充一个，弹幕字体也被BewlyBewly替换掉了🥲
> > 
> > 
> > 我也遇到了类似的问题，弹幕字体被强制渲染为Noto Sans，切换字体无效；暂时停用BewlyBewly可解决此问题
> > 希望此问题能尽快得到解决，感谢各位贡献者的付出
> 
> 是是想彈幕部份文字也改嗎，彈幕用noto sans和b站之前的字型差別都不大啊

今天使用时发现弹幕字体和之前有细微的区别，虽然很小但还是能感觉出不同，关闭插件后调试发现弹幕原本的字体是黑体

**Comment by ITManCHINA** [comment]
最终使用的参数：
`苹方-简, 苹方-繁, 苹方-港, -apple-system, BlinkMacSystemFont, "Segoe UI", Inter, "Roboto Flex", "Noto Sans", Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", Arial, sans-serif`

---

反正先用着吧，没有特殊字符的话就尝试仅保留苹方了🥲

**Comment by hakadao** [comment]
> > > > 再补充一个，弹幕字体也被BewlyBewly替换掉了🥲
> 
> > > 
> 
> > > 
> 
> > > 我也遇到了类似的问题，弹幕字体被强制渲染为Noto Sans，切换字体无效；暂时停用BewlyBewly可解决此问题
> 
> > > 希望此问题能尽快得到解决，感谢各位贡献者的付出
> 
> > 
> 
> > 是是想彈幕部份文字也改嗎，彈幕用noto sans和b站之前的字型差別都不大啊
> 
> 
> 
> 今天使用时发现弹幕字体和之前有细微的区别，虽然很小但还是能感觉出不同，关闭插件后调试发现弹幕原本的字体是黑体

你在自定義字體最前面用微軟雅黑不就可以囉

**Comment by hakadao** [comment]
> > > > 再补充一个，弹幕字体也被BewlyBewly替换掉了🥲
> 
> > > 
> 
> > > 
> 
> > > 我也遇到了类似的问题，弹幕字体被强制渲染为Noto Sans，切换字体无效；暂时停用BewlyBewly可解决此问题
> 
> > > 希望此问题能尽快得到解决，感谢各位贡献者的付出
> 
> > 
> 
> > 是是想彈幕部份文字也改嗎，彈幕用noto sans和b站之前的字型差別都不大啊
> 
> 
> 
> 今天使用时发现弹幕字体和之前有细微的区别，虽然很小但还是能感觉出不同，关闭插件后调试发现弹幕原本的字体是黑体

另外你知道最後一定會fallback到黑體嗎，我做了處理的

**Comment by hakadao** [comment]
> 最终使用的参数：
> 
> `苹方-简, 苹方-繁, 苹方-港, -apple-system, BlinkMacSystemFont, "Segoe UI", Inter, "Roboto Flex", "Noto Sans", Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", Arial, sans-serif`
> 
> 
> 
> ---
> 
> 
> 
> 反正先用着吧，没有其它特殊字符需要用其它字体显示的话就尝试仅保留苹方了🥲

system-ui windows處理太強制，加這個是因為windows簡體下的firefox用bewly正體中文才不會顯示明體/宋體，下版本我看看有沒有比較好的方式處理
