### ISSUE TITLE
BUG：切换至原版顶栏后，取消后 bew顶栏消失

### ISSUE THREAD

**Issue by TC999** [BewlyBewly/BewlyBewly#1033]
### 环境

浏览器 (如 Chrome): Chromium
浏览器版本 (如 126.0.6478.126): 124.0.6367.91
BewlyBewly 版本 (如 0.20.1): 0.31.4

### 问题描述

点击“使用原版 BiliBili 顶栏后”正常切换，但取消之后 bew 顶栏会消失，刷新也没用，重置设置才能恢复

https://github.com/user-attachments/assets/b4954643-facc-4d77-bb24-16a4b64f99b0

### 预期结果

取消后正常切回 bew 顶栏

**Comment by hakadao** [comment]
使用原版頂欄之後會關閉這bewly頂欄，兩功能互斥，無法同時一起開啓和關閉
![image](https://github.com/user-attachments/assets/e765c0af-b5aa-4331-98ce-6707f43c3720)
