### ISSUE TITLE
插件会导致弹幕字体修改功能失效

### ISSUE THREAD

**Issue by CirnoSalt** [BewlyBewly/BewlyBewly#1038]
### 环境

浏览器 (如 Chrome): Chromium 
浏览器版本 (如 126.0.6478.126): 127.0.6533.88
BewlyBewly 版本 (如 0.20.1): 0.31.5

### 问题描述

不知道是B站播放器更新还是插件更新导致的问题，最近发现开启BewlyBewly插件会导致播放器内置的弹幕字体设置功能失效，无论选什么字体弹幕都是默认字体，插件自带的【自定义字体】功能开关也是关闭的，禁用插件后就恢复正常了。
![QQ20240929-204339](https://github.com/user-attachments/assets/dd00c272-532f-4255-b532-595f1f9f33ec)
![QQ20240929-204847](https://github.com/user-attachments/assets/a26cf731-b99f-4128-9475-fe9ebdef14c7)
![QQ20240929-205000](https://github.com/user-attachments/assets/90860972-5f90-4764-b9d1-27f439f031d6)

**Comment by hakadao** [comment]
好，這部分應該很快處理

**Comment by CirnoSalt** [comment]
> 好，這部分應該很快處理

更新0.33.1版本后该BUG再次出现

**Comment by hakadao** [comment]
請把這裏取消
![image](https://github.com/user-attachments/assets/ed9b9c9b-0b61-41c2-b4cb-b8e069a285e8)
