### ISSUE TITLE
暗色模式按钮黑罩触发区域比白区小

### ISSUE THREAD

**Issue by sharJie** [BewlyBewly/BewlyBewly#1039]
### 环境

浏览器 (如 Chrome):edge
浏览器版本 (如 126.0.6478.126):129.0.2792.65
BewlyBewly 版本 (如 0.20.1):0.31.5

### 问题描述

https://github.com/user-attachments/assets/09c48be3-eace-4cdf-8539-34040957fe49

![image](https://github.com/user-attachments/assets/c809619b-2793-4093-81c2-586f57b559a6)

### 预期结果

两个特效同时出现

**Comment by hakadao** [comment]
為何要偏偏觸發這個不會影響正常使用的功能增加額外的維護難度
