### ISSUE TITLE
抽屉模式会当前页面自动跳转bv界面

### ISSUE THREAD

**Issue by Noah1995** [BewlyBewly/BewlyBewly#1042]
### 环境

cent浏览器版本 5.1.1130.129（正式版本） （32 位） (Portable) 
(Chromium 118.0.5993.159)
BewlyBewly 版本 (0.31.5):

### 问题描述

抽屉模式会当前页面自动跳转bv界面
![录制_2024_10_02_18_47_21_541](https://github.com/user-attachments/assets/7c5ad368-3b1e-45d9-a172-bef9c1fe1ab7)

**Comment by Noah1995** [comment]
> 尝试更新Chromium内核再看看。

我是试了一下金丝雀 131可以,
但是cent最新内核就是118啊...能否加入不要强制跳转

**Comment by Noah1995** [comment]
> 尝试更新Chromium内核再看看。

你看一下这个问题可以解决吗?
不行的话只能等cent更新内核了...
主要edge和chrome都不好用,catsxp更新快又没有谷歌同步

**Comment by hakadao** [comment]
> > 尝试更新Chromium内核再看看。
> 
> 
> 
> 我是试了一下金丝雀 131可以,
> 
> 但是cent最新内核就是118啊...能否加入不要强制跳转

以最新穩定內核為主，chrome那邊都到129了
