### ISSUE TITLE
顶栏私信没有提示

### ISSUE THREAD

**Issue by AsakawaRyou** [BewlyBewly/BewlyBewly#1044]
### 环境

浏览器 (如 Chrome):Chrome
浏览器版本 (如 126.0.6478.126):129.0.6668.90（正式版本） （64 位）
BewlyBewly 版本 (如 0.20.1):0.31.5

### 问题描述

收到别的用户私信的时候，顶栏不会有红点之类的提示
![image](https://github.com/user-attachments/assets/62c233a6-f1a8-4b20-8c20-8bdb03a82316)
![image](https://github.com/user-attachments/assets/3005aac6-4414-47e8-9dcf-274116aef420)

**Comment by AsakawaRyou** [comment]
点赞之类的会有提示

**Comment by hakadao** [comment]
原版b站如果是沒有關注的人私信也不會有提示吧，b站那邊這麼處理是防止騷擾
