### ISSUE TITLE
希望推荐的视频可以同时存在web和app

### ISSUE THREAD

**Issue by Knight-Hang** [BewlyBewly/BewlyBewly#1046]
目前推荐的视频的来源只能web和app二选一，有时候其中一端可能会推到感兴趣的视频，要一直切换比较麻烦，希望能够两端推荐的视频可以同时出现。
感觉可以混合在同一个页面里，也可以分开两栏，又或者其他更合理的布局方式。
另外希望可以标注推荐的来源。

**Comment by hakadao** [comment]
不太考慮，其實可以直接用 app 推介，app 推介普遍好過 web 的
另外b站web推介那邊其實是沒有提供不感興趣功能的，原版網頁的不感興趣只是前端處理後端沒有處理

那爲何bewlybelwy web端推介又用呢？因爲太多人把b站網頁推介不感興趣功能信以爲真，多次提 issue 轟炸，所以我也學b站弄了一個只有前端騙騙用戶的不感興趣。
