### ISSUE TITLE
Edge浏览器的标签页休眠之后回到页面切换内容不会获取，只能刷新整个网页才恢复正常。

### ISSUE THREAD

**Issue by HumanMus1c** [BewlyBewly/BewlyBewly#1048]
### 环境

浏览器 (如 Chrome): Edge
浏览器版本 (如 126.0.6478.126): 129.0.2792.65
BewlyBewly 版本 (如 0.20.1): 0.31.5

### 问题描述

（你这个issue模板输入框无法上传图片啊喂！）
就是Edge浏览器将阿B网页休眠之后再回到页面切换导航栏上的所有内容都不会刷新出来，只能刷新整个网页才恢复正常。

### 预期结果

Edge标签页休眠之后不影响导航栏内容的切换

**Comment by HumanMus1c** [comment]
![PixPin_2024-10-04_17-35-14](https://github.com/user-attachments/assets/8032598e-a624-405b-9c6b-c20583e2f35a)
![PixPin_2024-10-04_17-25-14](https://github.com/user-attachments/assets/0271b1fb-0387-4f40-9b19-2464f0b6576a)
![PixPin_2024-10-04_17-25-08](https://github.com/user-attachments/assets/cef8cc41-4a70-42a3-a65c-953c525a3194)
![PixPin_2024-10-04_17-25-04](https://github.com/user-attachments/assets/131aae47-743c-41c6-8eaf-9c9bd53aaed5)
![PixPin_2024-10-04_17-24-56](https://github.com/user-attachments/assets/a287eaec-a0f6-466e-9f0d-bdd3df7f56d4)

**Comment by HumanMus1c** [comment]
（哥，你这个issue模板输入框无法上传图片啊喂！）

**Comment by hakadao** [comment]
> （哥，你这个issue模板输入框无法上传图片啊喂！）

。。。。。。
![image](https://github.com/user-attachments/assets/5edf4107-07cf-471b-8732-d24e732f5988)

**Comment by hakadao** [comment]
瀏覽器休眠處理情況無法處理暫時
