### ISSUE TITLE
希望添加合集排序功能

### ISSUE THREAD

**Issue by liushengqi000** [BewlyBewly/BewlyBewly#1049]
b站合集最新上传的在最上面，播放的时候有种倒序观看的感觉。
希望能添加合集视频按上传时间正反排序功能。

**Comment by hakadao** [comment]
b站原本的播放邏輯不作改動
另外在README介紹那邊也說明了bewly定位
> BewlyBewly 主要专注页面的调整和优化，而不是完善功能和提升效率。
