### ISSUE TITLE
up主联合投稿导致主页出现多个重复视频

### ISSUE THREAD

**Issue by starmapler** [BewlyBewly/BewlyBewly#1050]
### 环境

浏览器 (如 Chrome): Edge
浏览器版本 (如 126.0.6478.126): 129.0.2792.79
BewlyBewly 版本 (如 0.20.1): 0.31.5

### 问题描述

![屏幕截图 2024-10-07 223332](https://github.com/user-attachments/assets/bff9bfcb-4b07-4ca6-9502-cca0d34359c5)
![屏幕截图 2024-10-07 223409](https://github.com/user-attachments/assets/0719d7e5-5595-46e0-b71e-2a36f4559e40)
如图所示，关注3位up联投会导致视频重复出现3次，之前也出现过多次复数位关注up联投导致同一视频连续出现的情况。

### 预期结果

是否可以缩减视频展示，以标注的形式展示联投up主？

**Comment by hakadao** [comment]
已修復，下一版本更新
