### ISSUE TITLE
有没有隐藏视频左上角关注按钮的功能

### ISSUE THREAD

**Issue by antnesswcm** [BewlyBewly/BewlyBewly#1055]
![image](https://github.com/user-attachments/assets/5d4de1be-6b4a-4161-9068-031e7206c4ad)

如图，视频左上角会显示关注按钮，虽然会消失，有没有隐藏它的功能呢

**Comment by hakadao** [comment]
這裏暫時不打算實現，現有比較完善的 [bilibili-cleaner](https://github.com/festoney8/bilibili-cleaner) 應該能解決此問題
