### ISSUE TITLE
好像通知系统出了bug?

### ISSUE THREAD

**Issue by xiaojiejieouo** [BewlyBewly/BewlyBewly#1056]
### 环境

浏览器 (edge):
浏览器版本 (129.0.2792.79):
BewlyBewly 版本 (0.31.6):

### 问题描述

不定时会出现,有时候通知会显示有一个新通知,但是是曾经看过的
显示为我的消息x1
![image](https://github.com/user-attachments/assets/74a6206c-fac7-4bb8-9d05-5da183ec955e)

**Comment by hakadao** [comment]
消息頁面只改了顏色沒改裏面邏輯，b站方面的問題無法處理
