### ISSUE TITLE
功能请求：可以加入黑名单功能吗？

### ISSUE THREAD

**Issue by RubiksCubei** [BewlyBewly/BewlyBewly#1058]
### 环境

Chrome 版本 129.0.6668.90
BewlyBewly 0.31.6

### 问题描述

之前一直在使用此油猴脚本
https://greasyfork.org/zh-CN/scripts/465675-b%E7%AB%99%E7%94%A8%E6%88%B7%E5%B1%8F%E8%94%BD
但启用插件后，此油猴脚本就会失效。
作者大大能实现一下类似的功能吗？

**Comment by hakadao** [comment]
已記錄到 #1025, 目前只打算在主頁使用，其他頁面不作處理
這裏先關閉了，有其他右鍵選單需求移步至 #1025 討論

**Comment by RubiksCubei** [comment]
用了几次右键 不想看此UP主 后，刷新几次页面依旧会出现此UP的视频。
