### ISSUE TITLE
FireFox中如果通过回车在搜索栏中进行搜索

### ISSUE THREAD

**Issue by Arsiendle** [BewlyBewly/BewlyBewly#1059]
### 环境

浏览器 (如 Chrome):zen browser（也是火狐）
浏览器版本 (如 126.0.6478.126):1.0.1-a.8
BewlyBewly 版本 (如 0.20.1):0.31.6

### 问题描述

就启用插件后在搜索栏中输入内容无法通过回车进行”搜索“功能

**Comment by hafterain** [comment]
已在一个全新安装的Zen Browser上测试，**此问题不存在**。

你可能漏看了右下角的提示，请选择「Allow pop-ups for bilibili.com」（如下图），之后就可以正常使用回车搜索功能。

![图片](https://github.com/user-attachments/assets/7234af5c-68cd-42fa-8b62-edf0d0c115b3)

※ 首次点击「Allow pop-ups for bilibili.com」时，可能会变为空白页。

**Comment by hakadao** [comment]
測過zen browser確實需要啓用上述權限才能正常開啓
