### ISSUE TITLE
【建议】抽屉打开的样式建议

### ISSUE THREAD

**Issue by zelbloo** [BewlyBewly/BewlyBewly#1060]
当前的抽屉打开样式有点粗糙，可以参考下Arc的弹窗实现

![image](https://github.com/user-attachments/assets/492cb718-01ab-4491-97e9-a277e7b9a4fa)

**Comment by hakadao** [comment]
首先抽屜開啓最大目的是製作成類似當頁頁面開啓播放頁的假像，所以要盡量和直接開啓播放頁的邊距位置差不多

弄成arc彈窗效果犧牲太多空間，暫時不會考慮。部分新功能和bug修正注定不能在一件事情打磨太久，誰不懂這麼設計好看這麼設計完美
