### ISSUE TITLE
BewlyBewly主页不刷新(扩展后台显示Service worker registration failed)(内含截图)

### ISSUE THREAD

**Issue by Simpleeasily** [BewlyBewly/BewlyBewly#1063]
### 环境

浏览器 (如 Chrome):Edge
浏览器版本 (如 126.0.6478.126):版本 92.0.902.67 (官方内部版本) (64 位)
BewlyBewly 版本 (如 0.20.1):0.31.7

### 问题描述

![屏幕截图 2024-10-12 223131](https://github.com/user-attachments/assets/577a6311-09ea-483d-82be-6790896ee3c0)
如图
![屏幕截图 2024-10-12 223022](https://github.com/user-attachments/assets/e60390d8-8005-43e3-8145-cc4e5c90bd21)
![屏幕截图 2024-10-12 223114](https://github.com/user-attachments/assets/f60d13e6-8b63-440a-af14-ca90a2ec8913)

**Comment by hakadao** [comment]
edge也可以用chrome web store，如無特殊要求請在那邊下載，在那邊下載也有自動更新功能

另外請注意你下載壓縮包後面沒有-firefox後綴

**Comment by Simpleeasily** [comment]
破案了，是我的Edge版本太垃圾了，更新了就没问题了，打扰了QWQ

**Comment by Simpleeasily** [comment]
起因是因为今天重新装了系统(Win10 LTSC)，系统自带的Edge没更新版本太老旧。还有感谢作者开发的软件！
