### ISSUE TITLE
为什么会要求读取我的浏览器历史记录？

### ISSUE THREAD

**Issue by MMMMMoris** [BewlyBewly/BewlyBewly#1069]
### 环境

浏览器 (如 Chrome): Chrome
浏览器版本 (如 126.0.6478.126): 129.0.6668.101 (Official Build) (64-bit) (cohort: Holdback) 
BewlyBewly 版本 (如 0.20.1): 0.32.0

### 问题描述

![image](https://github.com/user-attachments/assets/b4ee7716-a27f-4814-b762-52afc392ba92)

### 预期结果

我只是用这个插件来修改B站，为何要获取读取我的浏览历史的权限？

**Comment by hakadao** [comment]
browser.tabs 用於後臺開啓頁面，tabs權限也有讀取瀏覽記錄用途但這裏沒有用
chrome 下載時會說明最壞情況下和最高風險項確保之後你使用的安全

另外專案開源，誰都可以看到背後處理了甚麼
