### ISSUE TITLE
在首页，如果是关注的up的视频，那么视频底下不会显示该视频发布的时间

### ISSUE THREAD

**Issue by Skywalker144** [BewlyBewly/BewlyBewly#1071]
### 环境

浏览器 (如 Chrome):Chrome
浏览器版本 (如 126.0.6478.126):128.0.6613.138
BewlyBewly 版本 (如 0.20.1):0.32.0

### 问题描述

![image](https://github.com/user-attachments/assets/3fdd5f09-c7fc-4d2a-9294-055283986ef8)
如图，关注的up的视频底下不会显示视频发布时间

**Comment by hafterain** [comment]
在全新安装的BewlyBewly下做了测试，此问题似乎不存在：

![图片](https://github.com/user-attachments/assets/67e4f71f-658d-4be9-9c77-4d168b0a0ac3)

你有安装其他JS脚本、进行自定义CSS之类的操作吗？

**Comment by Skywalker144** [comment]
之前确实使用了tampermonkey，但是关闭后仍存在问题
后面发现，是设置中的“推荐模式”的问题，当我切换到Web，该问题解决了，但当我切换到App，该问题又出现了
<img width="1280" alt="Snipaste_2024-10-17_21-38-27" src="https://github.com/user-attachments/assets/c6a6a406-251a-4cb8-86c4-82da24e05742">
<img width="1280" alt="Snipaste_2024-10-17_21-34-54" src="https://github.com/user-attachments/assets/08bb3bb3-5758-4184-89c6-b34f24c21b94">

（由于B站原生客户端中，关注的up也是不会显示发布时间的），该问题能解决吗？

**Comment by hakadao** [comment]
> 之前确实使用了tampermonkey，但是关闭后仍存在问题 后面发现，是设置中的“推荐模式”的问题，当我切换到Web，该问题解决了，但当我切换到App，该问题又出现了 <img alt="Snipaste_2024-10-17_21-38-27" width="1280" src="https://private-user-images.githubusercontent.com/122092675/377490153-c6a6a406-251a-4cb8-86c4-82da24e05742.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxODA1NTUsIm5iZiI6MTcyOTE4MDI1NSwicGF0aCI6Ii8xMjIwOTI2NzUvMzc3NDkwMTUzLWM2YTZhNDA2LTI1MWEtNGNiOC04NmM0LTgyZGEyNGUwNTc0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QxNTUwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjJiMmZiY2FlOGI5Mjc4MDBkYTlhMGQzZmFjNTZiNWY0M2NmMzY5YWQ4MDhhMzEyNDc4Y2Q4ZTE4MDRhNzM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1y3rOevRKmvuNSQ5IXtY7-tnkZadIu6affEucDmycz8"> <img alt="Snipaste_2024-10-17_21-34-54" width="1280" src="https://private-user-images.githubusercontent.com/122092675/377490313-08bb3bb3-5758-4184-89c6-b34f24c21b94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxODA1NTUsIm5iZiI6MTcyOTE4MDI1NSwicGF0aCI6Ii8xMjIwOTI2NzUvMzc3NDkwMzEzLTA4YmIzYmIzLTU3NTgtNDE4NC04OWM2LWIzNGYyNGMyMWI5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QxNTUwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMmZjOGExZDI0MTM1MDY1NWIyYTI1NGRhYmUwMTZjNGY2ODE4YjE3ZDFmOWEwZGU5OTc1NWQxNDA5YzVmN2ZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zjulLvZalNdh5VTv1JoSvmWGFtz2mAZnQk5qmrKYex8">
> 
> （由于B站原生客户端中，关注的up也是不会显示发布时间的），该问题能解决吗？

ipad那邊推介沒有返回時間內容如果是已經關注了的up主

**Comment by Skywalker144** [comment]
> > 之前确实使用了tampermonkey，但是关闭后仍存在问题 后面发现，是设置中的“推荐模式”的问题，当我切换到Web，该问题解决了，但当我切换到App，该问题又出现了 <img alt="Snipaste_2024-10-17_21-38-27" width="1280" src="https://private-user-images.githubusercontent.com/122092675/377490153-c6a6a406-251a-4cb8-86c4-82da24e05742.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxODA1NTUsIm5iZiI6MTcyOTE4MDI1NSwicGF0aCI6Ii8xMjIwOTI2NzUvMzc3NDkwMTUzLWM2YTZhNDA2LTI1MWEtNGNiOC04NmM0LTgyZGEyNGUwNTc0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QxNTUwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjJiMmZiY2FlOGI5Mjc4MDBkYTlhMGQzZmFjNTZiNWY0M2NmMzY5YWQ4MDhhMzEyNDc4Y2Q4ZTE4MDRhNzM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1y3rOevRKmvuNSQ5IXtY7-tnkZadIu6affEucDmycz8"> <img alt="Snipaste_2024-10-17_21-34-54" width="1280" src="https://private-user-images.githubusercontent.com/122092675/377490313-08bb3bb3-5758-4184-89c6-b34f24c21b94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxODA1NTUsIm5iZiI6MTcyOTE4MDI1NSwicGF0aCI6Ii8xMjIwOTI2NzUvMzc3NDkwMzEzLTA4YmIzYmIzLTU3NTgtNDE4NC04OWM2LWIzNGYyNGMyMWI5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QxNTUwNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMmZjOGExZDI0MTM1MDY1NWIyYTI1NGRhYmUwMTZjNGY2ODE4YjE3ZDFmOWEwZGU5OTc1NWQxNDA5YzVmN2ZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zjulLvZalNdh5VTv1JoSvmWGFtz2mAZnQk5qmrKYex8">
> > （由于B站原生客户端中，关注的up也是不会显示发布时间的），该问题能解决吗？
> 
> ipad那邊推介沒有返回時間內容如果是已經關注了的up主

什么意思？

**Comment by hakadao** [comment]
https://github.com/BewlyBewly/BewlyBewly/issues/730#issuecomment-2185070417
