### ISSUE TITLE
“不感兴趣”按钮报错

### ISSUE THREAD

**Issue by LvWind** [BewlyBewly/BewlyBewly#1073]
### 环境

浏览器 (如 Chrome): Chrome
浏览器版本 (如 126.0.6478.126): 129.0.6668.91
BewlyBewly 版本 (如 0.20.1): 0.32.0

### 问题描述

个性推荐中的视频，菜单内的“不感兴趣”菜单提交报错，提示“请求错误”

**Comment by hakadao** [comment]
請先取得或重新取得access key試試
