### ISSUE TITLE
抽屉模式多次打开视频时油猴脚本内存未卸载干净

### ISSUE THREAD

**Issue by Aarondongsq** [BewlyBewly/BewlyBewly#1075]
### 环境

浏览器：Chrome
浏览器版本：126.0.6478.249
BewlyBewly 版本：0.32.0

### 问题描述

使用抽屉模式时多次打开，油猴脚本将会积攒过多内存

### 预期结果

关闭标签页时油猴脚本内存卸载

**Comment by hakadao** [comment]
我還第一次聽聞chrome擴充功能會影響油猴內存這個問題，兩者完全不相關

但是如果你想說抽屜關閉沒有釋放資源的話，v0.32.0早就在關閉抽屜前做了處理

**Comment by Aarondongsq** [comment]
那如何卸载呢

**Comment by hakadao** [comment]
> 那如何卸载呢

關閉抽屜就會釋放資源，不用額外處理

**Comment by Aarondongsq** [comment]
我是指油猴脚本的，总不能一直刷新吧

**Comment by hakadao** [comment]
> 我是指油猴脚本的，总不能一直刷新吧

擴充功能和油猴腳本兩個東西來的，請排除是否有某個油猴腳本有處理問題
