### ISSUE TITLE
限制访问网站再取消后就无法登录，必须卸载重装扩展

### ISSUE THREAD

**Issue by 112sb** [BewlyBewly/BewlyBewly#1077]
### 环境

浏览器 (如 Chrome): Chrome
浏览器版本 (如 126.0.6478.126):
BewlyBewly 版本 (如 0.20.1):最新版本

### 问题描述

限制访问网站再取消后就无法登录，必须卸载重装扩展

**Comment by hakadao** [comment]
你限制了擴充功能訪問網站原本的api當然無法登入啊，你限制最基本的功能之後無法使用也算是bug？

**Comment by 112sb** [comment]
> 你限制了擴充功能訪問網站原本的api當然無法登入啊，你限制最基本的功能之後無法使用也算是bug？
<img width="1268" alt="屏幕截图 2024-10-24 221910" src="https://github.com/user-attachments/assets/554c3259-e208-47ca-8c2e-6147c86f0503">
不是啊，限制然后再取消限制后会无法登录，然后网页开始狂吃cpu
