### ISSUE TITLE
在首页使用了“不想看此up主”，而且是对同一个视频屏蔽了两次

### ISSUE THREAD

**Issue by 694185819** [BewlyBewly/BewlyBewly#1081]
### 环境

浏览器 (如 Chrome):目前版本 129.0.6668.101（正式版本） （64 位）
浏览器版本 (如 126.0.6478.126):
BewlyBewly 版本 (如 0.20.1):0.32.0

### 问题描述

在首页使用了“不想看此up主”，而且是对同一个视频屏蔽了两次，我以为是本地文件生成并屏蔽，怎么依旧重复出现。以下是被我使用插件重复屏蔽的视频
https://www.bilibili.com/video/BV1fVmLYKEfq

**Comment by MidnightCrowing** [comment]
重复问题，参考#995
