### ISSUE TITLE
主页搜索框键盘直接输英文S和C不能用了

### ISSUE THREAD

**Issue by bing996** [BewlyBewly/BewlyBewly#1085]
### 环境

浏览器 (如 Chrome):Firefox
浏览器版本 (如 126.0.6478.126):131.0.3
BewlyBewly 版本 (如 0.20.1):0.33.1

### 问题描述

主页搜索框键盘直接输英文S和C不能用了，按了没反应,但是二级搜索页面就能打出来

**Comment by hakadao** [comment]
是否有同時使用其他擴充功能和腳本把這兩個鍵位佔用

**Comment by hakadao** [comment]
無法重現，需提供更多說明

**Comment by zhendery** [comment]
我也是！我还以为是键盘坏了，测试了发现只有s和c无法键入！

**Comment by zhendery** [comment]
我也是！我还以为是键盘坏了，测试了发现只有s和c无法键入！windows 10自带的输入法，只有英文不能输入，中文可以正常输入。
我是Edge 130.0.2849.46 (正式版本) (64 位)，BewlyBewly 版本 0.33.1
@hakadao

**Comment by imkyleshing** [comment]
我也是，不知道怎么排查

**Comment by bing996** [comment]
@hakadao @imkyleshing   正如大佬所说，关了浮图秀问题就解决了，谢谢！

**Comment by zhendery** [comment]
> @hakadao @imkyleshing 正如大佬所说，关了浮图秀问题就解决了，谢谢！

啊这，可是浮图秀也很好用啊，害，我有办法了！在中文输入状态输入s后按enter就可以了。
