### ISSUE TITLE
Firefox浏览器里抽屉模式失效

### ISSUE THREAD

**Issue by DrZhang1208** [BewlyBewly/BewlyBewly#1087]
### 环境

浏览器 (如 Chrome):Firefox
浏览器版本 (如 126.0.6478.126):正式版最新版和nightly 133.0a1 都会复现
BewlyBewly 版本 (如 0.20.1):0.33.1

### 问题描述

https://github.com/user-attachments/assets/810eed92-44cc-4bd2-9c1c-f92fcfb7c303

**Comment by DrZhang1208** [comment]
![Screenshot_2024-10-22_17-06-04](https://github.com/user-attachments/assets/71b85238-819c-449c-a187-63528c1221fc)

**Comment by hakadao** [comment]
重複 #1010
