### ISSUE TITLE
[Bug] 字体在125%缩放下很模糊

### ISSUE THREAD

**Issue by ShiinaManatsu** [BewlyBewly/BewlyBewly#1088]
### 环境

浏览器 (如 Chrome):
浏览器版本 (如 129.0):
BewlyBewly 版本 (如 0.33.1):

### 问题描述

字体在125%缩放下很模糊
![Snipaste_2024-10-22_20-48-23](https://github.com/user-attachments/assets/da26e856-fa52-43ca-9ff7-bca666652e8e)
![Snipaste_2024-10-22_20-48-00](https://github.com/user-attachments/assets/e9f889e0-b640-4aea-91ee-5ebd17c89a1c)

试了下150%, 很清晰, 但我比较习惯125%缩放

**Comment by starknt** [comment]
这个可以算是bug也可以不算是bug，因为本质上说其实是 chrome 的问题，详情可以看 #49

**Comment by ShiinaManatsu** [comment]
> 这个可以算是bug也可以不算是bug，因为本质上说其实是 chrome 的问题，详情可以看 #49

只能改成110%先用着了
