### ISSUE TITLE
首页搜索框输入关键词后回车，无法正确跳转至搜索内容页面

### ISSUE THREAD

**Issue by Ezer015** [BewlyBewly/BewlyBewly#1089]
### 环境

浏览器 (如 Chrome): Zen Browser (Firefox 内核)
浏览器版本 (如 126.0.6478.126): 1.0.1-a.11
BewlyBewly 版本 (如 0.20.1): 0.33.1

### 问题描述

首页搜索框输入关键词后回车，页面无变化。
![图片](https://github.com/user-attachments/assets/73295df9-9cbd-48ed-9c43-02966b38e0a0)

### 预期结果

跳转至搜索内容页面

**Comment by hakadao** [comment]
https://github.com/BewlyBewly/BewlyBewly/issues/1059#issuecomment-2409056372
