### ISSUE TITLE
希望能適配Drag to Preview

### ISSUE THREAD

**Issue by Shijinzakaue** [BewlyBewly/BewlyBewly#1091]
希望能適配或是內置 [Drag to Preview](https://chromewebstore.google.com/detail/drag-to-preview/fjllepdpgikphekgbinhpdkalliiejdh)，像是在其他頁面能拖拽喚出 (也不一定要拖拽)，由於在其他頁面也是通用的，我個人覺得可能可以替代抽屜功能(?

https://github.com/user-attachments/assets/f3b49d16-8626-4d20-ac12-ec096f75970e

只是感覺實現難度有點大，如果覺得還行再做吧

**Comment by hakadao** [comment]
這裏我猜是 [Drag to Preview](https://chromewebstore.google.com/detail/drag-to-preview/fjllepdpgikphekgbinhpdkalliiejdh) 沒有處理到 Shadow Dom 裏面的情況，當前要處理的話有點無解，最好還是向 Drag to Preview 匯報這個問題

**Comment by hakadao** [comment]
同樣你在使用了 shadow dom 的評論區拖放用戶頭像是不能打開空間頁的
