### ISSUE TITLE
希望添加自动打开字幕的功能

### ISSUE THREAD

**Issue by LingerJAB** [BewlyBewly/BewlyBewly#1093]
经常看连续的视频合集时候没有字幕，但是打开字幕后B站自动在下一次播放视频时候关闭字幕，还要手动打开很麻烦，希望能添加自动打开的功能

最好是能分按系列自动打开还是持续保持开启的按钮

**Comment by hakadao** [comment]
![IMG_20241026_031130.jpg](https://github.com/user-attachments/assets/1404eae0-dc92-4af6-9820-28906c3d6dd0)
