### ISSUE TITLE
csrf校验失败

### ISSUE THREAD

**Issue by itheword** [BewlyBewly/BewlyBewly#1097]
### 环境

浏览器 (如 Chrome):
浏览器版本 (如 126.0.6478.126):
BewlyBewly 版本 (如 0.20.1):

### 问题描述

csrf校验失败,无法发弹幕和关注up
![image](https://github.com/user-attachments/assets/714f3562-547b-493f-8334-c26d7c4a1668)

**Comment by hakadao** [comment]
能否有重現，另外問題模板信息不明確
