### ISSUE TITLE
openIframeDrawer() 无法打开//开头的url

### ISSUE THREAD

**Issue by MidnightCrowing** [BewlyBewly/BewlyBewly#1104]
### 环境

BewlyBewly 版本 : 0.34.2

### 问题描述

openIframeDrawer() 无法打开//开头的url，控制台中报错：
![recording](https://github.com/user-attachments/assets/5e94767c-e569-44db-925f-a66c4007b74b)

该问题在 `稍后再看` 和 `观看历史` 中存在（`稍后再看` 在本issue提出前在 #1103 中做过修改）

**Comment by hakadao** [comment]
這重構改好了
https://github.com/BewlyBewly/BewlyBewly/commit/c09c65f7294b81abfe4ca876cebc50ce7cf59e4f
