### ISSUE TITLE
B站搜索框文本选择没有蓝色背景突显，也不知道选择了哪里

### ISSUE THREAD

**Issue by LuWeiHuan** [BewlyBewly/BewlyBewly#1105]
### 环境

浏览器 Chrome 
BewlyBewly 版本 0.34.2:

### 问题描述

想选中搜索框里的一些文本，却没有蓝色被背景凸显，也不知道选到了哪里，能否修复一下，只有关闭了BewlyBewly手术框才正常

**Comment by MidnightCrowing** [comment]
参考这个 ##792

**Comment by LuWeiHuan** [comment]
> 参考这个 ##792

还是不知道修改哪里，要去设置自定义CSS吗？用户没设置的情况下使用默认蓝色最为底色不行吗？怎么会直接没有呢？

**Comment by LuWeiHuan** [comment]
> 另外插件可以自定义css，如果想要蓝色背景的话可以使用自定义css： ![image](https://private-user-images.githubusercontent.com/110297461/382472811-d02b836d-ba6b-42a2-aa64-f92da541ad86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NTIzMDIsIm5iZiI6MTczMDU1MjAwMiwicGF0aCI6Ii8xMTAyOTc0NjEvMzgyNDcyODExLWQwMmI4MzZkLWJhNmItNDJhMi1hYTY0LWY5MmRhNTQxYWQ4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQxMjUzMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MTQ2MzFjNWU4MTkwMDFkOTljODc2YWUyOThkZjg4M2FlNDU0NmQ0MjZjMjUwYmU3MjZlMjFkZDgxYTU2NTI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tZphg9MoHWlLLb5eBAJIe-Xzml94a039qGQO7FSn3Ao)
> 
> ```css
> .bewly-design *::selection,
> .bewly-wrapper *::selection {
>   background: #0337A1 !important; /* 取消自定义背景 */
> }
> ```
> 
> （ `#0337A1` 是我用工具提取的值，我也不知道默认值是多少😅）

还要自定义CSS？用户默认没设置的情况下使用默认蓝色最为底色不行吗？怎么会直接没有呢？还是谢谢呀。

**Comment by LuWeiHuan** [comment]
> 另外插件可以自定义css，如果想要蓝色背景的话可以使用自定义css： ![image](https://private-user-images.githubusercontent.com/110297461/382472811-d02b836d-ba6b-42a2-aa64-f92da541ad86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NTIzMDIsIm5iZiI6MTczMDU1MjAwMiwicGF0aCI6Ii8xMTAyOTc0NjEvMzgyNDcyODExLWQwMmI4MzZkLWJhNmItNDJhMi1hYTY0LWY5MmRhNTQxYWQ4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQxMjUzMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MTQ2MzFjNWU4MTkwMDFkOTljODc2YWUyOThkZjg4M2FlNDU0NmQ0MjZjMjUwYmU3MjZlMjFkZDgxYTU2NTI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tZphg9MoHWlLLb5eBAJIe-Xzml94a039qGQO7FSn3Ao)
> 
> ```css
> .bewly-design *::selection,
> .bewly-wrapper *::selection {
>   background: #0337A1 !important; /* 取消自定义背景 */
> }
> ```
> 
> （ `#0337A1` 是我用工具提取的值，我也不知道默认值是多少😅）

还要自定义CSS？默认情况下使用系统默认蓝色最为底色不就行了嘛？如果首次安装就像透明一样没有感觉过。问题解决了，谢谢你的帮忙。
