### ISSUE TITLE
[Bug] 右上角的直播动态里有重复项

### ISSUE THREAD

**Issue by ShiinaManatsu** [BewlyBewly/BewlyBewly#1111]
### 环境

浏览器 (如 Chrome): chrome
浏览器版本 (如 126.0.6478.126): 最新
BewlyBewly 版本 (如 0.20.1): 0.34.2

### 问题描述

右上角的直播动态里也会有重复的内容

![image](https://github.com/user-attachments/assets/385bfbe7-0a5a-4188-b0ed-6aee2244dd39)

**Comment by ShiinaManatsu** [comment]
看起来是偶发, 不是百分百出现

**Comment by MidnightCrowing** [comment]
嘶，感觉和 #962 的原因一样？先看看吧，如果情况经常出现再修😉

**Comment by hakadao** [comment]
應該就只是b站返回後臺數據問題，不太影響整體使用
