### ISSUE TITLE
主页闲置一段时间之后插件的刷新无法正常重新加载，需要刷新主页才能正常显示

### ISSUE THREAD

**Issue by slienceevi** [BewlyBewly/BewlyBewly#1116]
### 环境

浏览器 (如 Chrome):edge
浏览器版本 (如 126.0.6478.126):130.0.2849.68 
BewlyBewly 版本 (如 0.20.1):0.34.2

### 问题描述

主页闲置一段时间之后插件的刷新无法正常重新加载，需要刷新主页才能正常显示。
包括顶栏的动态，收藏夹，历史记录都无法显示。
![7082e4d2-4c3d-47de-961d-16234603347b](https://github.com/user-attachments/assets/e5c04b72-754a-4a59-b6c2-2d24eb70ac4c)

**Comment by MidnightCrowing** [comment]
看看和这个是不是重复了 #1048

**Comment by hakadao** [comment]
這個問題不知道怎麼解決，等別人看看如何處理吧
不知道edge休眠會對擴充功能怎麼處理
