### ISSUE TITLE
对视频进行不感兴趣操作时出现请求错误弹窗

### ISSUE THREAD

**Issue by Einzieg** [BewlyBewly/BewlyBewly#1120]
### 环境

浏览器 (如 Chrome): Chrome
浏览器版本 (如 126.0.6478.126): 130.0.6723.117
BewlyBewly 版本 (如 0.20.1): 0.34.2

### 问题描述

![image](https://github.com/user-attachments/assets/031149e8-0178-480a-9e14-72190a0f6160)

**Comment by hakadao** [comment]
請嘗試重新取得access key之後看看
