### ISSUE TITLE
打开主页黑屏

### ISSUE THREAD

**Issue by KLiuZC** [BewlyBewly/BewlyBewly#1123]
### 环境

浏览器 (如 Chrome): Chrome
浏览器版本 (如 126.0.6478.126): 130.0.6723.117
BewlyBewly 版本 (如 0.20.1): 0.34.3

### 问题描述

https://github.com/user-attachments/assets/11166cbc-408e-4f52-8b88-bb4ee773a67d

打开主页时，右下角有广告一闪而过，然后就是黑屏

**Comment by MidnightCrowing** [comment]
您好！请尝试禁用浏览器中的其他插件和油猴脚本，并重新加载页面，以确定是插件导致的问题。如果问题仍然存在，能否请您提供浏览器控制台的日志，这样有助于我们更好地定位问题原因。感谢您的反馈！

**Comment by KLiuZC** [comment]
发现是与插件Qantas Shopping Points-Prompter冲突，关闭插件恢复正常
