### ISSUE TITLE
用"抽屉打开"功能播放视频时点击右上角的“在新标签页打开”，要關閉抽屜

### ISSUE THREAD

**Issue by Winnable1** [BewlyBewly/BewlyBewly#1124]
### 环境

浏览器: Chrome
浏览器版本: 130.0.6723.119
BewlyBewly 版本: v0.34.3

### 问题描述

用"抽屉打开"功能播放视频时点击右上角的“在新标签页打开”，新标签页会播放视频，但抽屉内的视频也还在播放，还得回去手动关闭抽屉

### 预期结果

点击“在新标签页打开”后自动关闭抽屉

**Comment by hakadao** [comment]
我不認爲這應該歸爲一個bug，這只是一個操作習慣，並不是很多人喜歡這種操作邏輯
有些人可能看到在抽屜的推介影片是喜歡的但是一點就關閉了，這麼做不太合理
