### ISSUE TITLE
[Feature Request] 可不可以添加右侧评论区，很多时候想一边看视频，一边看评论

### ISSUE THREAD

**Issue by Leiyi548** [BewlyBewly/BewlyBewly#1127]
### 环境

浏览器 (如 Chrome):
浏览器版本 (如 126.0.6478.126):
BewlyBewly 版本 (如 0.20.1):

### 问题描述

类似哔哩助理
![图片](https://github.com/user-attachments/assets/33139625-bdd7-4e94-aed9-2696d3ba40d4)

**Comment by hakadao** [comment]
BewlyBewly主要是想除主頁外其他頁面減少調整，請考慮使用其他樣式和腳本解決

**Comment by Leiyi548** [comment]
> BewlyBewly主要是想除主頁外其他頁面減少調整，請考慮使用其他樣式和腳本解決

请问您知道有其他样式和脚本吗？
