### ISSUE TITLE
適配 分P详情页优化

### ISSUE THREAD

**Issue by hakadao** [BewlyBewly/BewlyBewly#1128]
![image](https://github.com/user-attachments/assets/7990ce3d-2d34-41f5-9ade-9f55dce5dbac)

https://greasyfork.org/zh-CN/scripts/490676-b%E7%AB%99-bilibili-%E5%88%86p%E8%A7%86%E9%A2%91%E8%AF%A6%E6%83%85%E9%A1%B5%E4%BC%98%E5%8C%96

**Comment by Octobersama** [comment]
对于b站新版的合集(带封面)的显示效果不好
![image](https://github.com/user-attachments/assets/30df1f57-2e21-4160-bafb-f152a4833be2)
图示合集:https://space.bilibili.com/14229967/channel/collectiondetail?sid=1533671

**Comment by Octobersama** [comment]
@hakadao
