### ISSUE TITLE
[FR]能否在使用原版B站首页时,加入bewlybewly的dock栏与侧边栏

### ISSUE THREAD

**Issue by hou9999** [BewlyBewly/BewlyBewly#1131]
### 环境

BewlyBewly 版本 :0.35.0

![chrome_XRkCVpbxKo](https://github.com/user-attachments/assets/276c55e5-319d-4dcb-900f-f0da436e45b8)

**Comment by hakadao** [comment]
計劃改成這樣，但是暫沒有時間
https://github.com/BewlyBewly/BewlyBewly/pull/1000
