### ISSUE TITLE
已登录时收藏夹无法查看，显示请先登录

### ISSUE THREAD

**Issue by wyllwyc** [BewlyBewly/BewlyBewly#1138]
### 环境

浏览器 (Edge):
浏览器版本 (131.0.2903.51):
BewlyBewly 版本 (如 0.35.1):

### 问题描述

已登录时收藏夹无法查看,
<img width="1280" alt="PixPin_2024-11-21_14-41-44" src="https://github.com/user-attachments/assets/6672aa90-345d-4f1b-af2d-43af360870e8">

**Comment by hakadao** [comment]
沒有重現，f5後還是嗎

**Comment by wyllwyc** [comment]
F5还后是，有可能是edge的问题,我在Chrome,夸克和Firefox均无法复现这个问题，删除掉新版重新安装旧版此问题依旧存在

**Comment by wyllwyc** [comment]
我在清除全edge部收数据后重新登录，此问题不再出现。

**Comment by wyllwyc** [comment]
在我清除edge全部数据后重新登录，此问题不再出现。

**Comment by wyllwyc** [comment]
在清除edge全部数据后，重新登录，此问题不再出现
