### ISSUE TITLE
[Feature Request] 并列这两个模块到导航栏但是不合并？

### ISSUE THREAD

**Issue by Ender-Wang** [BewlyBewly/BewlyBewly#1139]
### 环境

Chrome: 131.0.6778.86
BewlyBewly: v0.35.1

### 问题描述

目前这个排版总感觉导航栏这块有点乱， 可能这样改了之后会好很多。
![Google Chrome 2024-11-21 14 16 21](https://github.com/user-attachments/assets/634c799e-7b8d-44b7-bb61-20f0846d0348)

**Comment by Ender-Wang** [comment]
> 想問下這種設計如何考慮不同寬度的螢幕顯示

标准1080P的屏幕不是什么问题吧，市面上用宽屏的人比竖屏多很多吧

**Comment by hakadao** [comment]
收藏頁那邊怎麼處理，這兩個搜尋欄放一起迷惑性很大
另外本身頂欄可以設定自動收起然後就顯示分類tabs內容

**Comment by Ender-Wang** [comment]
> 收藏頁那邊怎麼處理，這兩個搜尋欄放一起迷惑性很大 另外本身頂欄可以設定自動收起然後就顯示分類tabs內容

OK.
