### ISSUE TITLE
搜索观看历史始终为空

### ISSUE THREAD

**Issue by Nathalie-Annis** [BewlyBewly/BewlyBewly#1141]
无论我输入什么关键词,搜索观看历史都搜索不到,一片空白

**Comment by TommyLin-812** [comment]
我没有这个问题，版本0.35.1

**Comment by Nathalie-Annis** [comment]
Chrome，版本0.35.1

https://github.com/user-attachments/assets/790f5496-b82a-43a3-adca-215f190054c8

**Comment by MidnightCrowing** [comment]
我这边也是，似乎是api的问题？
将 `src/background/messageListeners/api/history.ts` 文件中第19行：
> https://api.bilibili.com/x/web-goblin/history/search

替换成
> https://api.bilibili.com/x/web-interface/history/search

该问题可以解决，但不确定其他用户是否也有类似问题

**Comment by hakadao** [comment]
> 我这边也是，似乎是api的问题？ 将 `src/background/messageListeners/api/history.ts` 文件中第19行：
> 
> > https://api.bilibili.com/x/web-goblin/history/search
> 
> 替换成
> 
> > https://api.bilibili.com/x/web-interface/history/search
> 
> 该问题可以解决，但不确定其他用户是否也有类似问题

沒有問題的話換吧，之後直接合併
