### ISSUE TITLE
首页无法通过page up/down进行滚动

### ISSUE THREAD

**Issue by Chumion** [BewlyBewly/BewlyBewly#1142]
### 环境

浏览器: brave
浏览器版本: Version 1.73.91 Chromium: 131.0.6778.85 (Official Build) (arm64)
BewlyBewly 版本:  0.35.1

### 问题描述

- 在BewlyBewly首页时无法通过键盘上的page up/down键进行页面滚动
- 安装了vimium插件的情况下也无法使用jk进行滚动
- 视频播放页面，个人中心页面正常
- 在兼容性设置中开启Use the original Bilibili homepage后正常

**Comment by hakadao** [comment]
現在爲了達到windows透明捲動調效果而這麼處理的，但影響部分插件使用

要麼就是不用透明捲動條處理

**Comment by Chumion** [comment]
> 1. 可能需要在打开页面后，先用鼠标点击一下页面，才能正常使用键盘上的 Page Up/Down 键进行滚动。  
> 
> 2. 关于 Vimium 插件的问题，目前暂时无法解决，参考 #823。  
> 
> 

感谢，用鼠标点击后page up/down 可以正常工作。

**Comment by Chumion** [comment]
> 現在爲了達到windows透明捲動調效果而這麼處理的，但影響部分插件使用
> 
> 要麼就是不用透明捲動條處理

请问当前有关闭的方法吗，我在设置中没能找到相关的选项。

**Comment by hakadao** [comment]
> > 現在爲了達到windows透明捲動調效果而這麼處理的，但影響部分插件使用
> > 
> > 要麼就是不用透明捲動條處理
> 
> 请问当前有关闭的方法吗，我在设置中没能找到相关的选项。

這要重構，可能也會導致一堆人有意見和現有功能失效

**Comment by Chumion** [comment]
> > > 現在爲了達到windows透明捲動調效果而這麼處理的，但影響部分插件使用
> > > 
> > > 要麼就是不用透明捲動條處理
> > 
> > 请问当前有关闭的方法吗，我在设置中没能找到相关的选项。
> 
> 這要重構，可能也會導致一堆人有意見和現有功能失效

了解🫡。谢谢各位，除去这些小的兼容问题插件非常漂亮好用👍🏻

**Comment by Chumion** [comment]
一个workaround:

Vimium C插件可以正常滚动BewlyBewly首页。和page up/down一样需要先点击一下页面空白处。
