### ISSUE TITLE
首页点击搜索框后内容无法拖动

### ISSUE THREAD

**Issue by Aarondongsq** [BewlyBewly/BewlyBewly#1143]
### 环境

浏览器 (如 Chrome): Edge
浏览器版本 (如 126.0.6478.126): 131.0.2903.63
BewlyBewly 版本 (如 0.20.1): 0.35.1
下载来源：Chrome 应用商店

### 问题描述

在首页点击搜索框后（未开启“首页使用搜索页模式”），内容无法拖动

**Comment by Aarondongsq** [comment]
有时点击后不太明显

**Comment by hakadao** [comment]
> 有时点击后不太明显

還是不能理解，能否截圖說明

**Comment by Aarondongsq** [comment]
![image](https://github.com/user-attachments/assets/2675afd4-ec39-4b91-942b-1b0fb40dd23a)

**Comment by hakadao** [comment]
你點擊後要點擊空白才能拖動啊，防止誤操作爲何這算是bug
