### ISSUE TITLE
有关主页以外Dock栏的显示

### ISSUE THREAD

**Issue by Nathalie-Annis** [BewlyBewly/BewlyBewly#1146]
https://github.com/user-attachments/assets/3e653895-3c4c-43e1-a0ad-da980bd7fe93

请问视频页默认情况下只显示一半的dock栏，鼠标移动到上面才完整显示是咱们设定好的效果，还是我这里显示的问题？

**Comment by hakadao** [comment]
現在跟bilibili evolved一樣處理了，因爲之前還是有人覺得這樣佔位
