### ISSUE TITLE
“首页使用搜索页模式”下的样式优化

### ISSUE THREAD

**Issue by Nathalie-Annis** [BewlyBewly/BewlyBewly#1147]
https://github.com/user-attachments/assets/bbc4830d-7f54-4a69-895b-03d67f8525e1

现在在启用首页搜索页模式的情况下,顶栏在没有滑动到页面顶部的时候会与搜索栏重复显示,同时存在两个不美观,建议顶栏在移动到搜索页搜索栏的时候就不再显示

**Comment by hakadao** [comment]
duplidate #633
