### ISSUE TITLE
黑暗模式下部分字体与背景颜色相同

### ISSUE THREAD

**Issue by cns1rius** [BewlyBewly/BewlyBewly#1148]
### 环境

浏览器: Edge
浏览器版本: 131.0.2903.63 (正式版本)
BewlyBewly 版本: 0.35.1

### 问题描述

![image](https://github.com/user-attachments/assets/9af87309-7030-4cc4-a4be-9745fe776d78)
AI小助手在黑暗模式下为白底白字！

### 预期结果

黑底白字或白底黑字

**Comment by MidnightCrowing** [comment]
可否提供一下页面网址

**Comment by cns1rius** [comment]
所有的视频点aixiao'zhu's小助手都会白底白字
![image](https://github.com/user-attachments/assets/91395725-c4b3-4533-82da-30bf7df69598)

**Comment by cns1rius** [comment]
> 可否提供一下页面网址
所有的视频点ai小助手都会白底白字
![image](https://github.com/user-attachments/assets/3fab8518-dc24-483b-ac98-71aed056bbfa)
