### ISSUE TITLE
新版个人主页图文投稿出现错位情况

### ISSUE THREAD

**Issue by peng233163** [BewlyBewly/BewlyBewly#1155]
### 环境

浏览器 (如 Chrome):EDGE
浏览器版本 (如 126.0.6478.126):131.0.2903.70
BewlyBewly 版本 (如 0.20.1):0.35.1

### 问题描述

插件打开新版个人主页图文投稿出现错位情况
正常状态：
![image](https://github.com/user-attachments/assets/dde23c9a-446e-4ba9-8d60-2f76319f4b7b)
使用插件：
![image](https://github.com/user-attachments/assets/2d08b350-cada-49e5-9fc3-73cf41a7ad57)
希望能修复一下

**Comment by kardusenor** [comment]
最新版bewlybewly在firefox浏览器仍存在该问题
