### ISSUE TITLE
新版个人主页头图深色模式无法显示 浅色模式头图错位

### ISSUE THREAD

**Issue by Octobersama** [BewlyBewly/BewlyBewly#1157]
### 环境

浏览器:edge
浏览器版本:131.0.2903.70 (正式版本) (64 位)
BewlyBewly 版本:v0.35.1

### 问题描述

新版的账号主页在开启深色模式和"适应其他页面样式"之后无法正常显示头图(纯黑) 如图:
![image](https://github.com/user-attachments/assets/19685061-e563-47a1-81d2-856227c184b5)
新版开启"适应其他页面样式"关闭深色模式:
![image](https://github.com/user-attachments/assets/20d90478-9957-4e59-befc-2ccd6c7333bb)
新版关闭"适应其他页面样式"开启深色模式:
![image](https://github.com/user-attachments/assets/34a4bf92-2387-4ae9-b077-d55d5d2d9044)
旧版开启"适应其他页面样式"开启深色模式:
![image](https://github.com/user-attachments/assets/8eb86d74-b631-4096-9334-2b7dbb3b4069)

并非每次截图都刷新页面 不确定是否存在影响 无其他影响页面显示的脚本/插件
另外建议"适应其他页面样式"添加指定页面的黑白名单功能

### 预期结果

bug修复 新版账号页在开启"适应其他页面样式"以及深色模式后可以正常显示头图

**Comment by OctoberSama** [comment]
刚刚发现浅色模式头图上面都会有一个小白条 应该也是bug

**Comment by hakadao** [comment]
沒有推送到新空間頁，改不了暫時

**Comment by Alan-CRL** [comment]
@hakadao 遇到同样问题

**Comment by Alan-CRL** [comment]
另外需要注意的是在 36.2 版本中似乎去掉了右上角栏的背景，这似乎会受头图所影响。
![msedge_rNGVUOLx6E](https://github.com/user-attachments/assets/82534d0a-d98e-4a66-afc8-2e728795e1c2)

**Comment by hakadao** [comment]
> @hakadao 遇到同样问题

你 @ 我幹甚麼我又沒close這個issue，我現在都沒有內測到新版本找我有何用
