### ISSUE TITLE
dock在深色模式下切换回浅色模式按钮背景灯光效果错位

### ISSUE THREAD

**Issue by Alan-CRL** [BewlyBewly/BewlyBewly#1166]
### 环境

BewlyBewly 36.2

### 问题描述

dock在深色模式下切换回浅色模式按钮背景灯光效果错位，浅色模式下并不会存在这个问题。

![msedge_liev8ZlGfx](https://github.com/user-attachments/assets/699b3d75-b290-43b0-a248-0c5eeaed0d6f)

**Comment by hakadao** [comment]
故意設計的
