### ISSUE TITLE
0.36.2掉帧严重

### ISSUE THREAD

**Issue by MisakaSakura** [BewlyBewly/BewlyBewly#1170]
### 环境

浏览器 (如 Chrome):Edge
浏览器版本 (如 126.0.6478.126):131.0.2903.70 
BewlyBewly 版本 (如 0.20.1):0.36.2

### 问题描述

从某个版本起，鼠标移动到导航栏就开始严重掉帧，关闭模糊效果也无济于事，目前在用的最新版也是如此

**Comment by MisakaSakura** [comment]
更新：找到原因了，是因为关闭了浏览器设置里的「在可用时使用图形加速」选项引起的；而关闭这一选项是因为电脑双屏时，如果浏览器打开这个选项，主显示器在全屏游戏，副显示器播放视频会非常卡顿，无法正常播放，临时解决办法只有关闭这个选项；不知道有无两全之法兼顾bewly和双屏使用。

**Comment by MidnightCrowing** [comment]
我想会不会是因为代码里面的 `transform-gpu` 引起的？

**Comment by hakadao** [comment]
> 更新：找到原因了，是因为关闭了浏览器设置里的「在可用时使用图形加速」选项引起的；而关闭这一选项是因为电脑双屏时，如果浏览器打开这个选项，主显示器在全屏游戏，副显示器播放视频会非常卡顿，无法正常播放，临时解决办法只有关闭这个选项；不知道有无两全之法兼顾bewly和双屏使用。

關來幹甚麼這個，瀏覽其他網頁也會想對應受影響

**Comment by hakadao** [comment]
另外說明一下我沒有那麼好的環境測試不了，也不知道怎麼改

**Comment by MidnightCrowing** [comment]
[extension.zip](https://github.com/user-attachments/files/18037422/extension.zip)

构建了一个不带 `transform-gpu` 的，试试咋样

**Comment by MisakaSakura** [comment]
> [extension.zip](https://github.com/user-attachments/files/18037422/extension.zip)
> 
> @MisakaSakura 构建了一个不带 `transform-gpu` 的，试试咋样

这个是默认关闭毛玻璃的版本吧，默认关闭确实不卡，但是打开一样卡，是不是这个毛玻璃特性一定依赖图形加速

**Comment by hakadao** [comment]
> > [extension.zip](https://github.com/user-attachments/files/18037422/extension.zip)
> 
> > 
> 
> > @MisakaSakura 构建了一个不带 `transform-gpu` 的，试试咋样
> 
> 
> 
> 这个是默认关闭毛玻璃的版本吧，默认关闭确实不卡，但是打开一样卡，是不是这个毛玻璃特性一定依赖图形加速

我是覺得正常你關圖形加速幹嘛，毛玻璃當然要用gpu加速渲染才好，爲何要同時玩遊戲+打開網頁看

**Comment by hafterain** [comment]
> 更新：找到原因了，是因为关闭了浏览器设置里的「在可用时使用图形加速」选项引起的；而关闭这一选项是因为电脑双屏时，如果浏览器打开这个选项，主显示器在全屏游戏，副显示器播放视频会非常卡顿，无法正常播放，临时解决办法只有关闭这个选项；不知道有无两全之法兼顾bewly和双屏使用。

你试一下开成“无边框窗口化”而非“全屏”。

**Comment by MisakaSakura** [comment]
> > > [extension.zip](https://github.com/user-attachments/files/18037422/extension.zip)
> > 
> > > 
> > 
> > > @MisakaSakura 构建了一个不带 `transform-gpu` 的，试试咋样
> > 
> > 
> > 
> > 这个是默认关闭毛玻璃的版本吧，默认关闭确实不卡，但是打开一样卡，是不是这个毛玻璃特性一定依赖图形加速
> 
> 我是覺得正常你關圖形加速幹嘛，毛玻璃當然要用gpu加速渲染才好，爲何要同時玩遊戲+打開網頁看

虽然我实际上没在这么用，但是我可以给你列举不少人这样做的原因：1.查视频攻略，例如原神收集材料神瞳等，不少人会跟着视频走；2.对于主播，会需要额外一个屏幕来监控直播弹幕情况，也就需要在副屏打开直播间

**Comment by hakadao** [comment]
所以配置跟不上爲何還要開毛玻璃，我到現在都不懂

bewly對毛玻璃選項分類寫得很清楚是「毛玻璃與效能」
瀏覽器毛玻璃效能改進應該向瀏覽器那邊提出，我們就負責寫個網頁渲染那些都是瀏覽器來的
