### ISSUE TITLE
【问题】扩展刷新网页时CPU占用率异常

### ISSUE THREAD

**Issue by Aarondongsq** [BewlyBewly/BewlyBewly#1171]
### 环境

浏览器 (如 Chrome): Edge
浏览器版本 (如 126.0.6478.126): 131.0.2903.86 
BewlyBewly 版本 (如 0.20.1): 0.36.2
下载来源：Chrome 应用商店

### 问题描述

刷新个B站网页，CPU占用飙到30%~50%，通过浏览器任务管理器发现是此插件导致

### 预期结果

扩展全面支持GPU渲染而不是CPU渲染

**Comment by hakadao** [comment]
https://github.com/BewlyBewly/BewlyBewly/wiki/常見問題
