### ISSUE TITLE
mac mini 搭配 4k 显示器，显示的有点错乱

### ISSUE THREAD

**Issue by hubeixulu** [BewlyBewly/BewlyBewly#1174]
### 环境

浏览器：Firefox 
浏览器版本: 132.0.2 
BewlyBewly 版本 : 0.36.2

### 问题描述

右上角的图标显示的很小，鼠标指上去显示的不全，还会错乱，左上角的图标也是这样
<img width="1919" alt="图片" src="https://github.com/user-attachments/assets/3fbacc1d-e605-46d8-bbb5-5fcbbc8851e4">
<img width="1926" alt="图片" src="https://github.com/user-attachments/assets/84f979fe-cce3-4329-b236-41bf569dbe45">

**Comment by hakadao** [comment]
f5 後是否有重現此問題？firefox 安裝完成之後會有這種不明問題出現不太清楚解決方法

**Comment by hubeixulu** [comment]
> f5 後是否有重現此問題？firefox 安裝完成之後會有這種不明問題出現不太清楚解決方法

f5 刷新过后还是有这个问题，另外一台 windows11 上同样的 firefox同样的插件版本，显示没有问题。

**Comment by hakadao** [comment]
> > f5 後是否有重現此問題？firefox 安裝完成之後會有這種不明問題出現不太清楚解決方法
> 
> f5 刷新过后还是有这个问题，另外一台 windows11 上同样的 firefox同样的插件版本，显示没有问题。

檢測刪除再重裝能否重現，這應該只是firefox瀏覽器那邊的問題

**Comment by hafterain** [comment]
> > f5 後是否有重現此問題？firefox 安裝完成之後會有這種不明問題出現不太清楚解決方法
> 
> f5 刷新过后还是有这个问题，另外一台 windows11 上同样的 firefox同样的插件版本，显示没有问题。

完全关闭 Firefox（Command + Q），然后再重新打开试试。

**Comment by hubeixulu** [comment]
> > > f5 後是否有重現此問題？firefox 安裝完成之後會有這種不明問題出現不太清楚解決方法
> > 
> > 
> > f5 刷新过后还是有这个问题，另外一台 windows11 上同样的 firefox同样的插件版本，显示没有问题。
> 
> 按住 Shift 再按刷新。
> 
> 如果还不行，完全关闭 Firefox（Command + Q），然后再重新打开。

可以了，退出浏览器在进就可以了，感谢大佬
