### ISSUE TITLE
14 寸屏幕浏览个人头像会出现两个滚动条，界面布局会抖动

### ISSUE THREAD

**Issue by jianwu003** [BewlyBewly/BewlyBewly#1177]
### 环境

浏览器: Edge
浏览器版本: 131.0.2903.86 (正式版本) (64 位)
BewlyBewly 版本: 0.37.0

### 问题描述

14 寸屏幕浏览个人头像会出现两个滚动条，界面布局会抖动

### 预期结果

优化滚动条

**Comment by jianwu003** [comment]
问题 GIF
![PixPin_2024-12-09_14-02-51](https://github.com/user-attachments/assets/a8f72149-b1b1-4234-9ad8-183f4f24bfa5)

**Comment by jianwu003** [comment]
> 你屏幕分辨率？

1080P的，其他大屏幕放大界面效果也是一样的

**Comment by hakadao** [comment]
最好提供一下熒幕解析度，不打算對太小高度適配。後續若無提供和其他回應將直接關閉
https://guanjia.qq.com/knowledge-base/content/1286
