### ISSUE TITLE
UP投稿图文页显示错位

### ISSUE THREAD

**Issue by cns1rius** [BewlyBewly/BewlyBewly#1179]
### 环境

浏览器: Edge
浏览器版本: 131.0.2903.86
BewlyBewly 版本: 0.37.0

### 问题描述

UP主主页 投稿图文页面 显示错位,暗黑和明亮都错位，而且暗黑模式字体颜色也不对
[投稿图文页面](https://space.bilibili.com/360996402/upload/opus)
![image](https://github.com/user-attachments/assets/8020e611-0797-419a-a183-fcf9e7b3cc6c)
![image](https://github.com/user-attachments/assets/39a93ce6-217e-4dcf-8d60-7d139e89c17f)

**Comment by hafterain** [comment]
目前沒被灰度到新界面，沒法修暫時

**Comment by hakadao** [comment]
#1155
