### ISSUE TITLE
左上角切换Tab卡住并且无法点击

### ISSUE THREAD

**Issue by zhougx9981** [BewlyBewly/BewlyBewly#1186]
### 环境

浏览器 : Edge，Chrome均存在
浏览器版本 : 131.XXX
BewlyBewly 版本 : 从一开始使用BewlyBewly就有这个Bug，以为很快修好了就没提issue。

### 问题描述

切换Tab会出现，卡在上面并且无法点击的情况

https://github.com/user-attachments/assets/8200f080-0a8d-43d7-95da-185c90e989e1

### 预期结果

预期可以正确点击

**Comment by zhougx9981** [comment]
还有一个问题就是感觉收藏的字体比较模糊，但是其它不存在模糊。
截图可能看不出来，肉眼比较明显。

不知道这两个问题是否都是由高分屏引起。
![image](https://github.com/user-attachments/assets/93bdb07d-025d-4ff2-bd9c-d8a8573b5379)
![image](https://github.com/user-attachments/assets/cff89dbc-281c-4eba-9fe1-8b5eb8b3801b)

**Comment by hafterain** [comment]
> 切换Tab会出现，卡在上面并且无法点击的情况

已在一个干净的 Chromium 131.0.6778.85 中测试，没有发现问题。

请检查你的其他插件或 JS 脚本。

https://github.com/user-attachments/assets/a6d1d258-1d27-402d-878d-c97a04658403

**Comment by MidnightCrowing** [comment]
> > 切换Tab会出现，卡在上面并且无法点击的情况
> 
> 已在一个干净的 Chromium 131.0.6778.85 中测试，没有发现问题。
> 
> 请检查你的其他插件或 JS 脚本。
> 
>  Jietu20241212-105248-HD.mp4

我这边测试可以复现，要把设置里面`自动隐藏顶栏`选项打开：
![image](https://github.com/user-attachments/assets/aacb36c6-00b3-4102-9a9f-5ec4965d176a)
而且这个问题只有在从`排行`切换到其他标签时会才出现

**Comment by zhougx9981** [comment]
是的，我也开启了自动隐藏顶栏

**Comment by zhougx9981** [comment]
> > > 切换Tab会出现，卡在上面并且无法点击的情况
> > 
> > 
> > 已在一个干净的 Chromium 131.0.6778.85 中测试，没有发现问题。
> > 请检查你的其他插件或 JS 脚本。
> > Jietu20241212-105248-HD.mp4
> 
> 我这边测试可以复现，要把设置里面`自动隐藏顶栏`选项打开： ![image](https://private-user-images.githubusercontent.com/110297461/395236391-aacb36c6-00b3-4102-9a9f-5ec4965d176a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMjA3MzcsIm5iZiI6MTczNDAyMDQzNywicGF0aCI6Ii8xMTAyOTc0NjEvMzk1MjM2MzkxLWFhY2IzNmM2LTAwYjMtNDEwMi05YTlmLTVlYzQ5NjVkMTc2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMlQxNjIwMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2Y5YmY5MzI0ODA2OTVkNGU0MjRjY2FkYTUzYzM4NGZkODM5YjQ3ZDk1MDAyMDUxZWYxMGJjNGU0YzFhMDMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.S2iTr8xtOFhmaLjcaNbLd_5MlPJYLSsSTQAv_KYv39k) 而且这个问题只有在从`排行`切换到其他标签时才会出现

是的，我也开起了自动隐藏。

**Comment by hakadao** [comment]
> 从一开始使用BewlyBewly就有这个Bug，以为很快修好了就没提issue。

我又不能完全測試到你們是開了甚麼設定下做出甚麼操作產生這個bug的，真服了還要刻意強調

**Comment by zhougx9981** [comment]
> > 从一开始使用BewlyBewly就有这个Bug，以为很快修好了就没提issue。
> 
> 我又不能完全測試到你們是開了甚麼設定下做出甚麼操作產生這個bug的，真服了還要刻意強調

不好意思，我的表述可能有些不恰当，让您感到不舒服。

这不是我的本意，我只是想说明这个问题已经存在一段时间，并非急于求解。非常感谢您愿意花时间查看这个问题。
