### ISSUE TITLE
顶栏的投稿按钮一直处于激活状态

### ISSUE THREAD

**Issue by thissensen** [BewlyBewly/BewlyBewly#1187]
### 环境

浏览器 (如 Chrome):Cent Browser 版本 5.1.1130.129（正式版本） （64 位）
浏览器版本 (如 126.0.6478.126):Chromium 118.0.5993.159
BewlyBewly 版本 (如 0.20.1):v0.37.1

### 问题描述

旧版顶栏有一圈蓝色光圈，新版也有，疑似一直处于激活状态
![QQ截图20241212214800](https://github.com/user-attachments/assets/3a672288-7d58-4bc4-beaf-8c8b73186314)
![QQ截图20241212215033](https://github.com/user-attachments/assets/7b0d4c96-5419-4bde-9dda-37a5195b9f9b)

**Comment by hakadao** [comment]
故意設計的這裏其實

**Comment by thissensen** [comment]
> 故意设计的这个事实

就是新版顶栏这个蓝色太突兀了，左右灰色就他蓝色，希望可以统一风格
