### ISSUE TITLE
首页无法使用浮图秀插件？

### ISSUE THREAD

**Issue by SerendipityOne** [BewlyBewly/BewlyBewly#1196]
### 环境信息

- 浏览器（如 Google Chrome）：edge
- 浏览器版本（如 126.0.6478.126）：131.0.2903.99
- BewlyBewly 版本（如 0.20.1）：最新

如果你修改了 BewlyBewly 的设置，请写在下面：

### 问题描述

我发现在首页无法使用浮图秀插件，而原版是能使用的

### 最终确认

- [X] 我确认此问题未在其他 issue 中出现过。
- [X] 我确认我已阅读“[常見問題](https://github.com/BewlyBewly/BewlyBewly/wiki/%E5%B8%B8%E8%A6%8B%E5%95%8F%E9%A1%8C)”页面，其中没有对应我问题的解决方案。
- [X] 我确认我正在使用最新的 BewlyBewly 版本。
- [X] 我确认我做出的任何自定义设置（如果有）已经写明。

**Comment by hafterain** [comment]
重复 #788、#1085。

若需和其他插件一起使用，建议开启“使用原版 Bilibili 首页”。

**Comment by hakadao** [comment]
![image](https://github.com/user-attachments/assets/e1c74642-455d-4461-8709-233bec1d33fe)
可以嘗試使用b站原版頁面
