### ISSUE TITLE
评论区图片放大后无法正常关闭

### ISSUE THREAD

**Issue by JackieCYX** [BewlyBewly/BewlyBewly#1199]
### 环境信息

- 浏览器（Google Chrome）：
- 浏览器版本（131.0.6778.140）：
- BewlyBewly 版本（0.38.1）：

如果你修改了 BewlyBewly 的设置，请写在下面：

### 问题描述

使用插件自带的动态查看UP主动态评论区图片时，点击放大后图层显示异常，无法正常关闭

### 预期行为

可以点击右上角关闭

### 最终确认

- [X] 我确认此问题未在其他 issue 中出现过。
- [X] 我确认我已阅读“[常見問題](https://github.com/BewlyBewly/BewlyBewly/wiki/%E5%B8%B8%E8%A6%8B%E5%95%8F%E9%A1%8C)”页面，其中没有对应我问题的解决方案。
- [X] 我确认我正在使用最新的 BewlyBewly 版本。
- [X] 我确认我做出的任何自定义设置（如果有）已经写明。

**Comment by hakadao** [comment]
能點
![image](https://github.com/user-attachments/assets/91b85215-ea95-4e47-a4ab-73e0b17fc354)
