### ISSUE TITLE
【BUG】大会员页大会员卡片错位

### ISSUE THREAD

**Issue by Aarondongsq** [BewlyBewly/BewlyBewly#1200]
### 环境信息

- 浏览器（如 Google Chrome）：Microsoft Edge
- 浏览器版本（如 126.0.6478.126）：131.0.2903.112 (正式版本) (64 位)
- BewlyBewly 版本（如 0.20.1）：0.38.2

如果你修改了 BewlyBewly 的设置，请写在下面：

### 问题描述

重现：
1. 打开 bilibili 首页
2. 头像选择“我的大会员”
3. 大会员卡片出现错位
  ![397929313-e610298f-74e9-4ed6-85ac-4864e1939cd3](https://github.com/user-attachments/assets/3b8fedc9-b125-482f-8e77-287109a4687e)

### 最终确认

- [X] 我确认此问题未在其他 issue 中出现过。
- [X] 我确认我已阅读“[常見問題](https://github.com/BewlyBewly/BewlyBewly/wiki/%E5%B8%B8%E8%A6%8B%E5%95%8F%E9%A1%8C)”页面，其中没有对应我问题的解决方案。
- [X] 我确认我正在使用最新的 BewlyBewly 版本。
- [X] 我确认我做出的任何自定义设置（如果有）已经写明。

**Comment by hafterain** [comment]
你好，烦请不要修改 issue 模板，也不要加入任何附带的神秘词汇，这不会让你“显得很可爱”“看起来更友好”，只会降低整理问题的效率。
