### ISSUE TITLE
[Feature] 直播页可选仅展示正在直播的UP

### ISSUE THREAD

**Issue by BennettChina** [BewlyBewly/BewlyBewly#1203]
如题，首页的直播栏目下面 UP 目前是展示的历史记录和当前正在直播的 UP ，我希望可以增加仅展示正在直播的 UP ，而不是现在的混合一起然后加一个正在直播的标记，这种对我来说还是不够清晰明了。

**Comment by hakadao** [comment]
我是打算分開展示，後面改成上面顯示正在直播的 up，下面顯示推介

**Comment by BennettChina** [comment]
也可以，有点类似 App 上的那种形式。

**Comment by hakadao** [comment]
下版本直接放「關注」那邊了把直播，直播那邊就暫時先不該了
![image](https://github.com/user-attachments/assets/b4969551-bff9-46ce-a042-d57c14f3b6fc)
