### ISSUE TITLE
【功能请求&问题】是否考虑重新修改主页的哔哩哔哩无网页版？

### ISSUE THREAD

**Issue by Aarondongsq** [BewlyBewly/BewlyBewly#1205]
现在我看这个插件主页在动态页上默认是网页版，而没法关闭，希望添加一个不用网页版的动态页
效果如下：
![398026174-d76c2d45-3db2-4fdf-b1c4-7cdbc394a38f](https://github.com/user-attachments/assets/707d3fcf-78eb-4bae-8d89-d2fb23d9392e)

**Comment by hakadao** [comment]
沒有太多時間，後續考慮
