### ISSUE TITLE
重启浏览器会导致所有设定初始化

### ISSUE THREAD

**Issue by gsxgmpkt9020** [BewlyBewly/BewlyBewly#1208]
### 环境信息

- 浏览器 Google Chrome ：
- 浏览器版本  Version 131.0.6778.205 (Official Build) (64-bit)：
- BewlyBewly 版本 v0.38.4（问题几天前就有了）

如果你修改了 BewlyBewly 的设置，请写在下面（这将方便我们排查问题，可粗略写成类似“设置了 ○○○○ 后出现这个问题”〔将“○○○○”替换为你的设置项〕）：

全是默认设置，包括语言也是系统的英文

### 问题描述

重启浏览器会导致所有BewlyBewly设定强行初始化。
E:\CACHE\to_drop\C1\User\Default\Local Extension Settings\bbbiejemhfihiooipfcjmjmbfdmobobp
![image](https://github.com/user-attachments/assets/2aed9e7a-1e7d-416d-8a46-f3a0357ea72a)

```
2024/12/24-09:53:21.630 c2c Creating DB E:\CACHE\to_drop\C1\User\Default\Local Extension Settings\bbbiejemhfihiooipfcjmjmbfdmobobp since it was missing.
2024/12/24-09:53:22.489 c2c Reusing MANIFEST E:\CACHE\to_drop\C1\User\Default\Local Extension Settings\bbbiejemhfihiooipfcjmjmbfdmobobp/MANIFEST-000001
2024/12/24-09:53:22.490 c2c Recovering log #3
2024/12/24-09:53:22.594 c2c Reusing old log E:\CACHE\to_drop\C1\User\Default\Local Extension Settings\bbbiejemhfihiooipfcjmjmbfdmobobp/000003.log 
```

.log里也有乱码
[000003.log](https://github.com/user-attachments/files/18235017/000003.log)

MANIFEST-000001乱码：
晐古" leveldb.BytewiseComparator  

可能ldb数据库都没建

### 预期行为

重启浏览器读取设置文件（或数据库）中的设置

### 最终确认

- [X] 我确认此问题未在其他 issue 中出现过。
- [X] 我确认我已阅读“[常見問題](https://github.com/BewlyBewly/BewlyBewly/wiki/%E5%B8%B8%E8%A6%8B%E5%95%8F%E9%A1%8C)”页面，其中没有对应我问题的解决方案。
- [X] 我确认我正在使用最新的 BewlyBewly 版本。

### 作出贡献？

- [ ] 我将自行提交一个 PR 来解决此问题。

**Comment by hakadao** [comment]
不知道你是否有用過電腦清理軟件，可能它們連同瀏覽器緩存刪了

**Comment by hakadao** [comment]
> > 不知道你是否有用過電腦清理軟件，可能它們連同瀏覽器緩存刪了
> 
> 完全没用过。你能告诉我这个扩展的设置文件的建立、储存和读取方式吗？MANIFEST-000001在这里起得是什么作用？

這部分真不是我處理的，應該是瀏覽器的處理，瀏覽器設定那邊是否啓用了類似自動清理cache那些
