### ISSUE TITLE
[功能请求]加入可选的OverrideConfig.ini的配置文件

### ISSUE THREAD

**Issue by pein0saga** [BewlyBewly/BewlyBewly#1214]
### 环境信息

浏览器 Google Chrome ：
浏览器版本 Version 131.0.6778.205 (Official Build) (64-bit)：
BewlyBewly 版本 v0.38.4

### 问题描述

加入可选的自己编写的OverrideConfig.ini的配置文件以保证设置不会被各种因素重置、初始化，

扩展配置文件夹下没有OverrideConfig.ini文件则一切照常，如果有的话以最高优先级加载设定数据

https://github.com/BewlyBewly/BewlyBewly/issues/1208

格式直接沿用下面的就行

`{\"touchScreenOptimization\":false,\"enableGridLayoutSwitcher\":true,\"enableHorizontalScrolling\":false,\"language\":\"cmn-CN\",\"customizeFont\":false,\"fontFamily\":\"-apple-system, BlinkMacSystemFont, Inter, \\\"Segoe UI Variable\\\", \\\"Segoe UI\\\", \\\"Roboto Flex\\\", Roboto, \\\"Noto Sans\\\", Oxygen, Ubuntu, Cantarell, \\\"Open Sans\\\", \\\"Helvetica Neue\\\", Arial, sans-serif\",\"overrideDanmakuFont\":true,\"removeTheIndentFromChinesePunctuation\":false,\"disableFrostedGlass\":false,\"reduceFrostedGlassBlur\":false,\"videoCardLinkOpenMode\":\"newTab\",\"topBarLinkOpenMode\":\"currentTabIfNotHomepage\",\"searchBarLinkOpenMode\":\"currentTabIfNotHomepage\",\"closeDrawerWithoutPressingEscAgain\":false,\"blockAds\":true,\"blockTopSearchPageAds\":false,\"enableVideoPreview\":true,\"enableVideoCtrlBarOnVideoCard\":false,\"hoverVideoCardDelayed\":false,\"useOldTopBar\":false,\"autoHideTopBar\":false,\"topBarIco`

### 最终确认

- [X] 我确认此问题未在其他 issue 中出现过。
- [X] 我确认我已阅读“[常見問題](https://github.com/BewlyBewly/BewlyBewly/wiki/%E5%B8%B8%E8%A6%8B%E5%95%8F%E9%A1%8C)”页面，其中没有对应我问题的解决方案。
- [X] 我确认我正在使用最新的 BewlyBewly 版本。

### 作出贡献？

- [ ] 我将自行提交一个 PR 来解决此问题。

**Comment by hakadao** [comment]
匯入匯出設定那裏的格式才是bewlybewly接受的格式，這部份是瀏覽器處理的我怎麼弄呀💀
