### ISSUE TITLE
能不能添加一个选项来隐藏 正在关注 里的直播 

### ISSUE THREAD

**Issue by Eff0rtly** [BewlyBewly/BewlyBewly#1215]
能不能添加一个选项来隐藏 正在关注 里的直播 
毕竟 关注的直播 已经出现在 直播 选项中 何必多次一举
![图片](https://github.com/user-attachments/assets/8cf49ed8-ab8a-4ca8-a127-6b3dfc13798c)

**Comment by hafterain** [comment]
![image](https://github.com/user-attachments/assets/4f89db48-5ec9-44e1-826d-5d70bc0474a7)

此選項已於近期加入，煩請使用最新版的 BewlyBewly。

**Comment by hakadao** [comment]
在bewlybewly頁面->首頁然後拉下一點就可以看到
