### ISSUE TITLE
模态（设置）弹窗可以用Tab切换到外面的东西

### ISSUE THREAD

**Issue by kzyqq00-Player** [BewlyBewly/BewlyBewly#1222]
**如果设置弹窗预期应该是非模态的（不应该吧），请close此issue**

- 浏览器：Edge
- 浏览器版本：131.0.2903.112
- BewlyBewly 版本：0.38.5

在打开设置框的时候应该是一个模态框，不可以Tab到外面的东西，而我Tab到了：
<img src="https://github.com/user-attachments/assets/293e0da7-3097-4678-8139-cc70b140a85d" alt="截图" height="300px" />
这可能算一个bug？虽然我没有把这个issue投成bug...

**Comment by hakadao** [comment]
。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。
