### ISSUE TITLE
百分浏览器扩展提示错误

### ISSUE THREAD

**Issue by fifaplayer88** [BewlyBewly/BewlyBewly#1224]
### 环境信息

- 浏览器（百分浏览器）：
- 浏览器版本（5.1.1130.129）：
- BewlyBewly 版本（BewlyBewly 0.38.5）：

### 问题描述

百分浏览器扩展提示错误

### 预期行为

![屏幕截图 2024-12-28 134027](https://github.com/user-attachments/assets/c2c87569-1d38-4eb7-8c56-0dbf8f80001c)
![屏幕截图(8)](https://github.com/user-attachments/assets/83cd9789-9a8f-4ea5-8d05-de770db508e2)

### 最终确认

- [X] 我确认此问题未在其他 issue 中出现过。
- [X] 我确认我已阅读“[常見問題](https://github.com/BewlyBewly/BewlyBewly/wiki/%E5%B8%B8%E8%A6%8B%E5%95%8F%E9%A1%8C)”页面，其中没有对应我问题的解决方案。
- [X] 我确认我正在使用最新的 BewlyBewly 版本。

### 作出贡献？

- [ ] 我将自行提交一个 PR 来解决此问题。

**Comment by hafterain** [comment]
Cent Browser 可以通过 Chrome Web Store 安装，请使用此安装方式。

若你实在需要通过“开发者模式”加载，请解压并加载名为“extension.zip”的扩展，**请勿使用“extension-firefox.zip”**。

**通过后者安装的扩展无法自动更新，请尽可能通过 Chrome Web Store 安装。**

![image](https://github.com/user-attachments/assets/c5ad8f67-ace4-4aec-8f2a-63d8b577c211)

**Comment by fifaplayer88** [comment]
> Cent Browser 可以通过 Chrome Web Store 安装，请使用此安装方式
你好  我用的就是extension.zip 这个文件，但是用开发者模式安装以后 打开B站就出现我说的错误的选项，但是用chrome web安装就正常 以上
