### ISSUE TITLE
评论区点击图片，点击关闭无法正常关闭

### ISSUE THREAD

**Issue by JackieCYX** [BewlyBewly/BewlyBewly#1228]
### 环境信息

- 浏览器（Google Chrome）：
- 浏览器版本（131.0.6778.205）：
- BewlyBewly 版本（0.39.1）：

如果你修改了 BewlyBewly 的设置，请写在下面以方便我們排查問題（可粗略写成类似“设置了○○○○后出现这个问题”〔将“○○○○”替换为你的设置项〕）：

### 问题描述

评论区点击图片，点击关闭无法正常关闭，这里操作的时候我疯狂点击右上角的X，但是就是不能正常关闭

https://github.com/user-attachments/assets/e93d7e39-f7e9-4b0f-bd49-8c6b3f5418a1

### 预期行为

图片关闭

### 最终确认

- [X] 我确认此问题未在其他 issue 中出现过。
- [X] 我确认我已阅读“[常見問題](https://github.com/BewlyBewly/BewlyBewly/wiki/%E5%B8%B8%E8%A6%8B%E5%95%8F%E9%A1%8C)”页面，其中没有对应我问题的解决方案。
- [X] 我确认我正在使用最新的 BewlyBewly 版本。

### 作出贡献？

- [ ] 我将自行提交一个 PR 来解决此问题。

**Comment by hakadao** [comment]
請你先聽聽你重現的方式再想想畫面
![image](https://github.com/user-attachments/assets/028dcd6b-a647-4353-b982-4fd8d20e84c8)

**Comment by hakadao** [comment]
另外重複，這裏無法重現，是否有與其他擴充功能或腳本共用所導致
https://github.com/BewlyBewly/BewlyBewly/issues/1199#issuecomment-2558088779
