### ISSUE TITLE
关不掉首页标签栏，一直存在

### ISSUE THREAD

**Issue by jokers3858** [BewlyBewly/BewlyBewly#1231]
### 环境信息

- 浏览器（如 Google Chrome）：edge
- 浏览器版本（如 126.0.6478.126）：131.0.2903.112 (正式版本) (64 位)
- BewlyBewly 版本（如 0.20.1）：0.39.1

如果你修改了 BewlyBewly 的设置，请写在下面以方便我們排查問題（可粗略写成类似“设置了○○○○后出现这个问题”〔将“○○○○”替换为你的设置项〕）：

### 问题描述

关掉了 “总是显示首页标签栏” 后标签栏还是关不掉，一直存在
![屏幕截图 2024-12-30 180009](https://github.com/user-attachments/assets/da13ed36-4627-4d7e-8704-ffda050a7ecc)
![屏幕截图 2024-12-30 180041](https://github.com/user-attachments/assets/014b68ad-5e2a-4631-a5ba-f347c0d59e45)

### 预期行为

修复一下，关掉之后标签栏不应该一直存在

### 最终确认

- [X] 我确认此问题未在其他 issue 中出现过。
- [X] 我确认我已阅读“[常見問題](https://github.com/BewlyBewly/BewlyBewly/wiki/%E5%B8%B8%E8%A6%8B%E5%95%8F%E9%A1%8C)”页面，其中没有对应我问题的解决方案。
- [X] 我确认我正在使用最新的 BewlyBewly 版本。

### 作出贡献？

- [ ] 我将自行提交一个 PR 来解决此问题。

**Comment by hakadao** [comment]
它其實的意思是只保留一個標籤時會隱藏
