### ISSUE TITLE
[整合 bilibili-simple-home] Incorporate serval features from `bilibili-simple-home`

### ISSUE THREAD

**Issue by hakadao** [BewlyBewly/BewlyBewly#14]
https://github.com/hakadao/bilibili-simple-home

**Comment by hakadao** [comment]
已經實現
- 背景設定和遮蔽效果+毛玻璃背景

打算實現？
- 搜尋頁樣式調整
- 聚焦輸入框時顯示22或33娘？

**Comment by hakadao** [comment]
已實現
- 是否显示 LOGO
- LOGO 发光效果
- 选择主题色
- 选择背景
- 设置背景遮罩
- 搜索条聚焦后显示人物
- 搜索条聚焦后暗化效果

無法實現
- 搜索条聚焦后毛玻璃效­果（試過實現毛玻璃效果會失敗）

不打算實現
- 首页样式（可能只會單純調整搜尋欄和logo擺放位置）
- 顶栏设计效果
- 分区弹出层显示22娘
- 滑动视频放大效果

考慮實現？
- 背景依附方式

**Comment by flashorsink** [comment]
一点建议：希望实现主页开屏自动进入搜索页和首页的选择，以及搜索页下滚衔接首页的推荐视频。动态如果能做成类似收藏的右侧选项卡片就更好了。

**Comment by hakadao** [comment]
> 一点建议：希望实现主页开屏自动进入搜索页和首页的选择，以及搜索页下滚衔接首页的推荐视频。动态如果能做成类似收藏的右侧选项卡片就更好了。

1. 我是想加個功能是提供選擇預設啓動頁
2. 首頁加個功能使用搜尋頁效果
3. 動態頁面沒時間做，日後會專門做一個動態頁，b站網頁版的動態頁面不怎麼好調

**Comment by hakadao** [comment]
> 一点建议：希望实现主页开屏自动进入搜索页和首页的选择，以及搜索页下滚衔接首页的推荐视频。动态如果能做成类似收藏的右侧选项卡片就更好了。

第一条 v0.8.0 已经实现

**Comment by misaka10384** [comment]
大佬加油  我也想要动态首页  打开默认搜索页 支持鼠标滚轮下滑切换到首页推荐视频

**Comment by hakadao** [comment]
> 大佬加油 我也想要动态首页 打开默认搜索页 支持鼠标滚轮下滑切换到首页推荐视频

這段時間能不能再出個新版本我也很難説

**Comment by xiaowang-code** [comment]
我需要背景图是必应每日壁纸，https://cn.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=zh-C这是获取url连接，奈何下载到本地后run不起来，特求你添加此功能
