### ISSUE TITLE
[FR] 主页增加屏蔽视频所对应的 up 的按钮

### ISSUE THREAD

**Issue by F-park** [BewlyBewly/BewlyBewly#163]
### 新功能描述

由于插件改变了B站的界面，导致我使用的屏蔽 up 主的油猴脚本不能生效，希望插件可以实现类似的功能。

---

然后视频预览的触发也可以改成和原先的一致，只在红框内才触发预览，而不是在进入遮罩卡片就触发视频预览（误触率太高了）。

![image](https://github.com/hakadao/BewlyBewly/assets/52167622/6c0c4934-8dbb-4f6c-bbd4-27d6631202bf)

### 按钮位置建议

1. [直播插件](https://greasyfork.org/zh-CN/scripts/449261-%E7%9B%B4%E6%92%AD%E6%8F%92%E4%BB%B6/)，我现在在使用的，我觉得可以将屏蔽按钮放到右下角（只有划到下面空白处才显示）。

![image](https://github.com/hakadao/BewlyBewly/assets/52167622/fc4605fd-667f-4c1d-a20e-dd408f9a85cd)

2.  [B站用户屏蔽](https://greasyfork.org/zh-CN/scripts/465675-b%E7%AB%99%E7%94%A8%E6%88%B7%E5%B1%8F%E8%94%BD/)，在视频封面左上角放置屏蔽按钮，但屏蔽之前必定会触发视频预览，我觉得这种方案不是很好。

![image](https://github.com/hakadao/BewlyBewly/assets/52167622/2cbbb38c-f8d5-49aa-b29a-f12664cbdd08)

**Comment by hakadao** [comment]
1. 视频预览的触发這個可以改並且下版本有個選擇是否延遲預覽效果
2. 插件適配那些之後説吧，你可以用會原版的b站首頁
<img width="979" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/33394391/6aa91120-1a82-4510-ac90-de70a9c25ef9">
3. 後期頂欄會考慮點擊裏面的內容彈出右滑窗顯示bewlybewly頁面

**Comment by hakadao** [comment]
目前就兩個，後續添加更多
<img width="1020" alt="image" src="https://github.com/BewlyBewly/BewlyBewly/assets/33394391/a4006d72-41da-4dc3-9f45-20511b51a880">
