### ISSUE TITLE
【建议】我就觉得可以把这个 上划刷新也做到右侧的工具栏里，

### ISSUE THREAD

**Issue by yrui-ql** [BewlyBewly/BewlyBewly#220]
![image](https://github.com/hakadao/BewlyBewly/assets/19502359/5131c0dd-646e-42a4-89b5-9c7b27af96d9)

当前的操作手感是，一会挪到右侧，一会挪到下面点刷新，很奇怪的操作。
不过有一说一，这个界面配合我的网页暗黑主题，舒服多了，赞！

**Comment by hakadao** [comment]
加個開關以後

**Comment by hakadao** [comment]
其實你點擊dock項就可以實現返回頂部和刷新功能，那個按鈕只是給不知道這個特性的人用的

**Comment by hakadao** [comment]
考慮了一下好像也沒有必要吧，反正再點一次icon也能刷新就不放了
