### ISSUE TITLE
动态内容的文字字号貌似偏小

### ISSUE THREAD

**Issue by hyoban** [BewlyBewly/BewlyBewly#365]
![ScreenShot 2024-03-06 12 00 44](https://github.com/hakadao/BewlyBewly/assets/38493346/2879454a-b321-4b46-992d-cb0f72604917)

对比原版

![ScreenShot 2024-03-06 12 02 27](https://github.com/hakadao/BewlyBewly/assets/38493346/500ddbb7-6cdb-4524-a127-4bc23e381e4c)

**Comment by hakadao** [comment]
因爲我在 src/styles/main.scss 改了 html 標籤內的文字大小, 之前 unocss 的那些屬性 p-2, m-2, w-2 都是按照 rem 爲基礎來的, 當時沒想那麼多直接設定死 html 文字是 14px, 估計這個原因導致動態那邊文字字號變小

這個要改的話可能考慮以後做一個 iframe 再注入到裏面了, 我想不到其他解決方法
