### ISSUE TITLE
建议: 首页推荐的过滤功能

### ISSUE THREAD

**Issue by cliouo** [BewlyBewly/BewlyBewly#417]
### 使用pilipala很喜欢推荐过滤功能，不知道可不可以在设置里添加类似的过滤选项，例如:
1. **点赞率过滤**
个人习惯过滤掉点赞率2%以下的视频。
2. **视频时长过滤**
看B站嘛就不想看30秒以下的视频。
4. **屏蔽用户黑名单内UP的视频**
因为我看有人提屏蔽UP主，这样用户自己去拉B站黑名单，插件这边去过滤掉黑名单就好了。

**很喜欢这个插件，不管怎么样都很感谢您的工作。**
pilipala截图↓
![filter](https://github.com/hakadao/BewlyBewly/assets/71540889/fa42098b-3a86-47fa-80b5-db7a872943fa)

**Comment by GitHubSancho** [comment]
复议！

**Comment by xfrqh** [comment]
![2024-06-27_14-07-05](https://github.com/BewlyBewly/BewlyBewly/assets/73733485/82153ac6-6b6c-4257-a5a0-46148ec4bead)

也可以像[bilibili-app-recommend][recommend]那样按**播放量**过滤

[recommend]:https://greasyfork.org/zh-CN/scripts/443530-bilibili-app-recommend

**Comment by hakadao** [comment]
目前就兩個，後續添加更多
<img width="1020" alt="image" src="https://github.com/BewlyBewly/BewlyBewly/assets/33394391/db1854a7-e8f0-45c2-970f-127f06f3ffed">
