### ISSUE TITLE
右侧Dock 栏与右上角顶栏菜单

### ISSUE THREAD

**Issue by shaoyouvip** [BewlyBewly/BewlyBewly#426]
右侧Dock 栏与右上角顶栏菜单 所打开的稍后观看不一样一个是您开发者改的版本 一个是官方他的版本 点进去，希望能统一为开发者您所改的版本。

**Comment by hakadao** [comment]
可以，之后打算做成浮窗形式打开bewly的页面，官方的再单独开个tab

**Comment by hakadao** [comment]
下版本可以配置
![image](https://github.com/user-attachments/assets/aa037267-38d6-4d01-94db-3a862d34ed09)
