### ISSUE TITLE
在鼠标悬停在头像上时添加当前经验条显示

### ISSUE THREAD

**Issue by lszghcpp** [BewlyBewly/BewlyBewly#503]
在鼠标悬停在头像上时添加当前经验条显示

**Comment by hakadao** [comment]
把問題在標題裏說清楚，你寫todo我也不知道todo甚麼

**Comment by CreeperAWA** [comment]
我猜意思是主頁的頭像滑鼠懸浮在上面顯示經驗條，我也想要這個doge

**Comment by lszghcpp** [comment]
> 把問題在標題裏說清楚，你寫todo我也不知道todo甚麼

在任何页面下，将鼠标悬停在头像上，添加经验条显示belike:
![image](https://github.com/BewlyBewly/BewlyBewly/assets/158157016/e2a2bdbe-ef66-4fb3-b8bb-413b430d4c4c)
