### ISSUE TITLE
关于顶栏UI的一些建议

### ISSUE THREAD

**Issue by pasical** [BewlyBewly/BewlyBewly#549]
### 我觉得顶栏在网页中应该是一个一体化的存在，目前的ui显得太割裂了。
首先是目前采用了悬浮的设计，这一点没有什么问题，但是它把顶栏ui分成了3部分：logo，搜索框和功能键区，同时这三个部分长度不一，中间有较大空缺，这样会导致在视觉上的不连贯，从而影响下方网页的浏览体验。
![image](https://github.com/hakadao/BewlyBewly/assets/112304778/e7c6d3e2-ff2b-4074-b072-ceb045065dcb)

#### 在动态页，本身顶栏的底部应与下方元素平行，而分开的顶栏没有做到这一点。
![image](https://github.com/hakadao/BewlyBewly/assets/112304778/cd23557e-477b-4cbf-a8f8-0ed38db42c22)

#### 在首页也有体现，各部分之间的空缺导致一些控件的排列看起来很随意。
![image](https://github.com/hakadao/BewlyBewly/assets/112304778/e2764540-a5c6-4a6f-a59d-21f4a8d4e270)

Google m3设计官网的“顶栏”是悬浮一体的
![image](https://github.com/hakadao/BewlyBewly/assets/112304778/911ab537-f017-4807-a157-3176c248df27)

一个UI设计灵感网站，顶栏设计紧凑
![image](https://github.com/hakadao/BewlyBewly/assets/112304778/d9e8171b-c92f-419a-a11c-93a9291c03f8)

另一个UI设计参考网站，和BewlyBewly采用类似的遮罩，但是元素较为一体
![image](https://github.com/hakadao/BewlyBewly/assets/112304778/d35438a1-6742-4efe-b3e8-b56ff721449f)

### a. 去除顶栏三个部分的阴影，取消背景遮罩，让它和顶部空白融为一体。 
有点像GitHub的设计
### b. 把整个顶栏连成一体，缩减三个部分间的空隙。（到时候可能会有一个巨长无比的搜索框？）
![image](https://github.com/hakadao/BewlyBewly/assets/112304778/83a4049f-3eb3-4d73-8500-8662e44f79d7)
↑这样看起来好不少，当然也可以试图把dock栏加到空白处
![image](https://github.com/hakadao/BewlyBewly/assets/112304778/384a5e17-6a21-4f61-a66c-ae574ab3e714)
↑自己改了一下，还有细节没调好。搜索框确实太大了，虽然排版美观了，感觉可以加一些控件
### c. 始终显示顶栏背景，同时采用透明度更低的材质，颜色和页面背景要有一定差异，阴影之类的收敛一点
类似于win11任务栏
<img width="1280" alt="PixPin_2024-04-13_14-42-40" src="https://github.com/hakadao/BewlyBewly/assets/112304778/fe063b92-7b13-4534-8329-985f98f54615">
我自改了一下，显然效果没有达到我自己的要求
<img width="1278" alt="PixPin_2024-04-13_14-31-59" src="https://github.com/hakadao/BewlyBewly/assets/112304778/7315606c-81e2-4735-949a-f70a64aee997">

**Comment by hakadao** [comment]
目前感觉不管是加长搜索条或不用悬浮效果都感觉效果不是特别好，不过十分感谢你提出了一个设计上的建议
能否有其他你认为不错的顶栏设计，可为后续ui更新作参考和调整？

**Comment by pasical** [comment]
感谢你的答复，如果我找到好的设计我会继续分享😉

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by caycy01** [comment]
![image](https://github.com/hakadao/BewlyBewly/assets/98204496/0329877b-0937-4671-9f6e-8ff9aaa2cae0)
这一块可以塞bilibili logo里 在显示宽度足够的时候自动展开 或者是往下滑自动隐藏

我说说我为什么要提这个 因为在我的显示器上这个东西完全可以放在顶栏上面 而且又和哔哩哔哩的logo错位 这让我个人看的很难受（个人感受不代表所有人）

**Comment by pasical** [comment]
两个概念网站：
![image](https://github.com/hakadao/BewlyBewly/assets/112304778/7c375d36-a4d4-4da5-8a4e-e0ba4c98ff94)
![image](https://github.com/hakadao/BewlyBewly/assets/112304778/fae7137b-1b73-402c-ae96-872080fc8344)
https://whimsical.com/?ref=pixelfika
https://www.cosmos.so/

**Comment by hakadao** [comment]
> 两个概念网站： ![image](https://private-user-images.githubusercontent.com/112304778/322212328-7c375d36-a4d4-4da5-8a4e-e0ba4c98ff94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMTk3NDgsIm5iZiI6MTcxMzAxOTQ0OCwicGF0aCI6Ii8xMTIzMDQ3NzgvMzIyMjEyMzI4LTdjMzc1ZDM2LWE0ZDQtNGRhNS04YTRlLWUwYmE0Yzk4ZmY5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxM1QxNDQ0MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NWU4NGQ1ZTQzZTA1M2ZjZGM2YzZhMGM3MGU5NzMxOTIyMjM3NGFlZTZkMTAxMjE0MDA2OGNlYmUxZmIzOTg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RD-5VWaeG0RsIMzrXnwSE4BRTVNZn1-HTHzP3NFijpQ) ![image](https://private-user-images.githubusercontent.com/112304778/322212340-fae7137b-1b73-402c-ae96-872080fc8344.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMTk3NDgsIm5iZiI6MTcxMzAxOTQ0OCwicGF0aCI6Ii8xMTIzMDQ3NzgvMzIyMjEyMzQwLWZhZTcxMzdiLTFiNzMtNDAyYy1hZTk2LTg3MjA4MGZjODM0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxM1QxNDQ0MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ODdhNTBjMjZlMDY5NTNkOGU5YzNjZTA2ZDgxNTI1YTEyNGZiZDE2MGJjYzgxODE4NWMxNTc5MWQ3NTZkZDgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mXztYxVLBeQNRGAf53OuesP25nRe_SNAYPrAYsf3QFI) https://whimsical.com/?ref=pixelfika https://www.cosmos.so/

十分感谢提出，第二个网站顶栏真的好看
要改的话我还是怕用户不适应的，因为习惯养成后不太好改

**Comment by pasical** [comment]
还有这几个，我觉得可以考虑降低一下搜索框的存在感，不打开的时候会只保留一个图标缩到右侧
![image](https://github.com/hakadao/BewlyBewly/assets/112304778/85beed55-a373-4ce2-92a7-7829ea73b00f)
![image](https://github.com/hakadao/BewlyBewly/assets/112304778/f4d24406-b094-49bf-a637-d294541312fb)
![image](https://github.com/hakadao/BewlyBewly/assets/112304778/ac63ad3d-bddb-4661-bce5-0194754cf688)
https://mymind.com/mobile
https://www.1x.tech/
https://www.herve.paris/en/home

**Comment by pasical** [comment]
其实如果不怕改操作逻辑的话，可以试试logo去掉背景放中间，搜索放左边

**Comment by hakadao** [comment]
謝謝你的建議，先暫時關閉問題，已記錄todo

**Comment by hakadao** [comment]
操作不是想改就改的，之後研究吧，我v0.27.0是想過把搜尋欄隱藏換成一個按鈕點擊才搜尋增加留白空間
![image](https://github.com/user-attachments/assets/61735e91-3dd2-4feb-89f5-db4bc39b101a)
