### ISSUE TITLE
[ADAPTATION] VideoPlaybackPage: Missing adaptation style for Bewly

### ISSUE THREAD

**Issue by SolitudeSun** [BewlyBewly/BewlyBewly#609]
1. **视频`播放界面`中，`视频收藏`的勾选框、勾选框悬停、确认按钮悬停主题色也都不符**

    <img width="350" height="340" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/101030922/30c6cbcc-0960-48c6-8b4d-e34ce9b77bbf"><img width="350" height="340" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/101030922/acf80eef-b7a8-49e4-a9ac-e0457f9f81a3">

2. **视频`播放界面`中，视频播放页稿件`稿件举报`的单选按钮等与主题色不符**

    <img width="700" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/101030922/7e92ac29-542f-41d5-953f-428983fb071b">

3. **视频`播放界面`中，`设置分组`中的勾选框、新建按钮背景色与主题色不符**

    <img width="700" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/101030922/1e0ba47d-d5f1-483b-8980-566ce77349c4"><img width="350" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/101030922/dd4ab32e-0604-440c-9553-b7142140a358"><img width="350" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/101030922/c1c8ba8b-a3eb-4c1c-a12b-3989b6dcce08">

4. **视频`播放界面`评论中，`举报`按钮悬停颜色与主题色不符**
 
    <img width="700" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/101030922/1b321d20-e618-4832-9a75-5cdfbd9bfbb6">

5. **顶栏中，`稍后在看`内的`一键清空`的确认按钮与主题色不符**

    <img width="700" alt="image" src="https://github.com/hakadao/BewlyBewly/assets/101030922/7a11a2d0-67d2-4eb3-9200-f214839161bd">

**Comment by hakadao** [comment]
有些细节就算了吧，我处理不了那么多b站的屎山

**Comment by SolitudeSun** [comment]
好

**Comment by hakadao** [comment]
多選那邊b站直接是用了個圖片我也不知道如何改主題色
![image](https://github.com/hakadao/BewlyBewly/assets/33394391/23acea3e-e5bc-439a-9996-756a108bf978)

**Comment by SolitudeSun** [comment]
能直接替换这个图片吗，如果麻烦的话就算了
