### ISSUE TITLE
页面跳转逻辑问题

### ISSUE THREAD

**Issue by AlvinRey** [BewlyBewly/BewlyBewly#639]
目前的情况是，当使用页面右上方的小工具栏打开消息、动态、收藏、历史记录等页面时，默认是在本页内打开。而官方默认是在新标签页中打开的。我在设置里面找不到相关选项可以调整新页面的打开方式，请问后续有考虑加上吗？

**Comment by hakadao** [comment]
https://github.com/BewlyBewly/BewlyBewly/issues/624#issuecomment-2068074172
