### ISSUE TITLE
[BUG]创作中心没有效果

### ISSUE THREAD

**Issue by kzyqq00-Player** [BewlyBewly/BewlyBewly#641]
### 环境

浏览器: Edge
浏览器版本: 121.0.2277.83
BewlyBewly 版本: 0.16.4

### 问题描述

<img width="400" alt="1" src="https://github.com/BewlyBewly/BewlyBewly/assets/167841679/e71b3d81-ab32-440d-8a5c-be7b268a2259">
创作中心依然是浅色的

**Comment by hakadao** [comment]
沒有適配加不打算
