### ISSUE TITLE
[needs]

### ISSUE THREAD

**Issue by Husirydds** [BewlyBewly/BewlyBewly#643]
### 环境

浏览器:safari

### 问题描述

是否有safari浏览器的版本呢

**Comment by hakadao** [comment]
標題描述一下詳細內容，另外需求不是bug

**Comment by Husirydds** [comment]
插件支不支持Safari浏览器呢
我主要使用的是Safari浏览器,下载了之后没有找到安装教程

**Comment by hakadao** [comment]
> 插件支不支持Safari浏览器呢
> 
> 我主要使用的是Safari浏览器,下载了之后没有找到安装教程

safari支援後面會做，你可以嘗試用feat/support-safari編譯一個出來用用
