### ISSUE TITLE
[BUG]顶部动态预览，直播内容会重复显示

### ISSUE THREAD

**Issue by GGBondzzy** [BewlyBewly/BewlyBewly#649]
### 环境

浏览器: Chrome
浏览器版本: 124.0.6367.61
BewlyBewly 版本: 0.17.0

### 问题描述

![image](https://github.com/BewlyBewly/BewlyBewly/assets/76947595/cb2798dd-6cf2-4950-b075-dd266c5e8b50)
![image](https://github.com/BewlyBewly/BewlyBewly/assets/76947595/21033c50-3b61-4505-94c2-9917232dc55c)
直播预览里面会把当前的正在直播的UP重复显示一遍

**Comment by hakadao** [comment]
是疊加重複的內容嗎，給出截圖沒有看到

**Comment by GGBondzzy** [comment]
发现只有在直播人数达到十个或以上的时候会重复显示
