### ISSUE TITLE
[BUG]开启插件后白屏

### ISSUE THREAD

**Issue by winbug** [BewlyBewly/BewlyBewly#655]
### 环境

浏览器: Chrome
浏览器版本: 124.0.6367.61
BewlyBewly 版本: 0.17.0

### 问题描述

开启插件后，屏幕只有头部nav还在，其他内容部分都为白屏状态。

**Comment by starknt** [comment]
请先检查是否插件的是否全部开启

**Comment by hakadao** [comment]
有F5或是否排查過是與其他插件衝突

**Comment by winbug** [comment]
多谢starknt，确实是，去插件管理里面将所有权限打开就好了。
