### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by altair441n** [BewlyBewly/BewlyBewly#657]
### 环境

浏览器: Chrome
浏览器版本: 124.0.6367.79
BewlyBewly 版本: 0.17.0

### 问题描述

安装扩展后，在B站首页使用 smartUp手势 的 向上滚动和向下滚动 没有作用，视频页是可以正常滚动的。另外，设置的背景图片只在B站首页展示了，视频页没展示，不知道是不是BUG。

**Comment by hakadao** [comment]
其他插件共用很難處理衝突，另外背景只在首頁顯示
