### ISSUE TITLE
[BUG]: 笔记相关页面没有适配黑暗模式

### ISSUE THREAD

**Issue by ZC-eto** [BewlyBewly/BewlyBewly#663]
### 环境

浏览器: Chrome
浏览器版本: 124.0.6367.61
BewlyBewly 版本: 0.17.0

### 问题描述

暗黑模式下，B站的笔记无法正常显示。希望大大可以修复。  第二张图为暗黑模式下的情况， 无法显示笔记。
![image](https://github.com/BewlyBewly/BewlyBewly/assets/73825786/2aacbc22-52e9-4b57-923a-ffb8138117be)
![image](https://github.com/BewlyBewly/BewlyBewly/assets/73825786/e6188ed4-ae4d-4978-8b9a-4919c5e83e18)

**Comment by hakadao** [comment]
標題能不能大概說一下詳細內容？？？

**Comment by hakadao** [comment]
最好給出一個bv號吧，是所有筆記都這樣嗎

**Comment by ZC-eto** [comment]
bv号是啥啊🥲，是所有的笔记都是这样的，在日光（白色）模式下是可以正常实现的，就是可以看到字，暗黑 模式下就不见了，但是可以选中，就说明只是显示不出来，实际上还是存在的。下面一张是被选中的，一张是在暗黑模式下不可见的截图。
![image](https://github.com/BewlyBewly/BewlyBewly/assets/73825786/d73cd290-4641-42b0-b285-d82b4e553722)
![image](https://github.com/BewlyBewly/BewlyBewly/assets/73825786/1971930b-d478-47fe-b636-563cd5b76c67)

**Comment by hakadao** [comment]
v0.18.1已经改了，chrome上已更新

**Comment by ZC-eto** [comment]
哦哦哦，刚刚发现，厉害的大大
