### ISSUE TITLE
[建议] 能否出个 YouTuBe 的插件？

### ISSUE THREAD

**Issue by laniv** [BewlyBewly/BewlyBewly#667]
### 环境

浏览器: (如 Chrome)
浏览器版本: (如 123.0.6312.107)
BewlyBewly 版本: (如 0.16.2)

### 问题描述

首先感谢作者的这个插件，简直打开了一个新世界。每天都要刷B站，现在用这个插件后，网站清新简洁多了~！非常感谢~！
对了，作者在有时间的时候，是否会考虑出个 油管 的插件呀？非常期待~！

### 预期结果

非常期待~！

**Comment by hakadao** [comment]
抽出不了時間，現在bewly還有很多問題要處理
