### ISSUE TITLE
[BUG] "不敢兴趣”出错

### ISSUE THREAD

**Issue by K-O-N-B** [BewlyBewly/BewlyBewly#669]
### 环境

浏览器: edge
浏览器版本: 124.0.2478.51 
BewlyBewly 版本:0.18.0

### 问题描述

在首页选择某个视频“不敢兴趣”后，出现提示“请求错误”

**Comment by hakadao** [comment]
如果你是使用app端推介的，請先授權access key再使用，否則會出錯
