### ISSUE TITLE
首页左上角语言跟设置语言不对等

### ISSUE THREAD

**Issue by cherryrain1** [BewlyBewly/BewlyBewly#674]
![QQ截图20240426125210](https://github.com/BewlyBewly/BewlyBewly/assets/106550734/ee260b50-9589-4bf5-b13c-c86f9f2748fc)
![QQ截图20240426205431](https://github.com/BewlyBewly/BewlyBewly/assets/106550734/1da59745-6118-4fd8-82a5-1d6805a2b936)

**Comment by starknt** [comment]
请问你的是edge浏览器？

**Comment by hakadao** [comment]
請更新到最新版本0.18.0，新版本問題已解決
