### ISSUE TITLE
插件添加后往下滚动刷新率很低，我的刷新率是170hz，但往下滚动时可能只有60hz

### ISSUE THREAD

**Issue by Coforgpaper** [BewlyBewly/BewlyBewly#675]
### 环境

浏览器: (Edge)
BewlyBewly 版本: (如 0.18)

### 问题描述

插件添加后往下滚动刷新率很低，我的刷新率是170hz，但往下滚动时可能只有60hz

**Comment by hakadao** [comment]
bewlybewly甚麼版本，方便錄端視頻嗎

**Comment by xiaobeioo** [comment]
确实有性能问题。
在主页上不掉帧，但笔记本的风扇会高速转动，关掉毛玻璃效果也一样，原版主页上风扇不会转的。
在视频页上，上下滚动会掉帧。
版本v0.18.0

**Comment by hakadao** [comment]
正常你不設置遮罩和背景不會太卡使用時 @xiaobeioo @Coforgpaper

**Comment by ycb678** [comment]
是的 我也有同样问题 在edge浏览器会出现 但在谷歌就不会有

**Comment by xiaobeioo** [comment]
浏览器Edge
默认设置，开启毛玻璃，关闭遮罩和背景。
主页窗口，只要标签页在前台显示，无任何其它操作，风扇就转的厉害，滚动页面不掉帧。（笔记本屏2K 240hz，开关毛玻璃不影响结果）
视频窗口，仅在开启毛玻璃效果后，滚动页面会掉帧（大概电脑性能不足），关闭后正常。

在主页窗口性能测试显示有个  计划样式重新计算  在一直重复运行，希望能排查一下

**Comment by Rokukkkk** [comment]
没有明显掉帧但是确实有不流畅的感觉，可能和edge自带的平滑滚动有关系？

**Comment by hakadao** [comment]
v0.18.10 嘗試調整一下, 應該比以前好多了
