### ISSUE TITLE
[BUG] 不能拖拽打开链接

### ISSUE THREAD

**Issue by laniv** [BewlyBewly/BewlyBewly#677]
### 环境

浏览器: EDGE
浏览器版本: 124.0.2478.67
BewlyBewly 版本: 0.16.7

### 问题描述

使用插件后，不能拖拽打开视频链接了。
得使用 鼠标右键 来打开链接，这点有点不方便。
希望作者修复以下~！

### 预期结果

使用鼠标拖拽打开链接。

**Comment by hakadao** [comment]
我可以啊
https://github.com/BewlyBewly/BewlyBewly/assets/33394391/46e915f6-06fd-41d5-b319-b9a554a6edc7
