### ISSUE TITLE
[BUG] 使用原版 Bilibili 首页下滑的时候顶部分类会比较突兀

### ISSUE THREAD

**Issue by quiet-star-gazing** [BewlyBewly/BewlyBewly#678]
### 环境

浏览器:Edge
浏览器版本:124.0.2478.51 (正式版本) (64 位)
BewlyBewly 版本: 0.16.7

### 问题描述

![image](https://github.com/BewlyBewly/BewlyBewly/assets/109467643/a75958aa-0947-4068-ad27-4361da27e602)

### 预期结果

![image](https://github.com/BewlyBewly/BewlyBewly/assets/109467643/0b45f96d-ee6b-442e-afe2-c4d14ca90abd)

**Comment by hakadao** [comment]
這是b站原本的設計，我不怎麼想動先這樣吧
