### ISSUE TITLE
[Feature Request]增加关闭顶部导航栏按钮

### ISSUE THREAD

**Issue by jiang-yuan** [BewlyBewly/BewlyBewly#684]
### 环境

浏览器: (如 Chrome)
浏览器版本: (如 123.0.6312.107)
BewlyBewly 版本: (如 0.16.2)

### 问题描述

如何关闭顶部导航栏，因为用了别的脚本所以两个导航栏重叠在一起了
而且滚动的时候顶部导航栏一直显示，占用了屏幕显示空间，个人比较不习惯
找到设置里面只有自动隐藏导航栏，但是没能完全隐藏
请求至少允许在非主页隐藏导航栏，或者导航栏不跟随页面滚动
![image](https://github.com/BewlyBewly/BewlyBewly/assets/36291537/989d14a3-386a-4ee0-8529-b38f8a14d1a9)

### 预期结果

请求至少允许在非主页隐藏导航栏，或者导航栏不跟随页面滚动

**Comment by hakadao** [comment]
设置->兼容性那里有个bilibili evolved选项

**Comment by jiang-yuan** [comment]
![image](https://github.com/BewlyBewly/BewlyBewly/assets/36291537/50665a63-6547-487c-be35-72b3e6df8c39)
此选项为打开状态
另外我请求功能是在非首页关闭导航栏浮动跟随功能

**Comment by hakadao** [comment]
我不知道你是否看清楚右边的开关显示的是什么
