### ISSUE TITLE
[BUG] 单独设置搜索页壁纸选项的内置壁纸中，只有第一行的壁纸有效

### ISSUE THREAD

**Issue by fireflame-opx** [BewlyBewly/BewlyBewly#687]
### 环境

浏览器: Chrome
浏览器版本: 124.0.6367.79
BewlyBewly 版本: 0.18.1

### 问题描述

单独设置搜索页壁纸选项的内置壁纸中，只有第一行的壁纸有效
0.18.1版本出现，之前正常

**Comment by hyoban** [comment]
无法复现

![ScreenShot 2024-04-28 20 00 38](https://github.com/BewlyBewly/BewlyBewly/assets/38493346/23580f4c-87d3-4b3b-a50a-e83a884f50c4)

**Comment by fireflame-opx** [comment]
@hyoban 抱歉表述不清楚，是在开启首页使用搜索页模式之后，首页的搜索栏那块
