### ISSUE TITLE
能不能增加一个调节阴影的按钮或者选项？

### ISSUE THREAD

**Issue by jq6136** [BewlyBewly/BewlyBewly#696]
### 环境

浏览器: (如 Safari)
浏览器版本: (如 19618.1.15.11.14)
BewlyBewly 版本: (如 0.16.5)

### 问题描述

就是我感觉自带的阴影范围和深度都有点大，希望能调节

### 预期结果

希望能增加一个调节阴影的按钮或者选项

**Comment by hakadao** [comment]
後續加個自訂css開放調整吧

**Comment by jq6136** [comment]
谢谢作者的回复，期待该软件的新版本，还有顺带谢谢作者调整了Tag（我这里好像不能调的）

**Comment by hakadao** [comment]
之後在外觀最下可以自己改css，再維護多個陰影樣式有點麻煩直接開放改樣式算了
![image](https://github.com/user-attachments/assets/0d756713-67e8-44ee-92bf-bfb124f2604d)
