### ISSUE TITLE
[BUG]Chrome浏览器加载已解压的程序报错

### ISSUE THREAD

**Issue by CreeperAWA** [BewlyBewly/BewlyBewly#702]
### 环境

浏览器: Chrome
浏览器版本: 124.0.6367.91
BewlyBewly 版本: 安装的为0.18.2，实际上似乎不止这个版本有此问题

### 问题描述

使用Chrome加载解压后的此插件报错，提示
```
rules.json: Internal error while parsing rules.
无法加载清单。
```

### 预期结果

可以正常安装并使用

**Comment by starknt** [comment]
并不能复现此错误

**Comment by hakadao** [comment]
檢查一下是否錯用 `extension-firefox` 的載入到 chrome

**Comment by CreeperAWA** [comment]
> 檢查一下是否錯用 `extension-firefox` 的載入到 chrome

不是，用的就是发行版里的第二个

**Comment by starknt** [comment]
> 就是用的第二个

如果可以的话，请录制一个视频 (^-^)

**Comment by CreeperAWA** [comment]
![recording](https://github.com/BewlyBewly/BewlyBewly/assets/134939494/eda04e2b-4d4c-4c8c-8dae-0c39024e98e9)

**Comment by hyoban** [comment]
正确下载的扩展，解压后应当有以下三项

![ScreenShot 2024-05-03 13 35 10](https://github.com/BewlyBewly/BewlyBewly/assets/38493346/2455b917-7186-4354-aa25-674337e840eb)

**Comment by CreeperAWA** [comment]
> 正确下载的扩展，解压后应当有以下三项
> 
> ![ScreenShot 2024-05-03 13 35 10](https://private-user-images.githubusercontent.com/38493346/327653938-2455b917-7186-4354-aa25-674337e840eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MjI4MzYsIm5iZiI6MTcxNDcyMjUzNiwicGF0aCI6Ii8zODQ5MzM0Ni8zMjc2NTM5MzgtMjQ1NWI5MTctNzE4Ni00MzU0LWFhMjUtNjc0MzM3ZTg0MGViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDA3NDg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5MmEyM2Q0MDcyYmJkZGIxZjYwN2I5NmVjZjVmMWRkMTFmODFlYjM5YjNhMTBmYTU2ZTIyZGQ1YjNjMWMwNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xL_r3BzqSWQ-1qGYKvRosdZ_1Mp7IFjhrtoRa2vpj5s)

Windows在选择文件夹状态下不会显示文件，只会显示文件夹，文件夹里是有json文件的

**Comment by CreeperAWA** [comment]
依照错误提示看应是`.\assets\rules.json`出了问题

**Comment by starknt** [comment]
> 依照错误提示看应是`.\assets\rules.json`出了问题

感觉是你的解压软件的问题

**Comment by CreeperAWA** [comment]
源码里找的也不能用

**Comment by CreeperAWA** [comment]
解压软件使用的是bandizip 7.3.2 版本号 65001

**Comment by starknt** [comment]
我建议你换到别的盘符(例如： D)后再安装

**Comment by CreeperAWA** [comment]
感谢！我把Chrome以管理员身份运行就可以了，很奇怪，以前都没有这样，插件也是放在Chrome目录里的，总之谢谢啦！
