### ISSUE TITLE
【功能建议】对设置图标的动态效果建议

### ISSUE THREAD

**Issue by Anyayay** [BewlyBewly/BewlyBewly#703]
我注意到暗色模式的开关有动态效果而设置没有，因此提出此建议
可参考b站播放器的动态效果（不过如果这样做，要适当加快暗色模式开关的动态效果，以求统一）
![recording](https://github.com/BewlyBewly/BewlyBewly/assets/37764175/62ec287d-96c4-45f1-8652-880279bbcd84)

**Comment by hakadao** [comment]
本來dark mode和light mode的切換是個彩蛋才特意做得那麼特別，其他覺得沒必要
太多動效反而人會產生反感
