### ISSUE TITLE
[BUG] 在Edge中插件损坏问题

### ISSUE THREAD

**Issue by Meteor2333** [BewlyBewly/BewlyBewly#705]
### 环境

浏览器: Microsoft Edge
浏览器版本: 124.0.2478.67 (正式版本) (64 位)
BewlyBewly 版本: 0.18.2

### 问题描述

Dock栏→设置→外观→背景图片
背景图片模式为内置→选择你的背景
切换背景后插件将不可用
![微信图片_20240503142655](https://github.com/BewlyBewly/BewlyBewly/assets/78150764/b7865b0e-475d-4e0e-8807-375a5b2748b5)

**Comment by Meteor2333** [comment]
添加一个说明：此bug只在edge加载项下载时触发 同版本下github中下载的插件没有此bug

**Comment by IzumiMasaharu** [comment]
补充：同环境下更改这两个选项也会显示扩展损坏
![屏幕截图 2024-05-03 194505](https://github.com/BewlyBewly/BewlyBewly/assets/108920558/7d1ce27f-cc57-4cea-beb4-807ab4e68967)

**Comment by IzumiMasaharu** [comment]
发现了Edge端的一个解决方案：只要用Chrome商店的下载源就不会出问题
![屏幕截图 2024-05-03 200501](https://github.com/BewlyBewly/BewlyBewly/assets/108920558/b7429f0d-19ec-4022-932e-af4e85bafd98)

**Comment by hakadao** [comment]
不太清楚為何只有edge有這個問題

**Comment by wlwxj** [comment]
+1

**Comment by Meteor2333** [comment]
> 发现了Edge端的一个解决方案：只要用Chrome商店的下载源就不会出问题 ![屏幕截图 2024-05-03 200501](https://private-user-images.githubusercontent.com/108920558/327748192-b7429f0d-19ec-4022-932e-af4e85bafd98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NzYwNTEsIm5iZiI6MTcxNDg3NTc1MSwicGF0aCI6Ii8xMDg5MjA1NTgvMzI3NzQ4MTkyLWI3NDI5ZjBkLTE5ZWMtNDAyMi05MzJlLWFmNGU4NWJhZmQ5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNVQwMjIyMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYzUyZTg1YThlMmJhMjNlM2NjZGFlZDAzZWUyZDY4MGQxNDgxNGExODJiMDcwOGRmMWIzMWRiM2NmOGU4ZjJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lbpI-DRHO37flWSI8gemwIYsYD2Qmi-V3AowCWFdiJw)

Yep, this bug is only present with Edge add-ons

**Comment by saki3525** [comment]
同样的问题，修改设定后插件会崩溃。还有就是打开关于页面时什么都不显示。

**Comment by SolitudeSun** [comment]
问题相同，只要修改设置就损坏报错，之后只能重新安装，目前暂时使用 Chrome 源的版本

**Comment by QwindF** [comment]
同问题，插眼。
![image](https://github.com/BewlyBewly/BewlyBewly/assets/87116340/edcdfce8-ae31-4d7b-8e9c-79dc822660c9)

**Comment by a562314** [comment]
更改颜色也会导致崩溃

**Comment by hakadao** [comment]
> 0.18.4 edge版本![image](https://github.com/BewlyBewly/BewlyBewly/assets/46023154/f8f46bda-5b42-4014-a672-428239d5f69f)
> 
> 

edge 獨有問題請去 chrome web store 那邊下載更新，edge 版本遲遲沒有更新因爲傻逼edge addons那邊審核一定要你等7個工作日才給過

**Comment by hakadao** [comment]
傻逼edge現在終於審核成功已經上架舊版本 v0.18.8 了，應該不會再有這問題了

**Comment by HumanMus1c** [comment]
才发现edge浏览器安装的chrome插件也能无需特殊网络后台自动更新了。所以基本不需要再安装edge版本的插件了。edge插件审核慢，还一堆换皮垃圾。怪不得一些chrome插件根本就不上架edge插件商店。edge真的垃圾。
