### ISSUE TITLE
[BUG]安装后与vimium插件冲突无法scroll

### ISSUE THREAD

**Issue by xbunax** [BewlyBewly/BewlyBewly#706]
### 环境

浏览器:  Arc & chrome
浏览器版本: 124.0.6367.92 (正式版本) (arm64)
BewlyBewly 版本:  0.18.2

### 问题描述

插件安装后与`vimium`插件冲突无法scroll，Arc和Chrome都遇到此问题

### 预期结果

`vimium`插件功能正常

**Comment by hakadao** [comment]
插件之間共用的衝突不是bug，其次與不同插件出現的異常情況很難處理
