### ISSUE TITLE
[ADAPTATION] 右侧标签栏在暗夜模式下的配色很突兀

### ISSUE THREAD

**Issue by RightNode** [BewlyBewly/BewlyBewly#707]
### 环境

浏览器: Chrome
浏览器版本: 124.0.6367.119（正式版本） (arm64)
BewlyBewly 版本: 0.18.2

### 问题描述

右侧播放集合列表上方的标签栏右侧半透明组件，在暗夜模式下的配色未作修改，非常突兀，截图如下：

![image](https://github.com/BewlyBewly/BewlyBewly/assets/14964119/fbb9b1e0-5f66-4177-aa27-41e7599fffd2)

**Comment by hakadao** [comment]
errrrrrrrrrb站甚麼時候更新成youtube那種樣式了

**Comment by hakadao** [comment]
能否有此影片的地址提供？好像並非所有影片頁都有這個標籤

**Comment by hakadao** [comment]
我這裏暫時沒有出現此情況
![image](https://github.com/BewlyBewly/BewlyBewly/assets/33394391/ba752e6a-5c75-4e79-aeaa-d075bd70ee3e)

**Comment by SolitudeSun** [comment]
> 我這裏暫時沒有出現此情況 ![image](https://private-user-images.githubusercontent.com/33394391/328085736-ba752e6a-5c75-4e79-aeaa-d075bd70ee3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNjA5NDQsIm5iZiI6MTcxNTA2MDY0NCwicGF0aCI6Ii8zMzM5NDM5MS8zMjgwODU3MzYtYmE3NTJlNmEtNWM3NS00ZTc5LWFlYWEtZDA3NWJkNzBlZTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDA1NDQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ZWQyNjRiMWJkNjdhYWRhMGEyODllYjkzOTMxZGI3NmViYjlhMWQzNDUyNjYwYzI5NWNiZDIwOWIzZDExZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tJHuB76nilePnjaI_w6JaNvsLqxzcPECeHVKP5qZCgU)

**这是原视频链接：https://www.bilibili.com/video/BV1PJ411n7xZ
我这里没有这个组件，他可能是加了什么其他的插件或扩展导致的**

**Comment by RightNode** [comment]
视频地址如下：

https://www.bilibili.com/video/BV1PJ411n7xZ/?p=186&spm_id_from=pageDriver&vd_source=318625b4b41c096206ad88458a24c018

这是我chrome上目前在用的所有插件：

![image](https://github.com/BewlyBewly/BewlyBewly/assets/14964119/beedce39-fe04-47aa-acb0-de504e798d37)

另外，safari上也有标签栏：

![image](https://github.com/BewlyBewly/BewlyBewly/assets/14964119/719dc8dd-f360-48f0-afc3-1c3ceb691e94)

**Comment by SolitudeSun** [comment]
可能和B站推送有关？
Chrome我这里也没有

![image](https://github.com/BewlyBewly/BewlyBewly/assets/101030922/bc4a84bc-fe18-4052-8573-323245b3b0c1)

**Comment by SolitudeSun** [comment]
我猜测可能因为是macOS，显示的内容不太一样

![image](https://github.com/BewlyBewly/BewlyBewly/assets/101030922/36bfe8ff-6644-463d-bc1d-2d0dd0d14a1b)
![image](https://github.com/BewlyBewly/BewlyBewly/assets/101030922/77ad58e8-f3c0-4cce-a003-88310605bf97)
