### ISSUE TITLE
【功能建议】希望增加触控功能

### ISSUE THREAD

**Issue by hsake233** [BewlyBewly/BewlyBewly#710]
如题，我的设备是surface pro，一直在使用b站某位up的【触碰改造计划】拓展，安装您的拓展后发现这两个存在冲突，但我确实无法割舍触控体验，希望能增加触摸功能

**Comment by hakadao** [comment]
目前暫時沒有時間和精力支援觸控功能, 後期看看有沒有其他人可以實現或等版本穩定下來再調整
