### ISSUE TITLE
无法加载用户主页

### ISSUE THREAD

**Issue by TianLang-Hacker** [BewlyBewly/BewlyBewly#712]
### 环境

浏览器: (如 Chrome)
浏览器版本: (如 123.0.6312.107)
BewlyBewly 版本: (如 0.16.2)

### 问题描述

浏览器: Firefox Linux版
浏览器版本: 115.8.0esr (64 位)
BewlyBewly 版本: 0.16.6

1：鼠标点击关注列表后返回错误码：-500_0x572074.getBoundingClientRect is not a function
2：访问别人的主页的时候无法加载目标用户主页，全是空白（插件需要的权限全给了）
![1](https://github.com/BewlyBewly/BewlyBewly/assets/60563003/efa17101-422a-46bc-9370-2056f699331e)
![2](https://github.com/BewlyBewly/BewlyBewly/assets/60563003/02e4ad62-a5bc-4c7e-aaa8-a155bc8b16ca)
![3](https://github.com/BewlyBewly/BewlyBewly/assets/60563003/81a19b9a-64de-404b-a6a2-ef0920468345)

**Comment by starknt** [comment]
没办法复现，你或许尝试一下升级浏览器

**Comment by hakadao** [comment]
firefox addons那邊因爲一些問題導致遲遲不能更新新版本，嘗試用github那邊的最新版本再看看

**Comment by hakadao** [comment]
firefox 已經重新上架
https://addons.mozilla.org/en-US/firefox/addon/bewlybewly/
