### ISSUE TITLE
[BUG] 搜索栏聚焦时出现的人物加载失败

### ISSUE THREAD

**Issue by SolitudeSun** [BewlyBewly/BewlyBewly#716]
### 环境

浏览器: Microsoft Edge
浏览器版本: 124.0.2478.80
BewlyBewly 版本: 0.18.2

#### 如题：搜索栏聚焦时出现的人物加载失败

![image](https://github.com/BewlyBewly/BewlyBewly/assets/101030922/429be812-12c7-4d0b-bcc9-9d5ed9bba270)

#### 修复正常显示人物

**Comment by hakadao** [comment]
已修復，今晚發個版本
