### ISSUE TITLE
[BUG] 选择背景时默认启用背景遮罩效果的按钮不会自动打开

### ISSUE THREAD

**Issue by SolitudeSun** [BewlyBewly/BewlyBewly#717]
### 环境

浏览器: Microsoft Edge
浏览器版本: 124.0.2478.80
BewlyBewly 版本: 0.18.2

### 问题描述

**如题：默认情况下，选择图片前`启用背景遮罩效果`按钮为关闭，选择图片后按钮不会正常打开，且会自动调整样式**

![image](https://github.com/BewlyBewly/BewlyBewly/assets/101030922/9953169f-7c0e-43ee-9aa7-352610a5731f)

**以下为应该选择后表现的效果**

![image](https://github.com/BewlyBewly/BewlyBewly/assets/101030922/fa4b4db8-5b57-4ece-8b1b-a3bda95513ca)
![image](https://github.com/BewlyBewly/BewlyBewly/assets/101030922/c5faa003-ea2a-4185-9a8a-6ef8a9fd227a)

### 预期结果

**修复为应该表现的效果**

**Comment by hakadao** [comment]
這個說真的我也不知道如何解決，數據是變了但是視圖層沒有更新

**Comment by SolitudeSun** [comment]
那能否改成默认为关闭状态，不自动设置透明度呢，或者默认启用背景遮罩效果

**Comment by hakadao** [comment]
> 那能否把这个样式直接改成默认为关闭状态，不自动设置透明度呢，或者默认点击了直接启用背景遮罩效果的按钮

之前被很多不會用的用戶問可不可以加個遮障功能，他們甚至發現不了這功能
後面直接用了指定背景強制啟用了

**Comment by SolitudeSun** [comment]
> > 那能否把这个样式直接改成默认为关闭状态，不自动设置透明度呢，或者默认点击了直接启用背景遮罩效果的按钮
> 
> 之前被很多不會用的用戶問可不可以加個遮障功能，他們甚至發現不了這功能 後面直接用了指定背景強制啟用了

那就先这样吧，不影响使用，视图页面刷新后也是正常的
