### ISSUE TITLE
[BUG] 主页刷到的视频弹幕数为`0`时，视频卡片弹幕数显示错误

### ISSUE THREAD

**Issue by SolitudeSun** [BewlyBewly/BewlyBewly#723]
### 环境

浏览器: Microsoft Edge
浏览器版本: 124.0.2478.80
BewlyBewly 版本: 0.18.2

### 问题描述

**如题：例如如下两个视频弹幕数为`0`，但是主页显示的是`-弹幕`**

![image](https://github.com/BewlyBewly/BewlyBewly/assets/101030922/f1b3192d-9de9-4e52-8d2f-0b166a983b65)
![image](https://github.com/BewlyBewly/BewlyBewly/assets/101030922/8a1de858-4143-4457-9ba5-025ecfd799dd)

### 预期结果

**主页不显示弹幕数为`0`的标签，或者直接显示`0弹幕`**

**Comment by hakadao** [comment]
b站那邊返回的就是-號，我覺得不用處理這裏

**Comment by SolitudeSun** [comment]
OK

**Comment by SolitudeSun** [comment]
那就这样吧，没问题了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月06日 14:52 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [BewlyBewly/BewlyBewly] [BUG] 主页刷到的视频弹幕数为`0`时，视频卡片弹幕数显示错误 (Issue #723) |

Closed #723 as not planned.
