### ISSUE TITLE
背景会花屏闪烁

### ISSUE THREAD

**Issue by yebei199** [BewlyBewly/BewlyBewly#724]
### 环境

浏览器: Chrome
浏览器版本: 版本 124.0.6367.119（正式版本） （64 位）
BewlyBewly 版本:0.182

### 问题描述

使用的时候背景会花屏闪烁, 尤其是在滚动的时候, 不动的话就不会, 一闪而过, 但是频率非常高, 不过不会影响视频播放和正常使用, 但是会对看评论区有一些影响

**Comment by hakadao** [comment]
話說視頻頁好像沒有自訂義背景吧
