### ISSUE TITLE
更新之后加个红点提示在关于里

### ISSUE THREAD

**Issue by DD224ever** [BewlyBewly/BewlyBewly#726]
### 环境

Vivaldi | 6.7.3329.24

BewlyBewly 版本: (0.17.0)

### 问题描述

能不能插件有更新之后加个提示，加个红点或是小弹窗，还是说有提醒我没发现？目前只能隔几天打开一下github看看有没有更新

还有就是我自定义了背景图打开主页总是要加载图片，我用的图才600kb不到，问一下这是扩展的问题，还是我的电脑性能的问题还是网络问题，抑或是云图库的问题？我的电脑是amd4800h轻薄本无显卡。

**Comment by hakadao** [comment]
Vivaldi 瀏覽器可以在 chrome web store下載獲得自動更新
另外新版本是 v0.18.4，這個有點舊了你現在用的那個
圖片載入速度問題不是插件可以控制的，是網絡原因
