### ISSUE TITLE
[BUG] 收藏的音乐点击“稍后再看”并添加后，添加的为随机的视频

### ISSUE THREAD

**Issue by SolitudeSun** [BewlyBewly/BewlyBewly#727]
### 环境

浏览器: Microsoft Edge
浏览器版本: 124.0.2478.80
BewlyBewly 版本: 0.18.4

### 问题描述

**在收藏的音乐中点击添加"稍后再看"，"稍后再看"列表中则为其他不相关的视频，音乐应该是没有"稍后再看"这个功能的**

**还有一点就是，B 站音乐获取的 up 主头像都为空，应该是 B 站方面的问题，实际的 up 主都有头像
但是这个空会导致收藏栏的样式不太美观，能否重新修改下这方面的样式呢**

**这个问题与已解决的 #606 有差不多的问题**

![image](https://github.com/BewlyBewly/BewlyBewly/assets/101030922/0ea94d08-2705-478d-8657-d1f605ede165)
![image](https://github.com/BewlyBewly/BewlyBewly/assets/101030922/c08aae5f-1f3a-44ac-b94d-72f02c96d962)

![image](https://github.com/BewlyBewly/BewlyBewly/assets/101030922/57551104-6f03-456e-ac3d-a60d8c08047b)

### 预期结果

**删除收藏音乐的稍后再看按钮，修改部分样式**

**Comment by hakadao** [comment]
實際上就是b站音樂類型沒有返回up主頭像，那邊url是空的

**Comment by SolitudeSun** [comment]
> 實際上就是b站音樂類型沒有返回up主頭像，那邊url是空的

是的，这个是B站方面的问题

**Comment by hakadao** [comment]
這個就連在官方收藏頁裏點擊稍後觀看也有這個bug，不會修 = =

**Comment by SolitudeSun** [comment]
那先放着吧，影响不是太大



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月31日 00:03 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [BewlyBewly/BewlyBewly] [BUG] 收藏的音乐点击“稍后再看”并添加后，添加的为随机的视频 (Issue #727) |

這個就連在官方收藏頁裏點擊稍後觀看也有這個bug，不會修 = =
