### ISSUE TITLE
[BUG] 稍后再看中的"清空稍后再看"有时候需要多次点击

### ISSUE THREAD

**Issue by SolitudeSun** [BewlyBewly/BewlyBewly#728]
### 环境

浏览器: Microsoft Edge
浏览器版本: 124.0.2478.80
BewlyBewly 版本: 0.18.4

### 问题描述

**在点击"清空稍后再看"后，有时候视频不会消失需要再次点击，好像是概率事件？**
**但是如果点击后刷新界面后是正常的，应该是数据改了但是页面没有更新**

![image](https://github.com/BewlyBewly/BewlyBewly/assets/101030922/15b68dc8-0321-4e24-b882-f03174685b6f)
![image](https://github.com/BewlyBewly/BewlyBewly/assets/101030922/2d28c9a0-a41b-473e-9941-8d0a780413a5)

**还有一个建议就是，希望做一个和原版页面显示哪些视频"已观看"的标志**

![image](https://github.com/BewlyBewly/BewlyBewly/assets/101030922/b7611428-8126-407a-84a6-abeaf9ce65a9)

### 预期结果

**点击一次后就能清空，无需再次点击或刷新**
**希望添加一个"已观看"的标志**

**Comment by hakadao** [comment]
這單純是因為沒做等待效果而已，請求b站接口需要一點時間
