### ISSUE TITLE
主页显示缺少内容

### ISSUE THREAD

**Issue by deng-chao-rgb** [BewlyBewly/BewlyBewly#729]
### 环境

浏览器: (如 Chrome)
浏览器版本: (如 123.0.6312.107)
BewlyBewly 版本: (如 0.16.2)

### 问题描述

你好，这个主要收藏栏没能把我的收藏和订阅内容显示出来，如果可以的话，效率拉满。这个可以实现吗？

### 预期结果

![1](https://github.com/BewlyBewly/BewlyBewly/assets/83454018/992d8357-7eee-48c8-8854-cf5d0c4bb031)
![2](https://github.com/BewlyBewly/BewlyBewly/assets/83454018/657afc50-3c85-4a77-b052-3509e985262b)

**Comment by hakadao** [comment]
原本b站頂欄收藏都沒有這個功能我覺得不用加目前來說
