### ISSUE TITLE
[BUG]首页推荐视频中的已关注UP视频不显示发布日期

### ISSUE THREAD

**Issue by Seameee** [BewlyBewly/BewlyBewly#730]
### 环境

浏览器: Microsoft Edge
浏览器版本:126.0.2552.0 (正式版本) dev (64 位)
BewlyBewly 版本:0.18.4

### 问题描述

首页推荐视频中的已关注UP视频不显示发布日期，而未关注视频可以正常显示发布日期。另外没有使用插件的时候，原始网页也是可以显示已关注UP视频的发布日期。不知是否是因为使用了app端的推荐算法，烦请帮忙排查一下是什么原因。
![使用bewlybewly的首页](https://github.com/BewlyBewly/BewlyBewly/assets/31821836/f8e5439d-0e6c-4bca-9c37-11214c888ac8)
![未使用bewlybewly的首页](https://github.com/BewlyBewly/BewlyBewly/assets/31821836/d536ab72-4102-4a59-afc1-3deac7c1fdcd)

### 预期结果

首页已关注UP主推荐视频，也可以正常显示发布日期

**Comment by hakadao** [comment]
b站app端算法內容只要你是關注了up主都不會出現時間
<img width="1342" alt="image" src="https://github.com/BewlyBewly/BewlyBewly/assets/33394391/8050e19d-69bd-4d01-849d-642cc785e215">
