### ISSUE TITLE
Firefox无法从扩展商店安装组件是什么原因？

### ISSUE THREAD

**Issue by rainocean** [BewlyBewly/BewlyBewly#734]
### 环境

浏览器: Firefox  版本：125.0.3 (64 位)
系统：macOS 14.4.1 

### 问题描述

尝试从这里安装组件，但是跳出来的页面显示没找到内容
Firefox: https://addons.mozilla.org/lt/firefox/addon/bewlybewly/

<img width="1360" alt="图片" src="https://github.com/BewlyBewly/BewlyBewly/assets/16640966/3c09892c-e086-46ab-ac77-609fa6ca68b2">

尝试手动安装， 把签名要求改为false也没装上，求解
<img width="984" alt="图片" src="https://github.com/BewlyBewly/BewlyBewly/assets/16640966/4c651605-f095-4e4b-a190-a90115efd24a">

**Comment by rainocean** [comment]
打错标签了 不知道怎么改 ……

**Comment by hakadao** [comment]
firefox因爲之前沒有上傳源碼被屏蔽說違反規定，現在還在等待審核
![image](https://github.com/BewlyBewly/BewlyBewly/assets/33394391/4ef7f1f5-ab43-4124-af2d-f0e79e886b40)

**Comment by hakadao** [comment]
現在這樣，接下來交給 firefox addons 的 reviewers 了
![image](https://github.com/BewlyBewly/BewlyBewly/assets/33394391/35860af0-0dda-435d-8add-2ef42031a242)

**Comment by hakadao** [comment]
通過了終於
https://addons.mozilla.org/en-US/firefox/addon/bewlybewly/

**Comment by rainocean** [comment]
喜大普奔！！！！
