### ISSUE TITLE
[BUG] 使用亮色模式的情况下页面仍然会先加载深色模式然后才变成亮色模式

### ISSUE THREAD

**Issue by neotpravlennoye** [BewlyBewly/BewlyBewly#736]
### 环境

浏览器: Microsoft Edge
浏览器版本: 版本 125.0.2535.29 (正式版本) stable应用，beta频道 (64 位)
BewlyBewly 版本: 0.18.4

### 问题描述

windows系统和edge都用的暗色模式
bewlybewly用的亮色模式
不管是新开页面还是刷新页面，总是先显示为暗色模式，也就是背景是黑色的，已经显示出来的页面元素都是暗色的，零点几秒延迟后才变成亮色模式
https://imgur.com/a/UjOOjom

### 预期结果

既然用的是亮色模式那么应该直接渲染为亮色，而不是先暗色再亮色
另外这种纯黑色的暗色模式太伤眼了，建议使用深蓝深棕这类颜色来设计暗色模式😄

**Comment by zfbbb** [comment]
同样的问题  新开B站页面还是刷新页面，总是先显示为暗色模式，再跳为白色
win11和edge都为黑色模式
Microsoft Edge 版本：124.0.2478.80（正式版本）（64位）
BewlyBewly 版本: 0.18.4
