### ISSUE TITLE
unable to find utility "safari-web-extension-converter", not a developer tool or in PATH

### ISSUE THREAD

**Issue by Violetory** [BewlyBewly/BewlyBewly#738]
### 环境

Safari 17.4.1

### 问题描述

xcrun: error: unable to find utility "safari-web-extension-converter", not a developer tool or in PATH

**Comment by hakadao** [comment]
請先嘗試安裝xcode命令行工具再嘗試運行 xcrun 指令
https://www.freecodecamp.org/chinese/news/install-xcode-command-line-tools/

**Comment by hakadao** [comment]
能否提供一下你所輸入的指令？這回更好的幫助我們解答你的問題？
