### ISSUE TITLE
[功能建议] 关于顶栏的显示时机

### ISSUE THREAD

**Issue by mei-iem** [BewlyBewly/BewlyBewly#743]
如题，自由控制 仅在页面处于顶部时显示顶栏/始终显示/上滚时显示/始终不显示
![image](https://github.com/BewlyBewly/BewlyBewly/assets/97957593/38d2e3a3-f08c-492a-b395-75fe92d267fc)

**Comment by hakadao** [comment]
非常感謝你的意見，其實這種改動有點複雜，判斷的內容有點多，但是目前的處理已經達到了類似的效果，再添加相應功能的更加和配置會大大增加其他用戶的學習難度。也非常感謝你的提議，不過綜上所述，結合實際不太會考慮實現，不過非常感謝你創意 :)
