### ISSUE TITLE
[功能需求] 在右侧dock增加关注人直播的入口

### ISSUE THREAD

**Issue by neederhow** [BewlyBewly/BewlyBewly#745]
如题，虽然右上角有原版功能，但其它按钮都搬到dock了，希望直播也能搬过来。
原版也不好用，空间小，关注的人一多，每次都要滚好久找到比较感兴趣的up的直播间，完全没有整个屏幕来的舒服

**Comment by hakadao** [comment]
暫時沒有考慮，後期看需要實現
