### ISSUE TITLE
[BUG] 搜索历史无法清空或清空后又重复出现

### ISSUE THREAD

**Issue by jiang-yw** [BewlyBewly/BewlyBewly#749]
### 环境

浏览器: Chrome
浏览器版本: 124.0.6367.119
BewlyBewly 版本: 0.18.4

### 问题描述

主页或是视频页面搜索框搜索历史选择清空搜索历史后仍会出现时隔几年的历史搜索记录。
![image](https://github.com/BewlyBewly/BewlyBewly/assets/18746552/243226b9-e59e-4feb-913f-149813ae85a1)

### 预期结果

清空搜索历史后不再重复出现历史记录。

**Comment by hakadao** [comment]
i cant reprodce it

https://github.com/BewlyBewly/BewlyBewly/assets/33394391/26554321-a2c1-4f84-baeb-89b57239c99d

**Comment by jiang-yw** [comment]
我在最新版本重试了下，依然可以复现。

https://github.com/BewlyBewly/BewlyBewly/assets/18746552/198ed561-74be-47a1-94df-f10fd5bc03b3

**Comment by hakadao** [comment]
> 我在最新版本重试了下，依然可以复现。
> 
> 
> 
> https://github.com/BewlyBewly/BewlyBewly/assets/18746552/198ed561-74be-47a1-94df-f10fd5bc03b3
> 
> 

有没有和b站其他插件共用

**Comment by jiang-yw** [comment]
> > 我在最新版本重试了下，依然可以复现。
> > 
> >   
> >     
> >     
> > 
> >     2024-05-17.15-28-21.mp4
> 
> 有没有和b站其他插件共用

没有 开着的插件只有adblock plus

**Comment by hakadao** [comment]
> > > 我在最新版本重试了下，依然可以复现。
> > > ```
> > > 2024-05-17.15-28-21.mp4
> > > ```
> > 
> > 
> > 有没有和b站其他插件共用
> 
> 没有 开着的插件只有adblock plus

有使用油猴的那些腳本嗎？會不會是衝突了

**Comment by jiang-yw** [comment]
> > > > 我在最新版本重试了下，依然可以复现。
> > > > ```
> > > > 2024-05-17.15-28-21.mp4
> > > > ```
> > > 
> > > 
> > > 有没有和b站其他插件共用
> > 
> > 
> > 没有 开着的插件只有adblock plus
> 
> 有使用油猴的那些腳本嗎？會不會是衝突了

关掉了除了BewlyBewly所有插件 但是还还会复现
![image](https://github.com/BewlyBewly/BewlyBewly/assets/18746552/6e971b4d-9e70-47d7-a012-2d3c12140250)

**Comment by jiang-yw** [comment]
但是我清掉了B站的所有cookie 好像就不会复现了

**Comment by hakadao** [comment]
> 但是我清掉了B站的所有cookie 好像就不会复现了

之後如果沒有再次重現的話我先關閉issue了
