### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by ManyullynSword** [BewlyBewly/BewlyBewly#750]
### 环境

浏览器: Microsoft Edge
浏览器版本: Beata 125.0.2535.37
BewlyBewly 版本: 1.18.2~1.18.4

### 问题描述

只要在设置中设置主题色插件就会损坏

### 预期结果

不会损坏

**Comment by hakadao** [comment]
可以先用chrome web store 那邊的下載，那邊沒有問題，edge 問題討論可以移步到 #705
