### ISSUE TITLE
[BUG]更改背景会导致扩展被禁用

### ISSUE THREAD

**Issue by whystars** [BewlyBewly/BewlyBewly#753]
### 环境

浏览器: (Edge)
浏览器版本: (124.0.2478.97)
BewlyBewly 版本: (0.18.4)
扩展来自Github

### 问题描述

我在使用的时候发现，更改背景会导致扩展自动被禁用？？
而且没有任何办法解决，希望快点解决这个问题！！

**Comment by hakadao** [comment]
edge 下載專屬bug，在解決中，可以去chrome web store下載解決這個問題
後續討論可以移步到 #705 討論，謝謝
