### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jacky1120848060** [BewlyBewly/BewlyBewly#754]
### 环境

浏览器: Microsoft Edge
浏览器版本: 版本 126.0.2552.0 (正式版本) dev (64 位)
BewlyBewly 版本: (如 0.18.4)

### 问题描述

拖动dock内容顺序、自定义主题色 均导致插件自动推出且需要修复后重新使用

**Comment by hakadao** [comment]
edge 下載專屬bug，在解決中，可以去chrome web store下載解決這個問題
後續討論可以移步到 https://github.com/BewlyBewly/BewlyBewly/issues/705 討論，謝謝
