### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by KONGpro9** [BewlyBewly/BewlyBewly#758]
### 环境

浏览器: (Microsoft Edge)
浏览器版本: (124.0.2478.97 (正式版本) (64 位))
BewlyBewly 版本: (如 0.18.4)

### 问题描述

授权 BewlyBewly 使用 access key，扫完码之后刷新页面，扩展已损坏

**Comment by hakadao** [comment]
欢迎移步到 #705 汇总，这样有利于我们排查错误，谢谢
