### ISSUE TITLE
[BUG] Edge 扩展损坏已修复，但是导致了资源图片全部无法加载

### ISSUE THREAD

**Issue by SolitudeSun** [BewlyBewly/BewlyBewly#759]
### 环境

浏览器: Microsoft Edge
浏览器版本: 124.0.2478.97
BewlyBewly 版本: 0.18.5

### 问题描述

**使用的 Edge 浏览器安装的 Chrome 扩展，版本 0.18.5**
**扩展损坏的问题已经解决，但是导致了背景图片等路径下无法找到指定的资源**

![image](https://github.com/BewlyBewly/BewlyBewly/assets/101030922/ff90f7d7-7454-4fda-9e0a-11d962c54d71)
![image](https://github.com/BewlyBewly/BewlyBewly/assets/101030922/2c363f3a-ecef-4dab-bc41-e6c42255683d)

### 预期结果

**图片正常显示**

**Comment by hakadao** [comment]
現在 edge 上用 chrome web store 下載的 bewly 不會顯示損壞，只是圖片不出來

**Comment by SolitudeSun** [comment]
好



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月14日 01:51 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [BewlyBewly/BewlyBewly] [BUG] 修复 Edge 扩展损坏造成了资源图片全部无法加载 (Issue #759) |

現在 edge 上用 chrome web store 下載的 bewly 不會顯示損壞，只是圖片不出來
