### ISSUE TITLE
[BUG] 首页为空白页

### ISSUE THREAD

**Issue by z6m8n7ljw** [BewlyBewly/BewlyBewly#763]
### 环境

浏览器: Chrome
浏览器版本: 123.0.6312.107
BewlyBewly 版本: 0.18.5

![TinySnap-2024-05-13-21 59 14](https://github.com/BewlyBewly/BewlyBewly/assets/17857021/db7d5d1e-fd2b-4275-8ebc-bc5c017e50ec)
![TinySnap-2024-05-13-21 59 22](https://github.com/BewlyBewly/BewlyBewly/assets/17857021/74d538b6-60eb-45d4-afe0-bfe65a2c5f92)

### 问题描述

不启用 通用 - 使用原版 Bilibili 首页 的前提下，首页只是空白页。

### 预期结果

首页应为三列的推荐视频页。

**Comment by hakadao** [comment]
那是搜尋頁，請在這裏把首頁放回第一個。。。。
<img width="785" alt="image" src="https://github.com/BewlyBewly/BewlyBewly/assets/33394391/6d153c1e-cc19-42b8-a858-c3f821ae2edf">
