### ISSUE TITLE
性能问题：首页在新视频加载时会极其卡顿

### ISSUE THREAD

**Issue by d2913406181** [BewlyBewly/BewlyBewly#767]
### 环境

浏览器: Cent Browser
浏览器版本: 118.0.5993.159
BewlyBewly 版本: 0.18.8

### 问题描述

首页浏览途中在未加载视频加载时，会变得极其卡顿，加载完毕后回复正常

### 预期结果

正常加载视频，可以在视频加载途中流畅预览其他视频

**Comment by hakadao** [comment]
重複問題請移步到 #762
