### ISSUE TITLE
[Feature Request] 能否对首页推荐的视频卡片进行更多快捷操作以达到过滤的目的

### ISSUE THREAD

**Issue by neotpravlennoye** [BewlyBewly/BewlyBewly#769]
比如对某个单体视频进行屏蔽，该视频将不再出现在推荐里
比如对UP主进行屏蔽，该UP主的视频将不会再出现在推荐里
比如通过时长筛选，不符合筛选的视频将不会出现在推荐里

**Comment by hakadao** [comment]
#163 討論，需求已重複
