### ISSUE TITLE
[BUG]通知显示数量是实际的两倍

### ISSUE THREAD

**Issue by CyunNaam** [BewlyBewly/BewlyBewly#770]
### 环境

浏览器: Chrome
浏览器版本: 125.0.6422.41
BewlyBewly 版本: 0.18.5

### 问题描述

<img width="138" alt="image" src="https://github.com/BewlyBewly/BewlyBewly/assets/126946848/073a3cf1-1969-474b-b420-ae6f8ca1d648">

**Comment by AverilLuo** [comment]
+1

**Comment by ITManCHINA** [comment]
+1，且bewlybewly的版本为`0.18.8`也可以复现此问题

**Comment by hakadao** [comment]
b站接口返回內容換了，多了個 recv_reply, 下版本調整
<img width="720" alt="image" src="https://github.com/BewlyBewly/BewlyBewly/assets/33394391/0bc9a192-1381-486d-982f-b0a0aa52967e">
