### ISSUE TITLE
似乎是[BUG]加载很慢（几分钟）

### ISSUE THREAD

**Issue by availbleusername12121** [BewlyBewly/BewlyBewly#772]
### 环境

Edge 126.0.2566.1
bewlybewly版本：0.18.4

### 问题描述

已登录状况下要加载很久（大概几分钟）
![屏幕截图 2024-05-16 214746](https://github.com/BewlyBewly/BewlyBewly/assets/160390540/02c7b4c7-940c-49b9-ad5a-da0796f550ad)
不登录就很快

### 预期结果

迅速登录！

**Comment by hakadao** [comment]
這單純是網絡問題，我們無能為力
