### ISSUE TITLE
瀑布流视图的时候，没有不感兴趣的选项了，希望开发者看一下

### ISSUE THREAD

**Issue by XBSX** [BewlyBewly/BewlyBewly#773]
### 环境

浏览器:  edge
浏览器版本: 版本 124.0.2478.67 (正式版本) (arm64)
BewlyBewly 版本: 版本0.18.8

### 问题描述

瀑布流视图的时候，没有不感兴趣的选项了

### 预期结果

修复不感兴趣功能

**Comment by XBSX** [comment]
web算法的时候没有这个选项，app推荐算法的时候，显示请求错误

**Comment by XBSX** [comment]
![Uploading iShot_2024-05-18_21.29.54.png…]()

**Comment by hakadao** [comment]
> web算法的时候没有这个选项，app推荐算法的时候，显示请求错误

app 推介那邊需要先授權才可以正常使用不感興趣功能
<img width="975" alt="image" src="https://github.com/BewlyBewly/BewlyBewly/assets/33394391/0e501032-b8fa-4da6-974f-74922fe725d1">
另外web端的一直存在啊
<img width="293" alt="image" src="https://github.com/BewlyBewly/BewlyBewly/assets/33394391/63ddef59-fcce-4552-b900-4e38a0cbc28b">
