### ISSUE TITLE
[建议]首页推荐瀑布流增加一个手动刷新按钮和记忆瀑布流内容

### ISSUE THREAD

**Issue by XianYuDaXian** [BewlyBewly/BewlyBewly#774]
### 环境

浏览器: (如 Chrome)
浏览器版本: (如 123.0.6312.107)
BewlyBewly 版本: (如 0.16.2)

### 问题描述

现在首页推荐瀑布流是下滑然后无限刷新，但是电脑性能差的情况下瀑布流内容过多会造成卡顿，只能手动刷新页面获取新推荐。希望增加按钮直接刷新。另外就是当有的时候手滑刷新了首页，但是在那之前看到了感兴趣的视频。或者是标签页不活跃了切换回来的时候自动刷新导致视频被刷走了。希望可以记忆上次瀑布流，除非手动刷新或者手动滑动页面到底部出现新内容。效果类似这个脚本https://greasyfork.org/zh-CN/scripts/478516-bilibili%E6%8D%A2%E4%B8%80%E6%8D%A2-%E6%8D%A2%E5%9B%9E%E6%9D%A5

**Comment by XianYuDaXian** [comment]
才发现再次点击一下个性推荐就是刷新。那建议增加一个刷新图标更加直观，然后就是增加可以换回去的按钮，防止手滑错过视频

**Comment by hakadao** [comment]
瀑布流保存和只保留換一換那6個視頻不是同一個難度
