### ISSUE TITLE
[BUG] 无法正确显示登陆状态以及首页无法正确显示(空白) Unable to correctly display login status and home page cannot be displayed correctly (blank).

### ISSUE THREAD

**Issue by HHT0rro** [BewlyBewly/BewlyBewly#775]
### 环境

浏览器: Edge
浏览器版本: 125.0.2535.37 (正式版本)
BewlyBewly 版本: v0.18.8
windows版本: Windows 11 23H2 22635.3061

### 问题描述

无法正确显示登陆状态以及首页无法正确显示(空白页)
bug触发原因不详，出现后重装插件以及使用Edge修复功能均无效
![微信图片_20240519200052](https://github.com/BewlyBewly/BewlyBewly/assets/169252182/10f77eb6-dca1-470b-a887-6427ab0631cf)
![微信图片_20240519200058](https://github.com/BewlyBewly/BewlyBewly/assets/169252182/d28ba6a1-7ca7-431a-9209-02e7f5751276)
![微信图片_20240519200103](https://github.com/BewlyBewly/BewlyBewly/assets/169252182/8f0212fa-fe11-4e27-a7c3-c14c4133df1d)
![微信图片_20240519200107](https://github.com/BewlyBewly/BewlyBewly/assets/169252182/878b6a3c-585f-4c90-b98e-e457a010b2ae)
![微信图片_20240519200112](https://github.com/BewlyBewly/BewlyBewly/assets/169252182/a96890a6-343f-41e0-ad65-a54bd5217ed8)

**Comment by hakadao** [comment]
沒能重現, 是否與其他b站插件或油猴腳本衝突?

**Comment by HHT0rro** [comment]
> 沒能重現, 是否與其他b站插件或油猴腳本衝突?

您好，非常感谢您的回复 以下是我的插件列表
![微信图片_20240521170716](https://github.com/BewlyBewly/BewlyBewly/assets/169252182/e7ebad00-09ed-4b15-b1bd-fc2e8af323b3)
![微信图片_20240521170718](https://github.com/BewlyBewly/BewlyBewly/assets/169252182/ab2d370f-6e6d-4a7a-8b04-b46749af9c3b)

并且我在InPrivate模式中也出现了相同的情况（应该能排除插件或油猴脚本导致的冲突
![微信图片_20240521170906](https://github.com/BewlyBewly/BewlyBewly/assets/169252182/a55f9c5f-3d70-4321-9e37-46f313e10553)


我注意到在开启插件后控制台中日志输出有 白屏检测是否正常 {status: 'error', loop: 4, data: {_}}
![微信图片_20240521170825](https://github.com/BewlyBewly/BewlyBewly/assets/169252182/1fe17b7a-3174-4e39-88d3-74b2f54afbe0)
而关闭插件后恢复了“正常”：白屏检测是否正常{status: 'ok
![微信图片_20240521171020](https://github.com/BewlyBewly/BewlyBewly/assets/169252182/16b3aa8b-af3a-4a9c-bb32-10ca1beb83c0)

**Comment by hakadao** [comment]
`白屏检测是否正常` 是b站的腳本輸出的, 是否只有首頁有此問題? 其他頁面 (稍候觀看, 歷史, 收藏) 正常嗎?

**Comment by HHT0rro** [comment]
> 沒能重現, 是否與其他b站插件或油猴腳本衝突?

您好，并且我还注意到Edge浏览器提示插件出现了几个错误：
![微信图片_20240521171339](https://github.com/BewlyBewly/BewlyBewly/assets/169252182/94d23ffa-60f4-4ab4-8600-909184827420)
不清楚这是否是导致出现此bug的直接原因??

**Comment by hakadao** [comment]
> > 沒能重現, 是否與其他b站插件或油猴腳本衝突?
> 
> 您好，并且我还注意到Edge浏览器提示插件出现了几个错误： ![微信图片_20240521171339](https://private-user-images.githubusercontent.com/169252182/332361764-94d23ffa-60f4-4ab4-8600-909184827420.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODM4NTQsIm5iZiI6MTcxNjI4MzU1NCwicGF0aCI6Ii8xNjkyNTIxODIvMzMyMzYxNzY0LTk0ZDIzZmZhLTYwZjQtNGFiNC04NjAwLTkwOTE4NDgyNzQyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQwOTI1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTM1ZGQwNTFkZWEyZGVmY2YyZDhjZjA3NjA2NzU0ZGY0NWIyNjBlYTM5YjY3ZGRjM2E0MzFjZWRiNGI5YTFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gZIPB6Mla70MmHhnlQumYUgCYwlcl0AQOVRSPUeRnUU) 不清楚这是否是导致出现此bug的直接原因??

你是從哪裏下載的? 是 chrome web store 嗎, 還是自己下載 extensiton.zip 然後匯入的?
推介使用 chrome web store 下載

**Comment by JorenBai** [comment]
![image](https://github.com/BewlyBewly/BewlyBewly/assets/13309787/9c8e161b-e1cf-47eb-818c-92c2aee1c610)
问题类似，
Edge 版本 125.0.2535.51 (正式版本) (64 位)
BewlyBewly 版本0.18.8 来源 Edge 加载项商店

**Comment by hakadao** [comment]
現在還有出現此裏情況嗎? 如果沒有的話先 close, 有的話回覆我會重新 open

**Comment by z-ww447** [comment]
同樣問題，給完權現就好了

![image](https://github.com/BewlyBewly/BewlyBewly/assets/34766434/71088ccf-ba46-412f-a310-41babfe311e5)

**Comment by QianYI-Yan** [comment]
去谷歌的chorme下就正常了

> ![image](https://private-user-images.githubusercontent.com/13309787/332979341-9c8e161b-e1cf-47eb-818c-92c2aee1c610.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5ODk3ODIsIm5iZiI6MTcyNTk4OTQ4MiwicGF0aCI6Ii8xMzMwOTc4Ny8zMzI5NzkzNDEtOWM4ZTE2MWItZTFjZi00N2ViLTgxOGMtOTJjMmFlZTFjNjEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEwVDE3MzEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkZTZiMmVkYThlMTdjMTcxM2Q4Y2I1YTEzODQyNjk5ZTJlMDMxODU5NmZmMWZlYzg2NzQ4OGRlNDE1NjAyZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hp73KLYOErnEfPzHDgz5WEOAcGXDBFqma4VKkGy5bIs)问题类似， Edge 版本 125.0.2535.51 （正式版本） （64 位） BewlyBewly 版本0.18.8 来源 Edge 加载项商店
