### ISSUE TITLE
[BUG]今天edge更新过后 在bilibli主页上下滚动变得异常卡顿

### ISSUE THREAD

**Issue by Lockik** [BewlyBewly/BewlyBewly#781]
### 环境

![Clip_2024-05-21_13-43-51](https://github.com/BewlyBewly/BewlyBewly/assets/118150761/c0a7a87e-6892-4489-a750-383866fa59f4)
edge扩展商店里面的插件版本为18.8 贼卡
下了新版的18.9之后 卡顿有所缓解 但还是卡

### 问题描述

edge扩展商店里面的插件版本为18.8 贼卡
下了新版的18.9之后 卡顿有所缓解 但还是卡

**Comment by hakadao** [comment]
重複問題去 #760 討論
