### ISSUE TITLE
效能問題: v0.18.10 还是一卡一卡的

### ISSUE THREAD

**Issue by fgr178707** [BewlyBewly/BewlyBewly#783]
v0.18.10 还是一卡一卡的 但是比上一个版本好一点

https://github.com/BewlyBewly/BewlyBewly/assets/109357981/e299701d-fbc7-42fe-912f-53f391f76056

_Originally posted by @fgr178707 in https://github.com/BewlyBewly/BewlyBewly/issues/762#issuecomment-2123609933_

**Comment by hakadao** [comment]
關閉壁紙模糊效果就會好很多

**Comment by fgr178707** [comment]
> 關閉壁紙模糊效果就會好很多
> 設定那裏也說了會影響效能這個功能

问题是关了他也卡呀

**Comment by hakadao** [comment]
> > 關閉壁紙模糊效果就會好很多
> 
> > 設定那裏也說了會影響效能這個功能
> 
> 
> 
> 问题是关了他也卡呀

嘗試不要設定背景圖片和關閉毛玻璃效果

**Comment by fgr178707** [comment]
> 剩下的問題暫時無解了, 正常不用核顯的話應該不會那麼卡

我也纳闷 我之前用的0.18.9还是.8一点事没有 自从升级到了.10，就有这个问题了

**Comment by fgr178707** [comment]
> 我把 v0.18.4 - v0.18.9 期間的修改都看過， 也不太清楚爲何會這樣

升级完再删除 并降级也有这个问题
我好像就首次安装的时候没有这个问题

**Comment by hakadao** [comment]
> 我也是这样。看到新版本立马更新了一下。上个版本没有使用 切回b站原版的，这个版本好一些 但还是有一点卡卡的。

目前暫時無解了 = =, 看看有沒有其他人能幫忙改

**Comment by DarlingLaoxiansheng** [comment]
我从下载到现在就没更新过 今天发现变卡了 应该和更新没关系

**Comment by DarlingLaoxiansheng** [comment]
> 我从下载到现在就没更新过 今天发现变卡了 应该和更新没关系

一直用的18.8

**Comment by hakadao** [comment]
不知道你有沒看過原碼，我現在就是這麼做的

**Comment by YinLiaoQwQ** [comment]
@hakadao 似乎卡顿是由新视频推荐导致的卡顿，只要滑动到底部，一开始加载新推荐就开始卡顿了

**Comment by YinLiaoQwQ** [comment]
又测试了一下，只要预览视频在播放，滑动时也会卡顿  :(  奇怪的问题

**Comment by HumanMus1c** [comment]
0.18.9开始性能非常差。之前就没有这么卡。请教一下如何降级。

**Comment by fgr178707** [comment]
> 0.18.9开始性能非常差。之前就没有这么卡。请教一下如何降级。

降级好像也有这个问题
降级:先导出配置文件 下载低版本 压缩包  浏览器插件列表删除高版本 开启开发者模式，然后将低版本压缩包拖入即可

**Comment by flashorsink** [comment]
刚刚装了最新的也是卡，倒是一直用着的0.16.4很丝滑

**Comment by fgr178707** [comment]
> 刚刚装了最新的也是卡，倒是一直用着的0.16.4很丝滑

0.16.4？ 
不应该是0.18.4吗？
你这版本也太老了
等我明天试试

**Comment by flashorsink** [comment]
> > 刚刚装了最新的也是卡，倒是一直用着的0.16.4很丝滑
> 
> 0.16.4？ 不应该是0.18.4吗？ 你这版本也太老了 等我明天试试

因为一直安装包手动安装的，就很久没更新了，用着也没啥毛病

**Comment by fgr178707** [comment]
> > > 刚刚装了最新的也是卡，倒是一直用着的0.16.4很丝滑
> > 
> > 
> > 0.16.4？ 不应该是0.18.4吗？ 你这版本也太老了 等我明天试试
> 
> 因为一直安装包手动安装的，就很久没更新了，用着也没啥毛病

我刚刚试了一下，0.16.4还真不卡了 就是图片加载慢点

**Comment by fgr178707** [comment]
临时解决方法 下载V0.16.4 版本
[下载地址](https://github.com/BewlyBewly/BewlyBewly/releases/tag/v0.16.4)
[直连地址](https://github.com/BewlyBewly/BewlyBewly/releases/download/v0.16.4/extension.zip)

**Comment by hakadao** [comment]
經過我測試，目前最後一個不卡的版本是 v0.18.4，然後目前在研究 [v0.18.4 ~ v0.18.5 之間的修改](https://github.com/BewlyBewly/BewlyBewly/compare/v0.18.4...v0.18.5) 我真沒有頭緒可能需要其他人幫忙
下載地址：[v0.18.4.zip](https://github.com/BewlyBewly/BewlyBewly/files/15473544/v0.18.4.zip)

**Comment by fgr178707** [comment]
> 經過我測試，目前最後一個不卡的版本是 v0.18.4，然後目前在研究 [v0.18.4 ~ v0.18.5 之間的修改](https://github.com/BewlyBewly/BewlyBewly/compare/v0.18.4...v0.18.5) 我真沒有頭緒可能需要其他人幫忙 下載地址：[v0.18.4.zip](https://github.com/BewlyBewly/BewlyBewly/files/15473544/v0.18.4.zip)
> 
> 另外補充一點變卡不是故意做得那麼卡的，這段時間商店評價和看到的評論說得好像是我故意只做新功能不注重卡頓調整，如果看看過往的 issue 的話新功能現在更多是實現用戶的想法不是實現我希望做到的效果，之前測出來測到半夜2、3點我明天還要上班我現在也只是工作抽出的時間做的 我也只能盡量做好，插件本身也不是強迫人用的性質，在這裏說說最近我想說的......

不要搭理他 世上不可能有完美的 都是在不知不觉中插入了一个小小的bug

**Comment by fgr178707** [comment]
插件版本更新 v0.19.0
https://github.com/BewlyBewly/BewlyBewly/releases/tag/v0.19.0
