### ISSUE TITLE
[BUG]“稍后再看”页面的加载时间过长

### ISSUE THREAD

**Issue by rich-purnell** [BewlyBewly/BewlyBewly#784]
### 环境

浏览器: Microsoft Edge
浏览器版本: 125.0.2535.51 (正式版本) (64 位)
BewlyBewly 版本: v0.18.10

### 问题描述

“稍后再看”页面的加载时间过长，加载中途浏览器弹出页面无响应提示。可能与我的“稍后再看”列表中的视频数量过大有关。

![image](https://github.com/BewlyBewly/BewlyBewly/assets/17319140/1215c554-0631-425e-a64e-2d46942adfe1)d

### 预期结果

能够快速加载。

**Comment by DD224ever** [comment]
我也是，卡住不动了。[](ur
![image_73](https://github.com/BewlyBewly/BewlyBewly/assets/62013258/25f8039c-362a-40d0-b824-443542e0fc08)

**Comment by DD224ever** [comment]
![Uploading image_73.png…]()
