### ISSUE TITLE
[enhancement]首頁標籤欄調整

### ISSUE THREAD

**Issue by DD224ever** [BewlyBewly/BewlyBewly#785]
### 环境

0.18.10

### 问题描述

稍后再看卡住的BUG好像有人提了，那我提两个小建议：

1.图一图二的夜间模式切换按钮和首页样式按钮希望可以给个隐藏的选项，因为这两个按钮切好自己想要的样式之后基本用不到了，特别是那个切换样式的按钮，加个类似dock栏的自动贴边隐藏也行。

2.图三建议改成统一的两个字，清爽简洁些，如：关注、推荐、剧集、热门、排行；其实我希望这一栏也能自动隐藏。。。

![image_76](https://github.com/BewlyBewly/BewlyBewly/assets/62013258/694bef60-b285-420e-84c3-4ab57a8f9558)
![image_75](https://github.com/BewlyBewly/BewlyBewly/assets/62013258/4a56f46e-81bc-4c12-8941-1e1b347607ff)
![image_74](https://github.com/BewlyBewly/BewlyBewly/assets/62013258/3f6b62d0-fe81-4477-8177-0e4a41ee5995)

**Comment by DD224ever** [comment]
我不会改议题的标签。。。还有就是好像这种改B站首页的插件都会吞关注up的视频，就是up更新的视频不会显示在正在关注这一页（不是那种很短的动态视频），

**Comment by hakadao** [comment]
2. 我不建議一定要兩個字描述，以後如果出現不得不要三個字的話很難排版

**Comment by hakadao** [comment]
在 v0.19.0 這麼設置就可以實現了
<img width="991" alt="image" src="https://github.com/BewlyBewly/BewlyBewly/assets/33394391/bef1f429-ebd7-4846-8f38-5670dea5dd04">
<img width="967" alt="image" src="https://github.com/BewlyBewly/BewlyBewly/assets/33394391/f4fc1ddc-fde9-4036-8b79-933ec25ab06c">
