### ISSUE TITLE
和浮图秀冲突？或者说用了之后浮图秀就失效了

### ISSUE THREAD

**Issue by lhj5426** [BewlyBewly/BewlyBewly#788]
### 环境

浏览器: (如 Chrome)
浏览器版本: (如 123.0.6312.107)
BewlyBewly 版本: (如 0.18.9)

### 问题描述

没有使用扩展的时候首页
鼠标停留在 视频封面上
![image](https://github.com/BewlyBewly/BewlyBewly/assets/30548000/33d9b0e3-6725-485a-bdd3-67d7575c8b12)
浮图秀可以显示封面图大图
![image](https://github.com/BewlyBewly/BewlyBewly/assets/30548000/cf802a23-93a9-4f5f-8cdf-d09024f5f039)
使用了 大佬的扩展之后浮图秀就失效了 鼠标放在视频上就不会显示大图了

### 预期结果

希望可以 显示封面大图

**Comment by lhj5426** [comment]
https://github.com/BewlyBewly/BewlyBewly/assets/30548000/c0cb3ae3-9f95-47cb-833e-43e6d5ef8d67

 视频

**Comment by hyoban** [comment]
首页是插件全新写的页面，不和其它插件兼容，需要和其它插件一起使用的话在设置里开启原版 b 站首页
