### ISSUE TITLE
是否可以加入屏蔽“UP主的推荐”功能？

### ISSUE THREAD

**Issue by ThisDumpling** [BewlyBewly/BewlyBewly#791]
这种动态似乎都带有 `<div class="bili-dyn-card-goods">` 的标签，是否可以考虑加入屏蔽？

**Comment by hakadao** [comment]
對b站調整的功能暫時不打算開發
不過你可以試試這個腳本：https://greasyfork.org/zh-CN/scripts/479861-bilibili-%E9%A1%B5%E9%9D%A2%E5%87%80%E5%8C%96%E5%A4%A7%E5%B8%88
