### ISSUE TITLE
请求新增功能：用户可以调节选中文本时文本的颜色和底色的填充色

### ISSUE THREAD

**Issue by 1729Chen** [BewlyBewly/BewlyBewly#792]
我们选中一段文本时，他会以白字蓝底的形式呈现
![image](https://github.com/BewlyBewly/BewlyBewly/assets/108348883/4f7ae93c-75ce-4959-84fa-2782c0047f53)
![image](https://github.com/BewlyBewly/BewlyBewly/assets/108348883/11f0219b-ac9c-4dec-ac26-b3347cb37379)

但在使用BewlyBewly插件后，复制一段文本时只有底色填充色变为了浅灰色（RGB(54,54,60)），这样使得选中文本时很难看出选中了哪些文本（尤其开了暗色模式）
![image](https://github.com/BewlyBewly/BewlyBewly/assets/108348883/f5ec4d35-806d-4da4-be43-bfd78171024c)
![image](https://github.com/BewlyBewly/BewlyBewly/assets/108348883/418e0727-658e-4fa3-a633-b21eca4db0c1)

希望可以新增一个功能，可以用用户调节选中文本时文本的颜色和底色的填充色。

**Comment by hakadao** [comment]
我覺得沒有必要，灰色最多把透明度加大
我不太喜歡藍底白字

**Comment by 1729Chen** [comment]
透明度已经调节为100%，但是仍觉得选中文本后给的反馈不是那么明显

![image](https://github.com/BewlyBewly/BewlyBewly/assets/108348883/327be248-3dbd-4c62-963f-9bb3c31a4738)

**Comment by hakadao** [comment]
之後設定外觀最下可以改css
![image](https://github.com/user-attachments/assets/37df94fa-7af5-4e66-bbcd-4aba8e1a9b42)
