### ISSUE TITLE
[BUG]网址图标缺失？

### ISSUE THREAD

**Issue by CyunNaam** [BewlyBewly/BewlyBewly#800]
### 环境

浏览器:chrome
浏览器版本: 125.0.6422.142
BewlyBewly 版本: 0.19.1

### 问题描述

<img width="226" alt="image" src="https://github.com/BewlyBewly/BewlyBewly/assets/126946848/ca8d1e4f-f6a1-49bd-a05f-dc9afb299aef">

**Comment by hakadao** [comment]
停用插件之後問題還存在, 這是b站的bug
