### ISSUE TITLE
滚动首页时会卡顿

### ISSUE THREAD

**Issue by K05A4B** [BewlyBewly/BewlyBewly#802]
### 环境

浏览器: Edge
浏览器版本: 125.0.2535.79
BewlyBewly 版本: v0.18.10
GPU: RTX 3050 Laptop GPU (独显直连)

### 问题描述

首页滚动时UI会卡顿，特别是加载资源的时候

**Comment by hakadao** [comment]
提問時有注意到edge版本會因爲 edge addons 因審核問題導致更新速度慢嗎？
版本 v0.19.0 做已修正，推介從 chrome web store 下載
