### ISSUE TITLE
希望能在搜索页也开启“在视频卡片上显示视频控制栏”

### ISSUE THREAD

**Issue by NianBroken** [BewlyBewly/BewlyBewly#804]
当开启“视频预览功能”和“在视频卡片上显示视频控制栏”后，在“`https://www.bilibili.com/`”页面当鼠标悬停在视频卡片上时，会出现进度条、声音、下载等功能。

但如果Url在“`https://search.bilibili.com/all?keyword=xxxxx`”却没有“在视频卡片上显示视频控制栏”功能。

因此，希望能够在搜索页也开启“在视频卡片上显示视频控制栏”

**Comment by hakadao** [comment]
B站原本頁面不打算改動
