### ISSUE TITLE
希望能在视频播放页增加“下载视频”的功能

### ISSUE THREAD

**Issue by NianBroken** [BewlyBewly/BewlyBewly#805]
当开启“视频预览功能”和“在视频卡片上显示视频控制栏”后，在“`https://www.bilibili.com/`”页面当鼠标悬停在视频卡片上时，会出现进下载等功能。

因此，希望能够实现当Url在“`https://www.bilibili.com/video/BVxxxxx`”时也能实现视频下载功能。

**Comment by hakadao** [comment]
acghelper bilibili evolved 可以實現此功能甚至更好
