### ISSUE TITLE
侧边栏按钮需要自定义或调整排序优先级

### ISSUE THREAD

**Issue by charlil** [BewlyBewly/BewlyBewly#807]
### 环境

浏览器: (如 Chrome)
浏览器版本: (如 123.0.6312.107)
BewlyBewly 版本: (如 0.18.9)

### 问题描述

这次更新侧边栏增加的两个按钮 【搜索】和【番剧】 并且优先级再优先级在【收藏】【观看历史】【稍后观看】之上并不合理。
【搜索】框屏幕中上方是存在的并且原版b站【搜索】框也在中上方，大部分的用户也会习惯于在正中间搜索，所以没必要排序优先级那么高。（如果可以自定义按钮位置那就太好了）。

【番剧】按钮只是我个人从不看番剧所以排序优先级感觉有些别扭。

本来侧边栏按钮只有4个看着很简洁，一次更新加了1/2就会显得比较杂乱。**考虑到b站原界面有居多的按钮相信后续还会有用户让作者增加按钮，不如直接侧边栏按钮自定义**。

**Comment by charlil** [comment]
谢谢帮忙修改标签，我还在找修改标签的步骤qaq

**Comment by hakadao** [comment]
在常規 -> Dock 内容调整 可以實現對頁面的自定義或排序優先級
<img width="1077" alt="image" src="https://github.com/BewlyBewly/BewlyBewly/assets/33394391/70dcc289-3af6-4dfd-be36-a24374315db8">

**Comment by charlil** [comment]
感谢
