### ISSUE TITLE
[BUG]Edge插件首页无法打开视频页及视频页进度条无法拖动

### ISSUE THREAD

**Issue by clintduu** [BewlyBewly/BewlyBewly#812]
### 环境

浏览器: Microsoft Edge
浏览器版本: 125.0.2535.79 (正式版本) (64 位)
BewlyBewly 版本: 0.18.10
CPU: Intel i5-12100f
显卡: Intel Arc A750
OS: Windows11 23H2

### 问题描述

1. 首页无法打开视频页，但可以打开up主页，在其他页面可以打开视频页；
2. 视频页进度条无法拖动；
3. 鼠标在视频画面里不可见（这也许是一种设计，但能否增加鼠标隐藏延迟或增加鼠标隐藏选择开关？）

https://github.com/BewlyBewly/BewlyBewly/assets/52618023/38bc648b-9e5f-47fb-bd89-7b6a29077524

**Comment by hakadao** [comment]
edge 版本受審核原因遲遲不能更新，最新版本是 v0.19.2 在錯誤模板時也多次強調 edge 商店審核速度慢問題了
