### ISSUE TITLE
[BUG] 主页app推荐模式没有内容，伴随控制台报错，已多次重新获取accesskey

### ISSUE THREAD

**Issue by akira0245** [BewlyBewly/BewlyBewly#813]
### 环境

浏览器: Chrome
浏览器版本: 125.0.6422.113
BewlyBewly 版本: BewlyBewly [v0.19.2]

### 问题描述

主页app推荐模式没有内容，已多次重新获取accesskey，网页推荐模式正常显示，app推荐模式一片空白
打开控制台有报错

![image](https://github.com/BewlyBewly/BewlyBewly/assets/33274390/2051231f-379a-47f8-86c3-149f4457267d)

![image](https://github.com/BewlyBewly/BewlyBewly/assets/33274390/101bd8fb-6f4a-4e73-98c4-1bba89d8461a)
![image](https://github.com/BewlyBewly/BewlyBewly/assets/33274390/70d5a6dc-6df8-42f0-8571-e498834bca61)

**Comment by hakadao** [comment]
刷新過頁面還是這樣嗎

**Comment by akira0245** [comment]
是的 好几天了一直都是这样 刷新过 重启过浏览器和电脑了

**Comment by hakadao** [comment]
> 是的 好几天了一直都是这样 刷新过 重启过浏览器和电脑了

是在 chrome web store 商店下的嗎

**Comment by akira0245** [comment]
> > 是的 好几天了一直都是这样 刷新过 重启过浏览器和电脑了
> 
> 是在 chrome web store 商店下的嗎

是的

**Comment by akira0245** [comment]
试了开无痕模式只启用bewlybewly也还是这样 更奇怪的是打开无痕模式右上角依然在显示我的账号跟头像…… 点击头像才跳转到登录页面，实际上是没有登录状态的
![image](https://github.com/BewlyBewly/BewlyBewly/assets/33274390/4baea127-2639-4f28-bf34-1cc54ad2958f)

**Comment by LQZ100** [comment]
请问有解决这个问题吗，目前好像我也遇到了这个问题

**Comment by LQZ100** [comment]
很奇怪，开了VPN切换全局模式换了IP之后又恢复正常了，直连又不行，这个插件会被ban IP的吗？

**Comment by akira0245** [comment]
> 请问有解决这个问题吗，目前好像我也遇到了这个问题

没有解决

**Comment by hakadao** [comment]
有使用其他b站擴展或腳本嗎

**Comment by yoke686** [comment]
我也一样的问题

**Comment by hinlong** [comment]
firefox也有这个问题，firefox版本115.13.0esr

**Comment by hakadao** [comment]
換瀏覽器還有這個問題嗎?

**Comment by LQZ100** [comment]
> 換瀏覽器還有這個問題嗎?

这个问题貌似是前段时间B站服务器出问题的锅，后面就好了

**Comment by akira0245** [comment]
啊？不是？我没好啊？？？

**Comment by akira0245** [comment]
![image](https://github.com/user-attachments/assets/2fb2729d-06e3-4b6f-a050-edd6a08b49c8)
就刚刚还是这样

**Comment by akira0245** [comment]
能reopen一下吗 没有解决

**Comment by LQZ100** [comment]
> ![image](https://private-user-images.githubusercontent.com/33274390/348760157-2fb2729d-06e3-4b6f-a050-edd6a08b49c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNTc0MjAsIm5iZiI6MTcyMTA1NzEyMCwicGF0aCI6Ii8zMzI3NDM5MC8zNDg3NjAxNTctMmZiMjcyOWQtMDZlMy00YjZmLWEwNTAtZWRkNmEwOGI0OWM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDE1MjUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyZjQ4MTk0OWI1MWNiODRjZGU4OGM5MTZlZTA5ZTUzOTE3NTg0M2NiNjkwOWNlMWMzYzZmZjU0ZTk5MzA4ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DF1wP-1lpxfulv0DkzMNjvBlL4A9HSsOT5C3vGe1NbI) 就刚刚还是这样 @LQZ100

你试试不要开App推送，用回web推送，然后把浏览器所有的脚本都关了，把电脑的代理关了，看看能不能行

**Comment by LQZ100** [comment]
> ![image](https://private-user-images.githubusercontent.com/33274390/348760157-2fb2729d-06e3-4b6f-a050-edd6a08b49c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNTc0MjAsIm5iZiI6MTcyMTA1NzEyMCwicGF0aCI6Ii8zMzI3NDM5MC8zNDg3NjAxNTctMmZiMjcyOWQtMDZlMy00YjZmLWEwNTAtZWRkNmEwOGI0OWM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDE1MjUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyZjQ4MTk0OWI1MWNiODRjZGU4OGM5MTZlZTA5ZTUzOTE3NTg0M2NiNjkwOWNlMWMzYzZmZjU0ZTk5MzA4ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DF1wP-1lpxfulv0DkzMNjvBlL4A9HSsOT5C3vGe1NbI) 就刚刚还是这样 @LQZ100

![image](https://github.com/user-attachments/assets/c915e3d7-24ac-47c8-9ff5-8d451c270005)
我这边好像测试的是可以的，而且出问题好像也是前段时间B站服务器的那段时间

**Comment by akira0245** [comment]
刚刚把全部插件都关了一下发现是另一个扩展[Privacy Badger](https://chromewebstore.google.com/detail/%E9%9A%90%E7%A7%81%E7%8D%BE/pkehgijcmpdhfbdbbnkijodmdjhbjlgp)引起的问题 

之前为了排除其它扩展的原因已经在这个插件设置里设置了排除B站，但是似乎就算在它设置里排除了B站，只要这个插件是启用状态就会引发问题。
之后会去那个扩展的仓库反映一下😂 这边可以关掉了
