### ISSUE TITLE
刷新按钮能不能一致保持，而不是下拉之后就变成回到顶部了

### ISSUE THREAD

**Issue by lalalallu** [BewlyBewly/BewlyBewly#815]
### Discussed in https://github.com/BewlyBewly/BewlyBewly/discussions/814 <div type='discussions-op-text'> <sup>Originally posted by **lalalallu** 2024年6月4日</sup> 刷新按钮能不能一致保持，而不是下拉之后就变成回到顶部了</div>

**Comment by hakadao** [comment]
我覺得沒有必要多佔用一個位置
