### ISSUE TITLE
[BUG]请问在关注旁边的灰色按钮是什么啊，能够去掉吗

### ISSUE THREAD

**Issue by MADAO-NW** [BewlyBewly/BewlyBewly#819]
### 环境

浏览器: (如 Chrome)
浏览器版本: (如 123.0.6312.107)
BewlyBewly 版本: (如 0.18.9)

### 问题描述

edge浏览器使用，
![SnipasteSnipaste_2024-06-07_21-03-37](https://github.com/BewlyBewly/BewlyBewly/assets/81545756/a5e81e99-be6d-4366-b12c-bb168095dba0)

**Comment by BecherYes** [comment]
你看看有没有装了什么插件或者脚本里面包含了去除充电的功能，我有个Make BiliBili Great Again脚本就有，把相应的代码注释掉就好了

**Comment by hakadao** [comment]
能否給出視頻連結方便排查一下？

**Comment by hakadao** [comment]
如果沒有重現和回應的話先關閉了
