### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xiaobeioo** [BewlyBewly/BewlyBewly#820]
### 环境

浏览器: Edge
浏览器版本: 125.0.2535.85
BewlyBewly 版本: 0.19.3

### 问题描述

在视频页滚动页面查看评论时，会有掉帧。但是F12调用性能测试录制时，页面却不掉帧了。
关闭插件使用原版B站也不掉帧，希望能排查出是哪些控件引起的性能问题。

**Comment by xiaobeioo** [comment]
屏幕为高刷屏。猜测会不会有控件默认用60帧进行绘制，导致在高刷屏上看起来掉帧。

**Comment by hakadao** [comment]
沒有其他調整，另外標題下次能否詳細描述？
