### ISSUE TITLE
[BUG] 首页中 Vimium 无法通过(udjk)按键触发页面滚动

### ISSUE THREAD

**Issue by kfeng0806** [BewlyBewly/BewlyBewly#823]
### 环境

浏览器: Chrome
浏览器版本: 125.0.6422.142
BewlyBewly 版本: 0.19.3

### 问题描述

使用`BewlyBewly`后，在Bilibili首页时
[Vimium](https://chromewebstore.google.com/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb) 拓展下的 <kbd>u</kbd> <kbd>d</kbd> <kbd>j</kbd> <kbd>k</kbd> 键位无法正常上下滚动页面

### 预期结果

使用 [Vimium](https://chromewebstore.google.com/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb) 拓展时，<kbd>u</kbd> <kbd>d</kbd> <kbd>j</kbd> <kbd>k</kbd> 在首页中应该可以正常操作页面上下滚动

**Comment by hakadao** [comment]
目前 bewlybewly 是透過重寫整個b站頁面實現的，不知 vimium 是否因為無法監測到b站被改動後導致原本的鍵位失效，這可能要靠其他人幫忙
我們暫時沒有辦法處理
