### ISSUE TITLE
功能需求:将返回顶部按钮移到右侧

### ISSUE THREAD

**Issue by NEKOice** [BewlyBewly/BewlyBewly#825]
### 环境

edge: 125.0.2535.92
版本0.19.0

### 问题描述

<img width="171" alt="PixPin_2024-06-11_08-35-36" src="https://github.com/BewlyBewly/BewlyBewly/assets/75099085/b6584aa1-0110-4188-a8b4-0755efc8323b">

**Comment by hakadao** [comment]
0.19.3已經實現，在dock設定那邊
