### ISSUE TITLE
[BUG] 视频无法打开

### ISSUE THREAD

**Issue by yiobai** [BewlyBewly/BewlyBewly#828]
### 环境

浏览器: (Edge)
浏览器版本: (125.0.2535.92)
BewlyBewly 版本: (0.19.3)

### 问题描述

视频卡片打不开，跳转不到视频页面，只有UP头像和名字能点击并跳转，但能在控制台看到视频卡片是超链接的格式。

**Comment by hakadao** [comment]
不能重現，能否有影片提供出問題的過程

**Comment by yiobai** [comment]
好的，一会上传

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by yiobai** [comment]
https://github.com/BewlyBewly/BewlyBewly/assets/82246026/350b8274-5804-43f7-b768-9cd197e8079f

**Comment by yiobai** [comment]
> 不能重現，能否有影片提供出問題的過程 不能重现，能否有影片提供出问题的过程

https://github.com/BewlyBewly/BewlyBewly/assets/82246026/73da099b-1114-43be-a7ef-b6002a54c28a

**Comment by hakadao** [comment]
我不理解，為何不點擊視頻封面進入？

**Comment by yiobai** [comment]
> 我不理解，為何不點擊視頻封面進入？

点了封面（文字），都没办法打开，你能看到点击特效都出来了（背景变成半透明）

**Comment by yiobai** [comment]
> 我不理解，為何不點擊視頻封面進入？ 能否列出一下使用b站的腳本或擴展

点了封面（文字），都没办法打开，你能看到点击特效都出来了（背景有变化）

**Comment by yiobai** [comment]
> 我不理解，為何不點擊視頻封面進入？ 能否列出一下使用b站的腳本或擴展


https://github.com/BewlyBewly/BewlyBewly/assets/82246026/fe5b1552-87d5-4e1b-81e9-e5c3e0d42f6b

**Comment by yiobai** [comment]
![858537dc35530d3345f6bcd249238985](https://github.com/BewlyBewly/BewlyBewly/assets/82246026/b41a51e8-7941-4c0e-ab88-aaec141f73eb)
![a38c63f00afba3c4cc3f92ace8e9a1e2](https://github.com/BewlyBewly/BewlyBewly/assets/82246026/6a1ac77e-8516-4ffe-89b3-605d7e57f728)
![4ee15ee34639f6d1ffa5778819e328fd](https://github.com/BewlyBewly/BewlyBewly/assets/82246026/b4104d63-5334-4eca-97a1-31aeba867eec)
![8f0e093dd8700e5f480f0f1143358934](https://github.com/BewlyBewly/BewlyBewly/assets/82246026/a4985f5a-ee6f-453a-aa52-b652088fe13b)

![a356dd2e1c09e41e654c5012158bb210](https://github.com/BewlyBewly/BewlyBewly/assets/82246026/ce9b365f-fd15-4141-940a-b6cc2f8e405b)

**Comment by yiobai** [comment]
这些脚本删除或是关闭，还是打不开视频，我不清楚是不是扩展的问题，但我关闭相关的扩展并不能改变什么

**Comment by hakadao** [comment]
https://github.com/BewlyBewly/BewlyBewly/assets/33394391/77c1fc96-7d0f-4522-8fad-86a0d52f78c4
