### ISSUE TITLE
如何屏蔽通知中的系统通知？

### ISSUE THREAD

**Issue by isPoto** [BewlyBewly/BewlyBewly#830]
### 环境

浏览器: (如 Chrome)
浏览器版本: (如 123.0.6312.107)
BewlyBewly 版本: (如 0.18.9)

### 问题描述

通知的系统通知经常发些活动的广告，很烦人。我想屏蔽掉系统通知

**Comment by hakadao** [comment]
通知獲取是直接用b站的, b站這裏有對通知設置配置
其他如果b站在系統通知裏面發廣告的話我們處理不了, 因爲系統通知有時是收到充電和舉報成功, 會員購預約到貨那些
https://message.bilibili.com/#/config
