### ISSUE TITLE
未登录情况下, 首页个性推荐显示内容问题

### ISSUE THREAD

**Issue by MidnightCrowing** [BewlyBewly/BewlyBewly#836]
### 环境

浏览器: Chrome
浏览器版本: 126.0.6478.57
BewlyBewly 版本: 0.19.3

### 问题描述

![PixPin_2024-06-13_15-16-07](https://github.com/BewlyBewly/BewlyBewly/assets/110297461/77e5000f-87b5-46c6-bf78-956d753eaaa0)
这个地方应该改成登录界面吗? 它这个视频不登录情况下应该加载不出来吧🤔

### 预期结果

![PixPin_2024-06-13_15-28-06](https://github.com/BewlyBewly/BewlyBewly/assets/110297461/e43c7245-45d9-4184-a77d-0e5d79c654f0)
像这种

**Comment by hakadao** [comment]
但是搖搖領先的b站web端推介接口不登入時是有時可以取得數據有時又不行的, app端推介永遠可以取得數據
