### ISSUE TITLE
暗色模式下视频页面上UP主名字悬停时背景颜色变化

### ISSUE THREAD

**Issue by MidnightCrowing** [BewlyBewly/BewlyBewly#847]
### 环境

浏览器: Chrome
浏览器版本: 126.0.6478.57
BewlyBewly 版本: 0.19.8

### 问题描述

![PixPin_2024-06-18_18-47-44](https://github.com/BewlyBewly/BewlyBewly/assets/110297461/d64cc1c5-c322-43bd-b8ca-86ef57b07de6)
这个算是bug吗? 问题找到了, 要修吗?

**Comment by hakadao** [comment]
这个是不是b站原版就这样的

**Comment by MidnightCrowing** [comment]
b站原版是用了一个遮罩来实现悬停时字体变淡的效果, 但b站原版是浅色, 改成暗色之后这个遮罩太明显了, 
我的想法是直接用字体透明度实现, 把这个遮罩隐藏了

**Comment by hakadao** [comment]
> > 这个是不是b站原版就这样的
> 
> 
> 
> b站原版是用了一个遮罩来实现悬停时字体变淡的效果, 但b站原版是浅色, 改成暗色之后这个遮罩太明显了, 
> 
> 我的想法是直接用字体透明度实现, 把这个遮罩隐藏了

可以，就這樣吧
