### ISSUE TITLE
EDGE版本插件无法从扩展商店获取

### ISSUE THREAD

**Issue by xianhongtao** [BewlyBewly/BewlyBewly#852]
### 环境

浏览器: EDGE
浏览器版本: 126.0.2592.61 (正式版本) (64 位)
BewlyBewly 版本: 无法安装

### 问题描述

原https://microsoftedge.microsoft.com/addons/detail/bewlybewly/kceadhehfjdiakpiphpjgolbgehjdmja?hl=zh-CN现在已无法访问

**Comment by hakadao** [comment]
這是一個新版本的特性，不是bug
![image](https://github.com/BewlyBewly/BewlyBewly/assets/33394391/5dab8c73-84c5-4a59-b006-4e539c1d9b6d)
![image](https://github.com/BewlyBewly/BewlyBewly/assets/33394391/4f469da0-5b98-4f7d-9c24-f37f89f15e02)
