### ISSUE TITLE
[BUG]无论在什么页面点击bewlybewly自带的搜索框时都会出现错误“STATUS_ILLEGAL_INSTRUCTION”

### ISSUE THREAD

**Issue by haohao5004** [BewlyBewly/BewlyBewly#855]
### 环境

浏览器:Edge
浏览器版本:128.0.2664.0
BewlyBewly 版本:v0.19.8

### 问题描述

https://github.com/BewlyBewly/BewlyBewly/assets/109277299/07f5c5e5-411a-4e02-a682-2f9e5e3a7d29
无论在什么页面点击bewlybewly自带的搜索框时都会出现错误“STATUS_ILLEGAL_INSTRUCTION”，使用B站自带的搜索框就没有这个问题

**Comment by hakadao** [comment]
是否和其他b站擴展使用或油猴腳本？沒能重現

**Comment by hakadao** [comment]
另外視頻中沒有看到STATUS_ILLEGAL_INSTRUCTION錯誤

**Comment by haohao5004** [comment]
我把油猴卸载了也没用，最近也没加什么拓展，使用最新版（0.20.0）也还是有这个问题。使用正式版Edge（126.0.2592.68）不会出现这个问题

**Comment by hakadao** [comment]
> 我把油猴卸载了也没用，最近也没加什么拓展，使用最新版（0.20.0）也还是有这个问题。使用正式版Edge（126.0.2592.68）不会出现这个问题

那請以正式版edge爲主, 新瀏覽器功能可能還沒有完善多bug這不是擴展問題
