### ISSUE TITLE
[BUG] 菜单页面如果超过弹窗大小就看不完

### ISSUE THREAD

**Issue by Xionghaizi001** [BewlyBewly/BewlyBewly#856]
### 环境

浏览器: FireFox
浏览器版本: 127.0
BewlyBewly 版本: 0.19.8

### 问题描述

设置页面等插件自带的菜单看不完整个页面，也没有滚动条什么的，也不能滚动
![图片](https://github.com/BewlyBewly/BewlyBewly/assets/50747104/6b95569d-badc-4791-929e-34ade02b09e1)

**Comment by ITManCHINA** [comment]
其实换Chrome也不错（？）
真巧啊，你也在（偷看

**Comment by Xionghaizi001** [comment]
> 其实换Chrome也不错（？） 真巧啊，你也在（偷看

Edge和Firefox双持用户，懒得换了，尤其是Edge可以接入那个手机连接app，能够隔空接力发送网页

**Comment by hakadao** [comment]
沒能重現 v0.21.0, firefox 127.0.1 (64-bit)
<img width="1800" alt="image" src="https://github.com/BewlyBewly/BewlyBewly/assets/33394391/94b6bc65-4da1-4053-b859-502e28495433">

**Comment by Xionghaizi001** [comment]
已更新0.21.0，此bug已不存在。
