### ISSUE TITLE
[BUG] 收藏夹功能报错：Cannot read properties of null (reading 'medias')

### ISSUE THREAD

**Issue by RicardoWYP** [BewlyBewly/BewlyBewly#857]
### 环境

浏览器: Arc 
浏览器版本: 版本1.48.2 (51225)
BewlyBewly 版本: 0.19.8

### 问题描述

Arc 的收藏夹功能报错：index.global.js:156 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'medias')
    at index.global.js:156:16687
![image](https://github.com/BewlyBewly/BewlyBewly/assets/51823558/5be7e7f1-93be-46d6-82a2-768ac33e305d)

**Comment by hakadao** [comment]
最好標題不要只寫一個bug，簡單描述一下問題，我可能無意中會無視這類不明確內容
