### ISSUE TITLE
[BUG] 网页全屏播放视频时 会有默认播放页面的右侧文字显示在视频上

### ISSUE THREAD

**Issue by ljt990218** [BewlyBewly/BewlyBewly#858]
### 环境

浏览器: Chrome
浏览器版本: 126.0.6478.114
BewlyBewly 版本: 19.8

默认窗口右侧的 接下来播放栏的文字偶尔会在视频上显示

### 问题描述

![IMG_8975](https://github.com/BewlyBewly/BewlyBewly/assets/50509815/0a198295-b253-425e-88aa-a7691f064e57)

![IMG_8976](https://github.com/BewlyBewly/BewlyBewly/assets/50509815/e4c3bf4e-a83a-4ded-b85c-a50c0e0affdf)

**Comment by hakadao** [comment]
感覺這部份b站原版也有這個錯誤吧，是一瞬間還是持續的？
另外播放頁面只是調整了顏色其他甚麼都沒有改

**Comment by ljt990218** [comment]
一瞬间 可能就一帧的画面 我不使用插件没遇到过这个错误 我中午吃饭看视频时 多测测看

**Comment by ljt990218** [comment]
之前看视频也遇到过  我就把插件关闭 就没有这个问题了

**Comment by hakadao** [comment]
> 之前看视频也遇到过  我就把插件关闭 就没有这个问题了

我覺得這個問題是b站原因，多點試試直接使用b站情況下有沒有此情況
通常這個問題可能是和瀏覽器渲染有關

**Comment by ljt990218** [comment]
> > 之前看视频也遇到过  我就把插件关闭 就没有这个问题了
> 
> 我覺得這個問題是b站原因，多點試試直接使用b站情況下有沒有此情況 通常這個問題可能是和瀏覽器渲染有關

ok
