### ISSUE TITLE
[BUG] 稍后再看页和收藏页的模糊失效

### ISSUE THREAD

**Issue by 22Frederic** [BewlyBewly/BewlyBewly#863]
### 环境

浏览器 (如 Chrome):Chrome
浏览器版本 (如 126.0.6478.126):122.0.6261.95
BewlyBewly 版本 (如 0.20.1):0.20.1

### 问题描述

如图
![屏幕截图 2024-06-25 124227](https://github.com/BewlyBewly/BewlyBewly/assets/105597335/8592fe73-bfdb-45b8-813f-23c3f021cf29)

**Comment by hakadao** [comment]
ummm，就沒有試過其他瀏覽器有這種情況

**Comment by hakadao** [comment]
好吧,好像瀏覽器對 backdrop-filter 限制又增強了, 我後面看看怎麼弄
