### ISSUE TITLE
首次进入网站鼠标手势无法正常使用，需要单击页面或进行其他交互之后才能恢复正常

### ISSUE THREAD

**Issue by NaiveShiki** [BewlyBewly/BewlyBewly#867]
### 环境

浏览器 (如 cent browser):
浏览器版本 (版本 5.1.1130.128（正式版本） （64 位） (Chromium 118.0.5993.159)):
BewlyBewly 版本 (v0.21.0):

### 问题描述

![recording](https://github.com/BewlyBewly/BewlyBewly/assets/100564095/4946caa6-e503-403a-8e01-6c90340ca00f)

**Comment by hakadao** [comment]
手勢問題筆會考慮在內，這些手勢附加功能很難排查是如何發生的，且沒有精力研究和適配不同擴展共用後產生的問題
這部分問題單獨使用不會出現所以暫時不管，我們期待有其他人能解決
