### ISSUE TITLE
[建议]批量不喜欢

### ISSUE THREAD

**Issue by kzyqq00-Player** [BewlyBewly/BewlyBewly#868]
我刷B站的时候有时候会有一大堆不喜欢的视频，能不能整个批量不喜欢？
例如像资源管理器那样拖动时候出个框框

**Comment by hakadao** [comment]
暫時不會考慮製作，首先不喜歡接口b站只提供了單個的，批量實現的話只能循環調用
延後過度調用我很難保證b站那邊會不會當機器人封禁帳戶
