### ISSUE TITLE
[BUG] View Later tooltip obscured on English pages

### ISSUE THREAD

**Issue by imguolao** [BewlyBewly/BewlyBewly#870]
### 环境

浏览器 (如 Chrome): Chrome
浏览器版本 (如 126.0.6478.126): 126.0.6478.127
BewlyBewly 版本 (如 0.20.1): 0.20.1

### 问题描述

![image](https://github.com/BewlyBewly/BewlyBewly/assets/25502024/6ecf58cf-fa5b-4b1f-ba52-05bf33a0e733)

**Comment by imguolao** [comment]
Maybe we can use vue3's Teleport component to pass the tooltip's dom outside the body below.

**Comment by ljt990218** [comment]
把 tooltip 层级提高 也许是一种解决方法
