### ISSUE TITLE
[BUG] 通知显示bug

### ISSUE THREAD

**Issue by Liu8Can** [BewlyBewly/BewlyBewly#877]
### 环境

浏览器 (如 Chrome):EDGE
浏览器版本 (如 126.0.6478.126):Microsoft Edge 版本 126.0.2592.61 (正式版本) (64 位)
BewlyBewly 版本 (如 0.20.1):0.22.1 通过Chrome Web Store 下载，

### 问题描述

通知显示异常，没有通知，总显示还有一条，有通知也会多显示一条。关闭插件后则常显示。【子栏显示为我的消息】
![image](https://github.com/BewlyBewly/BewlyBewly/assets/102885173/9045a8d8-f24d-4986-9f8b-e7986275408c)
![image](https://github.com/BewlyBewly/BewlyBewly/assets/102885173/b0b8553e-5166-4084-bc8a-b90a19b15684)
在issue中我只看了显示为双倍异常的，没有发现多一个的，特此反馈。

**Comment by hakadao** [comment]
暫時沒有復現,有看過是否是系統消息或b站原版(沒有用擴展情況下)頁面的消息更新不及時原因嗎

**Comment by limbia** [comment]
遇到同样问题

**Comment by Liu8Can** [comment]
您好！感谢您的邮件，我已经收到了您的来信。我会尽快阅读并回复您的邮件。请注意，这封邮件是自动回复，我目前无法立即回复您的邮件。感谢您的耐心等待！
