### ISSUE TITLE
[BUG] 暗色模式下“UP主觉得很赞”显示为亮色模式

### ISSUE THREAD

**Issue by qigongBea** [BewlyBewly/BewlyBewly#880]
### 环境

浏览器 (如 Chrome): Chrome
浏览器版本 (如 126.0.6478.126): 126.0.6478.127 
BewlyBewly 版本 (如 0.20.1): v0.22.1

### 问题描述

![image](https://github.com/BewlyBewly/BewlyBewly/assets/61674462/4e80d435-047f-4b67-b9d4-c31787733ce8)
如图。之前没有这个问题，是更新后出现的

**Comment by qigongBea** [comment]
![image](https://github.com/BewlyBewly/BewlyBewly/assets/61674462/f34850d2-c598-46af-8cfc-ad48de17e273)
还有这个

**Comment by qigongBea** [comment]
又另：创作中心未适配暗色模式。

**Comment by qigongBea** [comment]
又又另：合集详细页面暗色模式未适配
![image](https://github.com/BewlyBewly/BewlyBewly/assets/61674462/f743fcfd-26dd-404c-82a8-566b6f4747c4)
![image](https://github.com/BewlyBewly/BewlyBewly/assets/61674462/ed814c91-ffa9-4007-9d66-fdef22cc4105)

**Comment by hakadao** [comment]
部份深色模式只能盡量適配，因為b站會時不時改變class導致樣式失效這裏問題無法避免
這種無法做到十全十美

**Comment by hakadao** [comment]
b站留言區更新之後用shadow dom實現的，改樣式不太好處理，只能看看就沒有其他真幫忙聊

**Comment by TC999** [comment]
元素似乎改名，不再是`div`开头
![image](https://github.com/BewlyBewly/BewlyBewly/assets/88823709/040f10b5-6a22-4d86-93f9-668fd1f3394f)

**Comment by qigongBea** [comment]
> 部份深色模式只能盡量適配，因為b站會時不時改變class導致樣式失效這裏問題無法避免 這種無法做到十全十美

能理解

**Comment by LQZ100** [comment]
确实是元素改名， 有些元素并不能够适配了

**Comment by TC999** [comment]
> 确实是元素改名， 有些元素并不能够适配了

最奇葩的是老合集还是'div'开头，新合集就变成了'a'抬头
