### ISSUE TITLE
bewlybewly左上角图标显示

### ISSUE THREAD

**Issue by Areire** [BewlyBewly/BewlyBewly#881]
### 环境

edge：126.0.2592.87bewlybewly：0.23.0

### 问题描述

@Hakadao 这里左上角logo好像跟以前的不一样了，能不能改回来或者做个可选项？

**Comment by hakadao** [comment]
logo一直沒變過,只是去了底色

**Comment by Areire** [comment]
那麼能不能增加底色選項？

**Comment by Areire** [comment]
@hakadao 那麼能不能增加底色選項

**Comment by hakadao** [comment]
> @hakadao 那麼能不能增加底色選項

目前打算今後直接無底色後面會添加個陰影, 然後logo改成可以選顏色的那種

**Comment by Areire** [comment]
@hakadao 好的
