### ISSUE TITLE
[建议]右上角的下拉框中可以点击进入up主页

### ISSUE THREAD

**Issue by buyfakett** [BewlyBewly/BewlyBewly#882]
当前在右上角的动态、收藏、历史、稍后再看的下拉框中，点击up主的名字是不会跳转到up主主页
原生的b站是支持这个功能的
希望能支持

**Comment by ljt990218** [comment]
我想修复这个问题。目前有人在处理这个 Issue 吗？

**Comment by hakadao** [comment]
> 我想修复这个问题。目前有人在处理这个 Issue 吗？

加吧

**Comment by ljt990218** [comment]
> 当前在右上角的动态、收藏、历史、稍后再看的下拉框中，点击up主的名字是不会跳转到up主主页 原生的b站是支持这个功能的 希望能支持

原生b站：动态下拉  点击up主的头像、名字 转到up主主页
                 历史下拉>直播栏 点击up主的名字 转到up主主页
其他地方都不转到up主主页

@hakadao 我不知道是所有都加上 还是跟原生b站一致

**Comment by hakadao** [comment]
> > 当前在右上角的动态、收藏、历史、稍后再看的下拉框中，点击up主的名字是不会跳转到up主主页 原生的b站是支持这个功能的 希望能支持
> 
> 
> 
> 原生b站：动态下拉  点击up主的头像、名字 转到up主主页
> 
>                  历史下拉>直播栏 点击up主的名字 转到up主主页
> 
> 其他地方都不转到up主主页
> 
> 
> 
> @hakadao 我不知道是所有都加上 还是跟原生b站一致

先跟b站一樣吧，注意要用a標籤跳轉，因為a標籤實現可以拖動開新窗口和中鍵或按ctrl+點擊後台開新頁面
可能要處理一下冒泡問題

**Comment by ljt990218** [comment]
> > > 当前在右上角的动态、收藏、历史、稍后再看的下拉框中，点击up主的名字是不会跳转到up主主页 原生的b站是支持这个功能的 希望能支持
> > 
> > 
> > 原生b站：动态下拉  点击up主的头像、名字 转到up主主页
> > ```
> >              历史下拉>直播栏 点击up主的名字 转到up主主页
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 其他地方都不转到up主主页
> > @hakadao 我不知道是所有都加上 还是跟原生b站一致
> 
> 先跟b站一樣吧，注意要用a標籤跳轉，因為a標籤實現可以拖動開新窗口和中鍵或按ctrl+點擊後台開新頁面 可能要處理一下冒泡問題

👌
