### ISSUE TITLE
[BUG] 消息菜单和关注菜单冲突相关

### ISSUE THREAD

**Issue by ITManCHINA** [BewlyBewly/BewlyBewly#883]
### 环境

**浏览器：Chrome
浏览器版本：126.0.6478.127 X64
BewlyBewly 版本：0.23.0

### 问题描述

在一个视频播放页里，鼠标移动到消息按钮并快速位移到`提醒我的`、`收到的赞`的位置，**且鼠标在`消息菜单`的范围之内**，会触发层级下面的关注菜单（如图）。这算是比较影响效率和操作体验的bug了🥲
![1720184991523](https://github.com/BewlyBewly/BewlyBewly/assets/50987405/77d883bc-3cdd-4d88-820a-13e45e1467ae)

**Comment by hakadao** [comment]
Ok之後儘快改

**Comment by hakadao** [comment]
這個比較難觸發也不太好處理，因為之前不調整座標那麼高是為了防止頂欄在影片全螢幕顯示時遮擋畫面。。。
