### ISSUE TITLE
[建议] 希望“个人推荐”不要有上限，这会导致设置了推荐过滤后无法推荐视频或者只能推荐几个视频。

### ISSUE THREAD

**Issue by jueduilingdu08** [BewlyBewly/BewlyBewly#884]
### 问题描述

我个人特别喜欢看长视频，所以会使用推荐过滤功能来过滤出超过30分钟的长视频，但是过滤后只剩下两三个视频了。
我同时测试了另一款猴油的插件“bilibili-app-recommend” 连接：https://github.com/magicdawn/bilibili-app-recommend
该软件是没有这个问题的，在筛选30分钟视频后可以铺满整个屏幕并且无限增加。
我研究了下发现是由于个人推荐有上限，而这个上限会导致筛选视频后数量不足，而且无法手动开关上限，如果可以，希望可以不设置上限，让过滤出来的视频可以无限增加或者增加一个开关。 谢谢！
因为我觉得您做的软件更好用效率更高，所以希望作者能增加该功能，谢谢！

筛选设置：
![筛选设置](https://github.com/BewlyBewly/BewlyBewly/assets/39888256/f04c4d78-a4ea-4f66-9b53-996b86d73e7b)
筛选后的视频数量：
![筛选后的视频数量](https://github.com/BewlyBewly/BewlyBewly/assets/39888256/10323466-d271-490b-948b-b46940795fc4)

另一款猴油软件的筛选设置：
![另一款猴油软件的筛选设置](https://github.com/BewlyBewly/BewlyBewly/assets/39888256/d269f89b-5ea6-4b6f-8330-4f80737e4922)
另一款猴油软件的筛选后的视频数量：
![另一款猴油软件的筛选后的视频数量](https://github.com/BewlyBewly/BewlyBewly/assets/39888256/3454a1a8-e136-4778-8e87-3897cf7d0479)

**Comment by akira0245** [comment]
而且有个问题是如果筛选出来的视频太少不满半屏导致没法滚动，就直接不会加载更多视频了，因为加载是滚动触发的
希望能改进一下
