### ISSUE TITLE
扩展的图片有些无法加载，希望做进扩展本地

### ISSUE THREAD

**Issue by Aarondongsq** [BewlyBewly/BewlyBewly#886]
### 环境

浏览器：Edge

### 问题描述

在中国大陆，在设置页面的部分图片根本无法加载

**Comment by hakadao** [comment]
做進本地edge直接說損壞然後之前edge用戶完全不看說明edge審核慢修復了的bug還要看edge審核眼色和edge用戶轟炸過時錯誤提出我真的不感繼續做了

**Comment by Aarondongsq** [comment]
插件登录的按钮有显示问题，字体与图标有错位现象，在使用了新版的顶栏后所致

使用的浏览器：Chrome（版本 122.0.6261.85）
