### ISSUE TITLE
[BUG] 表情面板被弹幕输入框文本遮挡

### ISSUE THREAD

**Issue by PopFortress** [BewlyBewly/BewlyBewly#887]
### 环境

浏览器 (如 Chrome): msedge
浏览器版本 (如 126.0.6478.126): 126.0.2592.87
BewlyBewly 版本 (如 0.20.1): 0.19.0

### 问题描述

![image](https://github.com/BewlyBewly/BewlyBewly/assets/124672853/9e8b9311-74ca-4eb6-8456-f27b3ab8396a)

**Comment by MidnightCrowing** [comment]
把插件关了试试呢

![PixPin_2024-07-07_20-17-58](https://github.com/BewlyBewly/BewlyBewly/assets/110297461/2c19d6c4-ba09-4411-a2b1-be70397784d7)
这个应该是b站的问题, 建议找b站客服反馈

**Comment by hakadao** [comment]
經確認這部分沒有使用擴展情況下b站也有這問題,請去b站客戶反饋

**Comment by hakadao** [comment]
另外現在最新版本是 v0.24.0 EDGE 用戶也可以透過 chrome web store 下載 BewlyBewly 且 edge 也會自動更新擴展

**Comment by PopFortress** [comment]
好的，谢谢回复。
不过我在 Edge 商店上好像搜索不到 BewlyBewly 扩展了？

> 另外現在最新版本是 v0.24.0 EDGE 用戶也可以透過 chrome web store 下載 BewlyBewly 且 edge 也會自動更新擴展

**Comment by hakadao** [comment]
> 好的，谢谢回复。 不过我在 Edge 商店上好像搜索不到 BewlyBewly 扩展了？
> 
> > 另外現在最新版本是 v0.24.0 EDGE 用戶也可以透過 chrome web store 下載 BewlyBewly 且 edge 也會自動更新擴展

edge商店上的已经下架，可以用edge下载chrome web store上的bewlybewly，那边下载也可以更新 https://chromewebstore.google.com/detail/bewlybewly/bbbiejemhfihiooipfcjmjmbfdmobobp

**Comment by PopFortress** [comment]
> > 好的，谢谢回复。 不过我在 Edge 商店上好像搜索不到 BewlyBewly 扩展了？
> > > 另外現在最新版本是 v0.24.0 EDGE 用戶也可以透過 chrome web store 下載 BewlyBewly 且 edge 也會自動更新擴展
> 
> edge商店上的已经下架，可以用edge下载chrome web store上的bewlybewly，那边下载也可以更新 https://chromewebstore.google.com/detail/bewlybewly/bbbiejemhfihiooipfcjmjmbfdmobobp

嗯嗯
