### ISSUE TITLE
背景设置问题

### ISSUE THREAD

**Issue by shaoyouvip** [BewlyBewly/BewlyBewly#892]
![屏幕截图 2024-07-08 180613](https://github.com/BewlyBewly/BewlyBewly/assets/45180881/d01b981b-4391-4a84-b8ef-c24ebb3ebd1f)
![屏幕截图 2024-07-08 180633](https://github.com/BewlyBewly/BewlyBewly/assets/45180881/f2de2a64-d96b-4dea-8613-7f429383ac3e)
您好这个背景设置只有首页生效 感觉挺有割裂感的. 能在新打开的视频页面也同步吗?

**Comment by hakadao** [comment]
不打算,那部分處理太過麻煩,
