### ISSUE TITLE
[style] set the video title height on the video card

### ISSUE THREAD

**Issue by huzhongyang** [BewlyBewly/BewlyBewly#894]
### before
![image](https://github.com/user-attachments/assets/f71fa690-0a80-4258-8038-f3330a385a8a)

### after
![image](https://github.com/user-attachments/assets/05a75af4-fc27-47e0-8814-c369fafe6467)

**Comment by hakadao** [comment]
i dont understand why we should leave a space to achieve alignment, it seems a bit weird... 
the current design is already very good
