### ISSUE TITLE
[Ehancement]适配篡改猴脚本-B站屏蔽

### ISSUE THREAD

**Issue by MoreBugOfDog** [BewlyBewly/BewlyBewly#901]
### 环境

浏览器 (如 Chrome):Edge
浏览器版本 (如 126.0.6478.126): 版本 127.0.2651.49 (正式版本) stable应用，beta频道 (64 位)
BewlyBewly 版本 (如 0.20.1):[v0.25.0](https://github.com/hakadao/BewlyBewly/releases)

### 问题描述

篡改猴脚本 任何修改DOM的操作都会被失效（如屏蔽标题包含指定内容的视频https://update.greasyfork.org/scripts/474107/B%E7%AB%99%E5%B1%8F%E8%94%BD.user.js）
**（原因：视频相关信息被修改，应该是className）**
关闭广告屏蔽无效
关闭毛玻璃无效
关闭背景遮罩无效
在**拓展内**设置使用原版首页有效
![image](https://github.com/user-attachments/assets/b8f0c254-61c6-475b-bf86-f48927680c15)
这个操作有效

### 预期结果

使用拓展修改的首页下，篡改猴脚本依然起作用

**Comment by MengNianxiaoyao** [comment]
这个不算bug，因为首页不是b站自己的而是插件的了

**Comment by hakadao** [comment]
這部分處理不了,要麼用原版頁面要麼就先這樣...
