### ISSUE TITLE
[BUG]搜索框在失去焦点后重新点击后，光标位置不在鼠标点击处

### ISSUE THREAD

**Issue by Faneter** [BewlyBewly/BewlyBewly#903]
## 环境
浏览器：Firefox 版本: 128.0 (64 位)
BewlyBewly 版本: 0.25

## 问题描述

在域名[search.bilibili.com](https://search.bilibili.com/)下的失焦的文本框在点击时无法根据鼠标点击位置切换光标位置，而会停留在文本最后方。
![录制_2024_07_17_22_10_42_876 00_00_00-00_00_30](https://github.com/user-attachments/assets/b85dd6f2-6798-48fc-b16e-2fcc02e687fb)
如上图所示，在我点击“方”和“的”中间时，光标并未出现在这两字之间，而是在文本最后方。
经我测试，[主页www.bilibili.com](https://www.bilibili.com/)的搜索框无此问题，而在[搜索页search.bilibili.com](https://search.bilibili.com/)下出现此问题。

**Comment by hakadao** [comment]
這部分你可以試試停用擴展後看看原版b站的處理, 建議去跟b站客服提出問題, bewly 只是深度改寫主頁其他頁面功能都沒有額外調整過
