### ISSUE TITLE
关于视频刷新按钮

### ISSUE THREAD

**Issue by Kirara-Tianqing** [BewlyBewly/BewlyBewly#905]
一个很好的拓展重新规划B站主页的排版让人非常舒服与喜欢，但是关于视频的刷新功能按钮能否独立出来，放在B站原版主页的位置 (第一行最后一列的右边) 呢？因为用惯了原版的刷新按钮，现在在用右下角二合一的刷新按钮太难受了(我个人的鼠标指针习惯是在放屏幕右边的中间偏上，我不知道大家是不是也这样)

**Comment by hakadao** [comment]
你可以試試這個功能
![image](https://github.com/user-attachments/assets/1ac5acb5-7d95-439a-b333-459b89c71cbb)
啓用後
![image](https://github.com/user-attachments/assets/a11ab7b5-13a8-4cc3-b5e5-e8e85b87bf0f)
