### ISSUE TITLE
发现B站消息页面添加暗色支持

### ISSUE THREAD

**Issue by MidnightCrowing** [BewlyBewly/BewlyBewly#908]
### 环境

Nothing to preview

### 问题描述

![PixPin_2024-07-18_13-36-58](https://github.com/user-attachments/assets/792b3b75-1428-4ff9-a597-26c537d0590e)

经过多次尝试，发现显示暗色模式似乎是个随机事件，但可以在顶部的 `html` 标签中的 `class` 属性里添加 `bili_dark` 值，以手动切换为暗色模式。

B站的这个改动会导致使用插件时切换亮色模式出现问题，#907 就是为了想解决这个问题。

不过这只是进行简单尝试，切换时会导致与过渡动画不适配，后面要改。在这之前，我想问一下，关于B站暗色模式的支持，我们要怎么处理？

- 如果不想使用它的样式，可以直接删除 `bili_dark` 这个值。
- 如果想基于它的样式进行调整，目前需要解决能否与过渡动画配合的问题。

另外，我感觉它的暗色支持并不好看（个人意见）。

我对多个页面手动添加 `bili_dark` 进行了尝试，发现动态页也适配了暗色模式，但与插件的暗色模式产生冲突（出现颜色叠加, 变得更暗）：

![PixPin_2024-07-18_13-32-15](https://github.com/user-attachments/assets/c1238a1e-ac90-4fc4-ae9a-7401a230d93e)

**Comment by hakadao** [comment]
首先如果b站真做了深色模式是一件好事, 之後擴展又能減少一些工作量, 至於好不好看另說, 你也應該感受到適配b站深色的痛苦吧
過後我看看b站那邊的深色效果先, 最近上班回到家都沒有時間
