### ISSUE TITLE
刪除底部高斯模糊

### ISSUE THREAD

**Issue by Alan-CRL** [BewlyBewly/BewlyBewly#912]
### 环境

浏览器: Edge
浏览器版本: 126.0.2592.102 
BewlyBewly: 0.25.0

### 问题描述

尊敬的 BewlyBewly 开发团队：我发现向上到顶按钮被底端的高斯模糊了，而位于底部的栏并没有被高斯模糊。总结为层级错误。

### 预期结果

修复这个问题后，我也希望提供一个开关可以关闭底部高斯模糊，我不喜欢这个东西，导致我现在还停留在 0.21.1，这应该是最后一个没有底部高斯模糊的版本。

**Comment by hakadao** [comment]
下版本刪除底部模糊
