### ISSUE TITLE
[建議] 过滤掉无意义的up主

### ISSUE THREAD

**Issue by Galen-Chen177** [BewlyBewly/BewlyBewly#915]
### 环境

浏览器 (如 Chrome):
浏览器版本 (如 126.0.6478.126):
BewlyBewly 版本 (如 0.20.1):

### 问题描述

进入B站的时候，经常有<0元白嫖XXX游戏><年入XX个W，但是需要放弃社交>这类视频，一看就是小号来诈骗的，每次都会拉黑，但是没什么效果，每天都会有新的这类视频在B站主页，我发现这类小号都是关注人数很少，播放量很高的号，大概率就是买来骗人的，很影响体验，烦不甚烦，

### 预期结果

希望出一个功能能自定义过滤掉这些小号的视频，比如在设置里设置10000，那么界面中不会显示关注人数小于10000的UP的视频，拜托，真的拉黑都拉黑吐了

**Comment by kitawa1981** [comment]
希望能添加关键字过滤

**Comment by hakadao** [comment]
弄完了下版本會有
https://github.com/BewlyBewly/BewlyBewly/pull/965

**Comment by Galen-Chen177** [comment]
thanks
