### ISSUE TITLE
[enhancement] 番剧页面建议

### ISSUE THREAD

**Issue by kndxhz** [BewlyBewly/BewlyBewly#917]
在b站中，番剧被分为3个类型，分别是“想看”、“在看”、“看过”
而**在番剧页面的“正在追”部分应当展示的是“在看”的内容，而不是所有番剧**
![image](https://github.com/user-attachments/assets/179675e6-51a1-477f-a493-1071f0e164ec)

简单抓了下api
在看
`https://api.bilibili.com/x/space/bangumi/follow/list?type=1&follow_status=2&pn=1&ps=15&vmid=用户uid`
想看
`https://api.bilibili.com/x/space/bangumi/follow/list?type=1&follow_status=1&pn=1&ps=15&vmid=用户uid`
看过
`https://api.bilibili.com/x/space/bangumi/follow/list?type=1&follow_status=3&pn=1&ps=15&vmid=用户uid`

**Comment by hakadao** [comment]
順便提醒一下最新版本是 v0.26.0, edge 已放棄上架可在 edge 中用 chrome web store 下載且會自動更新

**Comment by kndxhz** [comment]
好的，已经更新


| |
可耐的小伙纸
游戏和科技爱好者
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月25日 10:31 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [BewlyBewly/BewlyBewly] [feat] 番剧页面建议 (Issue #917) |

順便提醒一下最新版本是 v0.26.0, edge 已放棄上架可在 edge 中用 chrome web store 下載且會自動更新
