### ISSUE TITLE
[BUG] 首页通知右上角显示数量，进入菜单后未显示数量

### ISSUE THREAD

**Issue by Renyi12345678** [BewlyBewly/BewlyBewly#918]
### 环境

浏览器 (Chrome):
浏览器版本 (118.0.5993.159 ):
BewlyBewly 版本 (0.25.2):

### 问题描述

右上角通知开启数字角标后，会显示新消息数量（比如1），但是点一下到菜单（回复我的、提到我的、收到的赞...）这个页面时，却不会显示刚才的消息数量1，必须一个个点进去查看具体是哪个。

**Comment by hakadao** [comment]
沒能重現，這可能是b站返回數據問題

**Comment by Renyi12345678** [comment]
如图
![微信截图_20240725093050](https://github.com/user-attachments/assets/b5d08ffb-0294-4f35-8012-3038a1f8116c)
![微信截图_20240725093103](https://github.com/user-attachments/assets/d68f7b9f-660b-447b-97c7-e10fc28ac500)

**Comment by Renyi12345678** [comment]
> 沒能重現，這可能是b站返回數據問題

尝试更新到0.26.0，依然存在这个问题，如果解决不了就先凑合用着吧，感谢

**Comment by hakadao** [comment]
這部分是直接調用這個接口計算數量, 要麼是b站後臺返回結果變了, 否則不會突然出問題
https://api.bilibili.com/x/msgfeed/unread?mobi_app=web

**Comment by macshen** [comment]
同样的问题，从上个版本就是这样

**Comment by macshen** [comment]
> 這部分是直接調用這個接口計算數量, 要麼是b站後臺返回結果變了, 否則不會突然出問題 [api.bilibili.com/x/msgfeed/unread?mobi_app=web](https://api.bilibili.com/x/msgfeed/unread?mobi_app=web)

https://api.bilibili.com/x/msgfeed/unread?mobiapp=web
多了个 _ 下划线?
