### ISSUE TITLE
[BUG] 打开网站视频时，默认关闭视频声音

### ISSUE THREAD

**Issue by Wushiye1st** [BewlyBewly/BewlyBewly#921]
### 环境

浏览器  Chrome
浏览器版本 127.0.6533.73
BewlyBewly 版本 0.25.2

### 问题描述

打开视频以后默认关闭声音，无法修正改为默认开启。

### 预期结果

希望提供默认开启和默认关闭的声音的选项

**Comment by hakadao** [comment]
這部分沒有一行代碼控制了自動靜音，暫時不知道瀏覽器是怎麼處理的，可能需要其他人幫忙研究

**Comment by UiShigure** [comment]
https://developer.chrome.com/blog/autoplay?hl=zh-cn
这是浏览器的播放策略，只要网站的媒体参与度低，视频是不允许有声自动播放的

**Comment by UiShigure** [comment]
说白了，就是视频刷少了，媒体参与度不高

**Comment by hakadao** [comment]
目前試過如果以視頻卡片以抽屜打開的話不會出現此問題，新標籤頁開啓不知觸發了甚麼策略導致預設靜音

**Comment by hafterain** [comment]
请检査你浏览器的权限设置，新版本的浏览器往往默认设置为「阻止音频」，改为「允许音频和视频」方可在打开时播放声音。

![图片](https://github.com/user-attachments/assets/cb600cae-503e-4807-8cd0-2bb5a31bb628)
