### ISSUE TITLE
[feat] 创作者页专栏编辑器深色模式适配

### ISSUE THREAD

**Issue by TC999** [BewlyBewly/BewlyBewly#922]
现在情况，如图所示
![image](https://github.com/user-attachments/assets/e895ff0f-eba4-4a14-a821-29d9b6e4c726)

网址：<https://member.bilibili.com/platform/upload/text/edit>

**Comment by hakadao** [comment]
這部分是個iframe,不打算完全適配沒有太多精力

**Comment by TC999** [comment]
修改了下代码，这样就成功了，[编译好的扩展](https://github.com/TC999/BewlyBewly-Beta/releases/tag/v0.26.23)
相关提交 https://github.com/TC999/BewlyBewly-Beta/commit/1dd4fad5b895ac5c8f3513ded44e10a3bdf6f1b2
测试效果图
![](https://private-user-images.githubusercontent.com/88823709/352570848-8bd7407b-db3a-43c6-81c4-ccf6a23e6ff0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMDUzMTcsIm5iZiI6MTcyMjAwNTAxNywicGF0aCI6Ii84ODgyMzcwOS8zNTI1NzA4NDgtOGJkNzQwN2ItZGIzYS00M2M2LTgxYzQtY2NmNmEyM2U2ZmYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDE0NDMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjMGYzNjJkOGRmMzMyMWZlYTAxODZlNTY0ZmM2NGQ5YjY0OWI1Y2E2ZDY0ODI1ZmE1MTgxOGVmNGZkNTk0OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.syjFlZ_O4cWEXaRsICvo3OwowMcZuR2YmmhlsqWXIjI)

**Comment by hakadao** [comment]
> 修改了下代码，这样就成功了，[编译好的扩展](https://github.com/TC999/BewlyBewly-Beta/releases/tag/v0.26.23)
> 
> 相关提交 https://github.com/TC999/BewlyBewly-Beta/commit/1dd4fad5b895ac5c8f3513ded44e10a3bdf6f1b2
> 
> 测试效果图
> 
> ![](https://private-user-images.githubusercontent.com/88823709/352570848-8bd7407b-db3a-43c6-81c4-ccf6a23e6ff0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIwMDUzMTcsIm5iZiI6MTcyMjAwNTAxNywicGF0aCI6Ii84ODgyMzcwOS8zNTI1NzA4NDgtOGJkNzQwN2ItZGIzYS00M2M2LTgxYzQtY2NmNmEyM2U2ZmYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDE0NDMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjMGYzNjJkOGRmMzMyMWZlYTAxODZlNTY0ZmM2NGQ5YjY0OWI1Y2E2ZDY0ODI1ZmE1MTgxOGVmNGZkNTk0OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.syjFlZ_O4cWEXaRsICvo3OwowMcZuR2YmmhlsqWXIjI)

你看看那邊上傳圖片是不是反色的。。。
做完要多測
