### ISSUE TITLE
bewlybewly0.27.0顶部栏

### ISSUE THREAD

**Issue by Areire** [BewlyBewly/BewlyBewly#929]
### 环境

edge 127.0.2651.74
bewlybewly 0.27.0

### 问题描述

bewlybewly右上角顶部栏改的有一点别扭。

### 预期结果

增加可选项

**Comment by hakadao** [comment]
不打算，如果有建議的可以提出進行修改，但不打算改回來

**Comment by HibikiZ3** [comment]
那你就不能加个自定义排序？用了那么久都习惯了你说改就改？还不能自己排序？

**Comment by hakadao** [comment]
> 那你就不能加个自定义排序？用了那么久都习惯了你说改就改？还不能自己排序？

沒有強制你用bewly，現在主流的都是頭像放右邊的，我甚至沒有強制你收費使用如果你覺得真的不好用歡迎去用其他擴展

**Comment by HibikiZ3** [comment]
那你要不想加自定义排序那我就用老版本呗，能拿你咋办

**Comment by HibikiZ3** [comment]
> > 那你就不能加个自定义排序？用了那么久都习惯了你说改就改？还不能自己排序？
> 
> 沒有強制你用bewly，現在主流的都是頭像放右邊的，我甚至沒有強制你收費使用如果你覺得真的不好用歡迎去用其他擴展

那你要不想加自定义排序那我就用老版本呗，能拿你咋办

**Comment by hakadao** [comment]
> > > 那你就不能加个自定义排序？用了那么久都习惯了你说改就改？还不能自己排序？
> > 
> > 
> > 沒有強制你用bewly，現在主流的都是頭像放右邊的，我甚至沒有強制你收費使用如果你覺得真的不好用歡迎去用其他擴展
> 
> 那你要不想加自定义排序那我就用老版本呗，能拿你咋办

歡迎使用舊版本，沒有人強制你一定要用新的

**Comment by Areire** [comment]
那行吧，我慢慢适应。

**Comment by hakadao** [comment]
> 那行吧，我慢慢适应。

後續加個用回舊頂欄選項，但是舊頂欄那部份之後我不會再做太大調整包括功能上的

**Comment by Areire** [comment]
OK。

**Comment by hakadao** [comment]
<img width="979" alt="image" src="https://github.com/user-attachments/assets/ddab4771-c8f8-4966-b86e-b2795ff0c0aa">
