### ISSUE TITLE
[BUG] 鼠标悬停在自己头像后，不能马上操作弹出菜单

### ISSUE THREAD

**Issue by g-mph** [BewlyBewly/BewlyBewly#934]
### 环境

浏览器 (如 Chrome):Microsoft Edge
浏览器版本 (如 126.0.6478.126):127.0.2651.74
BewlyBewly 版本 (如 0.20.1):0.27.2

### 问题描述

鼠标放在右上角自己头像上，一出现弹出菜单后鼠标下移，菜单消失。

### 预期结果

鼠标放在右上角自己头像上，一出现弹出菜单后鼠标下移，菜单动画依旧展示，菜单打开。

**Comment by g-mph** [comment]
右边几个键都没有这问题，就只有自己头像键有。

**Comment by hakadao** [comment]
試試最新版0.30.0還有沒有問題

**Comment by g-mph** [comment]
> 試試最新版0.30.0還有沒有問題

@hakadao 还是有

https://github.com/user-attachments/assets/887585a2-f455-4ff7-a7bb-4106fe3c3400
