### ISSUE TITLE
[BUG] Edge 等级进度栏显示错误

### ISSUE THREAD

**Issue by Aliorpse** [BewlyBewly/BewlyBewly#935]
原版
![2409c8bbc5cbd96522d1dc95d981c026](https://github.com/user-attachments/assets/bea5ae83-9a19-4d5e-8dcf-80db2c797549)
BewlyBewly
![b0452314c7e51e41780727a4f8dad770](https://github.com/user-attachments/assets/5bbc17f5-c00a-4201-998b-e4b0de31fb24)

**Comment by hakadao** [comment]
數值都是一樣, 只是調整了一下大小寫, 沒看到有錯誤

**Comment by Aliorpse** [comment]
我的意思是，进度条显示进度百分比不同
