### ISSUE TITLE
[BUG] 黑暗主题无法适配DARK READER插件

### ISSUE THREAD

**Issue by LeonX86** [BewlyBewly/BewlyBewly#937]
### 环境

浏览器 (如 Chrome):Thorium
浏览器版本 (如 126.0.6478.126):124.0.6367.218
BewlyBewly 版本 (如 0.20.1): 0.27.2

### 问题描述

![1Q7Y{%AR`QC36J6ZZ4} 7FC](https://github.com/user-attachments/assets/5c5eb512-cc90-41a3-bec5-b6a099dfe538)
![QQ截图20240729224812](https://github.com/user-attachments/assets/60145db6-c3a2-49f2-8a27-21bd3aaf3467)
想问一下这个自动的逻辑是啥，是根据时间自动切换至黑暗模式吗，我用了几天他好像也没自己切换，然后和DARK READER插件也不适配

### 预期结果

根据时间自动切换明亮/黑暗模式

**Comment by hakadao** [comment]
bewlybewly本來就有b站多數頁面的深色適配你還要用dark reader幹甚麼，只要你系統顏色和瀏覽器顏色是深色bewly就是深色
