### ISSUE TITLE
想问一下搜索之后的跳转的页面会进一步适配吗？

### ISSUE THREAD

**Issue by FeliPan** [BewlyBewly/BewlyBewly#938]
![屏幕截图 2024-07-30 114136](https://github.com/user-attachments/assets/fe82f35a-a5f7-416c-b996-69af41ec72d9)
![屏幕截图 2024-07-30 114423](https://github.com/user-attachments/assets/cf4ef678-eed8-4d78-a8d4-d5c33b6e9462)

比如说顶部栏，以及下拉后显示的原版搜索框这些，会进一步修改吗？

**Comment by hakadao** [comment]
不會，沒有那麼精力
