### ISSUE TITLE
[BUG] 动态直播数据没拉取 没显示出来

### ISSUE THREAD

**Issue by GaoJaJnn** [BewlyBewly/BewlyBewly#942]
### 环境

浏览器 (如 Chrome):Chrome
浏览器版本 (如 126.0.6478.126):127.0.6533.89
BewlyBewly 版本 (如 0.20.1):v0.27.3

### 问题描述

主页 动态 直播显示为空,但是有主播开播
![1722417664404](https://github.com/user-attachments/assets/8dfa690f-4d49-44cd-8ba7-8cccb095d145)
![1722417908473](https://github.com/user-attachments/assets/86cd6e9f-2b5e-4810-90af-d49f4d89e764)

### 预期结果

动态直播显示主播开播list

**Comment by hakadao** [comment]
有數據的,只是沒有刷新而已
![image](https://github.com/user-attachments/assets/8a24ef65-6593-4852-b89d-01aaa2530479)
