### ISSUE TITLE
[BUG]顶栏模糊

### ISSUE THREAD

**Issue by alexchend** [BewlyBewly/BewlyBewly#948]
### 环境

浏览器 :Edge
浏览器版本:127.0.2651.86 (正式版本) (64 位)
BewlyBewly 版本 :0.27.3

### 问题描述

顶栏模糊，我是笔记本，分辨率2560x1600时候会这样，我刚刚试了试1920x1080就不会
<img width="366" alt="Snipaste_2024-08-03_03-08-34" src="https://github.com/user-attachments/assets/ee841dec-565f-4465-b86a-37cf8f30fc3f">

**Comment by hakadao** [comment]
先試試換chrome看看有沒有這種情況，比較大概率是瀏覽器渲染問題
