### ISSUE TITLE
[Feature] 首页推荐视频添加拉黑作者的选项

### ISSUE THREAD

**Issue by ffainy** [BewlyBewly/BewlyBewly#949]
目前首页推荐视频有`不感兴趣`和`不想看此UP主`两个快捷选项，但都没啥用，点了以后没刷新几次又出现了
希望能添加一个拉黑此UP主的功能，正常拉黑需要点UP主名字进入主页才能操作很麻烦

**Comment by hakadao** [comment]
其實最好建議你用app推介，網頁版推介那邊據說拉黑了還是會有出現
