### ISSUE TITLE
[BUG] 首页视频卡片不能兼容 Surfingkeys

### ISSUE THREAD

**Issue by LonelySteve** [BewlyBewly/BewlyBewly#951]
### 环境

浏览器 (如 Chrome): Chrome
浏览器版本 (如 126.0.6478.126):  127.0.6533.89（正式版本） （64 位）
BewlyBewly 版本 (如 0.20.1): 0.27.3

### 问题描述

**演示**

https://github.com/user-attachments/assets/55260a2e-11c8-4fcb-b1eb-8c00f70f1fc5

**当前现象**

通过 [Surfingkeys](https://github.com/brookhong/Surfingkeys) 操作，无论是使用 q 还是 f，无论是对视频封面还是视频标题做模拟点击，均无法正常打开首页视频，操作之后无反应，必须通过鼠标才能打开视频

**相关代码**

https://github.com/BewlyBewly/BewlyBewly/blob/b8cfa16d015d5fe2b33a30fef4c7d63fc4db11c6/src/components/VideoCard/VideoCard.vue#L236-L239

可能是因为并非对 click 事件做监听，所以 surfingkeys 触发图片或标题点击之后没有反应，即使是在控制台中通过 $0.click() 的方式也无法触发打开视频的逻辑

**其他**

虽然没有尝试，但 [Vimium](https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb?hl=zh) 应该也是无法正常使用的，另外一点，虽然首页的视频无法正常通过 Surfingkeys 打开，但搜索页面，视频页面的视频却能通过 Surfingkeys 正常打开（也能通过 $0.click() 的方式打开）。

### 预期结果

通过 Surfingkeys 正常打开首页视频

**Comment by hakadao** [comment]
是不是只要有click事件跳轉就可以了嗎？

**Comment by LonelySteve** [comment]
> 是不是只要有click事件跳轉就可以了嗎？

理论上是这样的，只要 BewlyBewly 能正常处理来自图片的 click 事件即可，从 Surfingkeys 代码可以看出，它默认情况下会触发 ['mouseover', 'mousedown', 'mouseup', 'click'] 这些事件，但看起来单纯地触发  'mousedown', 'mouseup' 并不能正常打开视频

https://github.com/brookhong/Surfingkeys/blob/965301c079852f9d310145d823628d107e940588/src/content_scripts/common/hints.js#L781

目前看来解决方法有两个：

1. 让 BewlyBewly 能正常处理来自图片的 click 事件
2. 提供一种程序化的方式来触发打开视频的逻辑，我可以通过编写 Surfingkeys 配置的方式来自定义它点击的行为

其中第二种方式需要对 BewlyBewly 这块的逻辑有一定了解，因为我本人时间不多，所以想请教大佬，是否可以通过在元素上组合分发一些事件来达到目的，这样其实也不用修改 BewlyBewly 的代码了

**Comment by LonelySteve** [comment]
可以了，感谢
