### ISSUE TITLE
[功能建议] 左上这个按钮，增加一个设定让其只具备刷新功能，不弹出分类框

### ISSUE THREAD

**Issue by ErickWei** [BewlyBewly/BewlyBewly#952]
### 环境

浏览器 (如 Chrome):
浏览器版本 (如 126.0.6478.126):
BewlyBewly 版本 (如 0.20.1):

### 问题描述

个人习惯，基本上这个按钮只用来刷新，不查看分类视频。
隐隐觉得还有很多人有这种需求，希望能增加这个功能，因为弹出来另外一个对话框有点碍事。谢谢

<img width="902" alt="image" src="https://github.com/user-attachments/assets/c1f84c7f-0072-4ce1-a2a7-9518e727fd08">

**Comment by hakadao** [comment]
f5 或 ctrl + r 就可以解決再說加動不動一個配置後期維護太麻煩
