### ISSUE TITLE
[建议]增加自定义字体

### ISSUE THREAD

**Issue by JIUYINGSHI** [BewlyBewly/BewlyBewly#954]
毕竟win的字体对我来说有点花眼，不知道能不能做到

**Comment by NoCatsOrYou** [comment]
浏览器中更改字体就行，或者更改系统字体

**Comment by Pcodcsja** [comment]
我也是在浏览器中更改了字体 结果还是不太行
![Clip_2024-08-25_04-01-27](https://github.com/user-attachments/assets/da67ead1-cbf1-4b7f-a024-f768cfd868c3)
你在浏览器安装一个油猴插件管理器，然后安装「Bilibili Evolved」插件（项目地址：https://github.com/the1812/Bilibili-Evolved?spm_id_from=..0.0） 
在插件中安装这个
![Clip_2024-08-25_04-03-11](https://github.com/user-attachments/assets/ed15260b-b898-44e8-bc86-69e87557aadb)
点击更多选项后，把你喜欢的字体输入进去就行，示例如下：
![Clip_2024-08-25_04-04-11](https://github.com/user-attachments/assets/12016de1-4e60-4694-8701-7f4f019397fd)

**Comment by cloudflypeng** [comment]
字体加载 可以用https://github.com/bramstein/fontfaceobserver
