### ISSUE TITLE
[BUG] 暗黑模式无法正常运作

### ISSUE THREAD

**Issue by caicai7162** [BewlyBewly/BewlyBewly#955]
### 环境

浏览器 MicroSoft Edge
浏览器版本 127.0.2651.86 (正式版本) (64 位)
BewlyBewly 版本 0.27.4

### 问题描述

![image](https://github.com/user-attachments/assets/e6bb2f9d-2bbf-4ad1-84d9-2f1deb3b2c76)

**Comment by hakadao** [comment]
這種情況是因為你同時安裝聊多個bewlybewly，刪除舊的保留新的就可以解決
