### ISSUE TITLE
视频播放页面右边的两个按钮隐藏

### ISSUE THREAD

**Issue by Homer-Max** [BewlyBewly/BewlyBewly#958]
### 环境

浏览器 (如 Chrome):
浏览器版本 (如 126.0.6478.126):
BewlyBewly 版本 (如 0.20.1):

### 问题描述

我使用了wider宽屏，两个按钮遮挡了部分视频，却没有自动隐藏功能。那些按钮在首页就可以了，在播放页面没有用的

**Comment by hakadao** [comment]
下版本可以直接配置
![image](https://github.com/user-attachments/assets/214aeea1-9483-40b8-8383-1c43033a7a66)
