### ISSUE TITLE
【功能请求】在番剧页面增加追剧页面入口

### ISSUE THREAD

**Issue by sjrmdtjws2233** [BewlyBewly/BewlyBewly#959]
![屏幕截图 2024-08-11 134905](https://github.com/user-attachments/assets/f449de62-4476-40fd-b5e6-e85c629f38cb)
![屏幕截图 2024-08-11 134934](https://github.com/user-attachments/assets/105fd9c2-4465-4638-bc85-9ed72320d5c7)

**Comment by hakadao** [comment]
這類不是屬於動畫內容, 不太想加入進去

**Comment by JIANHAISITIAN** [comment]
谢谢答复
________________________________
发件人: Hakadao ***@***.***>
发送时间: 2024年8月21日 10:33
收件人: BewlyBewly/BewlyBewly ***@***.***>
抄送: Hengxuan Yao ***@***.***>; Author ***@***.***>
主题: Re: [BewlyBewly/BewlyBewly] 【功能请求】在番剧页面增加追剧页面入口 (Issue #959)


@不是凫赢热, 不太想加入M去

―
