### ISSUE TITLE
[BUG] "我的收藏和订阅"部分无法显示具体的视频内容

### ISSUE THREAD

**Issue by aurora0x27** [BewlyBewly/BewlyBewly#961]
### 环境

浏览器: Google Chrome
浏览器版本: 1 127.0.6533.119
BewlyBewly: 0.27.4

### 问题描述

个人页面点击"我的收藏和订阅"后没有在右侧显示对应合集的各集视频
![image](https://github.com/user-attachments/assets/ad5d8578-8422-42b7-acfa-c2c50db788d2)
![image](https://github.com/user-attachments/assets/5e43b529-7a3b-426b-9e0e-5681950c969f)

### 预期结果

正常显示合集中的视频

**Comment by hakadao** [comment]
只有主頁是改過的，其他b站頁面最多適配了深色或去廣告
