### ISSUE TITLE
[BUG] 关注页面视频条目偶尔会重复出现

### ISSUE THREAD

**Issue by bbcyz** [BewlyBewly/BewlyBewly#962]
### 环境

浏览器 :Chrome
浏览器版本 :127.0.6533.120
BewlyBewly 版本 :0.27.4
![PixPin_2024-08-16_00-18-29](https://github.com/user-attachments/assets/a2cca764-90f8-4bc5-a0e6-7ec51caedf70)

### 问题描述

关注页面偶尔会出现重复的视频条目

**Comment by hakadao** [comment]
是不是滑動太快導致的

**Comment by Ender-Wang** [comment]
我也遇到了，最近发现的，每天都能看到好几条重复的
![Google Chrome 2024-08-17 13 43 41](https://github.com/user-attachments/assets/db6f0fa9-4c62-4a55-8f47-4743c757d022)
![Google Chrome 2024-08-17 13 44 41](https://github.com/user-attachments/assets/bda0d955-ffaf-4b62-9018-bed16213371b)

**Comment by DemoJameson** [comment]
我发现有时候右上角的动态与正在关注的列表相比会缺少一些视频，这时正在关注就会出现重复的条目
