### ISSUE TITLE
[BUG] 打开插件youtube会卡死，点不了暂停

### ISSUE THREAD

**Issue by zuowinston** [BewlyBewly/BewlyBewly#963]
### 环境

浏览器 ( Chrome):
浏览器版本 (如 127.0.6533.120):
BewlyBewly 版本 (如 0.27.4):

### 问题描述

打开这个插件，youtube页面的暂停开始就按不了，也不知道是不是和别的插件冲突，我关了别的好像没解决，应该就是这个插件的原因

### 预期结果

希望能够修复一下，辛苦啦

**Comment by zuowinston** [comment]
感谢感谢啦，放一会，youtube页面就卡死了

**Comment by hakadao** [comment]
你如果禁止插件之後沒有解決那就是其他問題，要麼是開太多應用電腦
這裏不是解決非bewly之外問題的地方
