### ISSUE TITLE
[BUG] 滚动时有时候会卡住，只能刷新，且每次推荐视频基本一致（是B站推荐问题还是插件问题？）

### ISSUE THREAD

**Issue by CreeperAWA** [BewlyBewly/BewlyBewly#964]
### 环境

浏览器 (如 Chrome):Chrome
浏览器版本 (如 126.0.6478.126):127.0.6533.120（正式版本） （64 位）
BewlyBewly 版本 (如 0.20.1):0.27.4

### 问题描述

如下图，滚动时会卡住不加载视频
![recording](https://github.com/user-attachments/assets/2159bb2d-5791-43b6-a9ab-56cb3799dc5e)
该问题概率复现，但是我这几次似乎运气出奇的好，次次复现
使用web端推荐（实测使用web端推荐和app推荐存在同样问题），推荐视频一致图片如下
![recording](https://github.com/user-attachments/assets/7acfe644-db92-4faa-94dc-16a45168c8cb)

### 预期结果

正常加载视频，若推荐视频一致非B站推荐问题，则希望可以避免推荐一致问题，若为B站推荐问题，希望可以尽量解决

**Comment by hakadao** [comment]
是否啟用了推薦過濾功能

**Comment by CreeperAWA** [comment]
是

> 是否啟用了推薦過濾功能
