### ISSUE TITLE
[咨询] 视频清晰度选项无法记忆

### ISSUE THREAD

**Issue by lakevilladom** [BewlyBewly/BewlyBewly#966]
### 环境

浏览器 (如 Chrome): Chrome
浏览器版本 (如 126.0.6478.126):127.0.6533.100
BewlyBewly 版本 (如 0.20.1):v0.27.4

### 问题描述

经常发现视频播放的清晰度会下调到720，能否新增设置：指定清晰度或者优先选择最高清晰度

**Comment by hakadao** [comment]
> BewlyBewly 主要专注页面的调整和优化，而不是完善功能和提升效率。

播放器相關的調整請找其他擴充功能或油猴腳本，這些不在考慮添加功能之內
