### ISSUE TITLE
[BUG] 打开视频页面时或者打开哔哩哔哩首页会闪出bilibili原版顶栏

### ISSUE THREAD

**Issue by Areire** [BewlyBewly/BewlyBewly#967]
### 环境

浏览器 (如 Chrome):Catsxp
浏览器版本 (如 126.0.6478.126):4.8.2 内核版本:127.0.6533.100
BewlyBewly 版本 (如 0.20.1):0.28.0

### 问题描述

打开视频页面时或者打开哔哩哔哩首页会闪出bilibili原版顶栏，过了几秒会自动变为bewlybewly的顶栏。

### 预期结果

修复此问题

**Comment by hakadao** [comment]
這部分暫時不知道如何修復

**Comment by ITManCHINA** [comment]
果然这个还是有问题😂
