### ISSUE TITLE
[BUG] 滚动时有时候会卡住，只能刷新，且每次推荐视频基本一致

### ISSUE THREAD

**Issue by CreeperAWA** [BewlyBewly/BewlyBewly#970]
### 环境

浏览器 (如 Chrome):Chrome
浏览器版本 (如 126.0.6478.126):127.0.6533.120（正式版本） （64 位）
BewlyBewly 版本 (如 0.20.1):0.27.4

### 问题描述

这个标题是不是看起来非常眼熟，我又出现了一样的问题了(
每次推荐视频基本一致的问题上一次没有解决，滚动时有时候会卡住的问题概率复现，我现在又复现了，详细信息见 #964
补充一下每次推荐视频基本一致问题的信息：这个每天看是不一样的，但是一天（应该是24小时左右）内看都是一样的，暂时没有试过清理浏览器缓存

### 预期结果

正常加载视频，尽量解决推荐一致问题

**Comment by hakadao** [comment]
新版本是0.28.1已修復卡着問題
另外app推介一定要授權才能獲取個性內容，否則都會重複

**Comment by CreeperAWA** [comment]
我使用web推荐和app推荐都是重复的，并且我授权了key，我使用的也是0.28.1，热门视频仍然卡住，但我刚刚刷了一下个性推荐发现是好的，并且也不会重复推荐
环境是从上个issue复制的，忘改了，抱歉

**Comment by hakadao** [comment]
> 我使用web推荐和app推荐都是重复的，并且我授权了key，我使用的也是0.28.1，热门视频仍然卡住，但我刚刚刷了一下个性推荐发现是好的，并且也不会重复推荐
> 
> 环境是从上个issue复制的，忘改了，抱歉

B站熱門數據沒有更新我還能做甚麼

**Comment by CreeperAWA** [comment]
不是。。。原来热门数据这么容易就到头吗。。。以前也没这样过，我还以为这个和安卓端首页是一样的，就说怎么感觉味不对
打扰了，抱歉

**Comment by hakadao** [comment]
> 不是。。。原来热门数据这么容易就到头吗。。。以前也没这样过，我还以为这个和安卓端首页是一样的，就说怎么感觉味不对
> 
> 打扰了，抱歉

你可以使用b站原版首頁點進去熱門視頻看看，他那邊也是有到頭的

**Comment by CreeperAWA** [comment]
好吧，还真是，打扰了，我以前一直以为我看的就是热门视频，原来是个性推荐

**Comment by CreeperAWA** [comment]
好吧，还真是，打扰了，我以前一直以为我看的就是热门视频，原来是个性推荐
