### ISSUE TITLE
在顶栏可见性中关闭顶栏后，刷新会重新出现

### ISSUE THREAD

**Issue by shibuyameltdown** [BewlyBewly/BewlyBewly#971]
### 环境

chrome版本128.0.6613.84
插件版本v0.28.0
油猴版本5.2.0

### 问题描述

如题

**Comment by hakadao** [comment]
重複問題，請去 #967 討論

**Comment by shibuyameltdown** [comment]
是一样的吗，我用的是bilibili evolved顶栏。将本插件顶栏关闭后刷新，两个插件的顶栏会同时出现，同时设置里的顶栏会重新变回打开状态🥲
