### ISSUE TITLE
[BUG] 网页加载问题

### ISSUE THREAD

**Issue by Hanitong** [BewlyBewly/BewlyBewly#977]
### 环境

浏览器: Chrome
浏览器版本: 128.0.6613.114
BewlyBewly 版本: 0.28.3

### 问题描述

- 开启 Clash 代理情况
能够正常进入 bilibili.com，但是内容都显示为占位符，过很久才能加载出内容。加载出一次之后可以正常使用一会，但一段时间后就会再次出现以上问题。关掉插件使用原版B站主页就可以修复以上问题。
- 关掉 Clash 后启用插件可以正常使用，或者关掉插件使用原版B站主页也无问题。
![image](https://github.com/user-attachments/assets/304c0ef2-275f-4f5b-8f81-e4de5642da0f)
![image](https://github.com/user-attachments/assets/428bbf02-f71c-499f-8bb4-94719439d05c)

不止首页有问题，开启插件后包括视频播放页等都会出现加载空页面的情况。

bug不是稳定持续出现，出现一会儿后好一会儿，然后又出问题。

简言之，开启插件并开启代理有问题，关闭代理问题解决；关闭插件并打开代理无问题，打开插件问题出现。应该不是个人网络原因，不知道是不是插件的网络请求方面可能存在一些问题。

**Comment by hakadao** [comment]
為何不直接開pac模式或規則模式？

**Comment by hakadao** [comment]
b站本來就是你用其他ip訪問會慢點的，網絡問題的事我怎麼處理
