### ISSUE TITLE
[优化建议] b站原本的操作逻辑是点击之后在新窗口打开，此插件使用却是相反的逻辑，希望能够有选项控制

### ISSUE THREAD

**Issue by GRTsk0818** [BewlyBewly/BewlyBewly#979]
### 环境

浏览器 Chrome
浏览器版本 128.0.6613.86
BewlyBewly 版本 v0.28.4

### 问题描述

顶上一排按钮都是点击后替换当前页，而不是在新窗口打开
设置》关于 里的几个官方链接却是在新窗口打开

### 预期结果

都改为在新窗口打开，和b站原版保持一致，尽量不变使用习惯

**Comment by hakadao** [comment]
有點麻煩，之前寫是寫死的，我其實期望是減少新開標籤頁，日後再慢慢換成配置式的
不過你可以先暫時用着b站原本的頂欄先
![image](https://github.com/user-attachments/assets/79d4d3bd-c6f7-4864-bcf5-545840da74f0)

**Comment by hakadao** [comment]
下版本可以配置
![image](https://github.com/user-attachments/assets/6238e69c-2e62-4775-819e-892c4345e263)

**Comment by GRTsk0818** [comment]
没改完，[v0.31.3]直接点通知按钮还是，点下面子菜单就不会
