### ISSUE TITLE
[BUG] Firefox中首页DOCK栏中除了亮暗色切换和设置，其他点击无效果

### ISSUE THREAD

**Issue by VVtianchen** [BewlyBewly/BewlyBewly#980]
### 环境

浏览器 (如 Chrome):firefox
浏览器版本 (如 126.0.6478.126):129.02
BewlyBewly 版本 (如 0.20.1):0.28.4

### 问题描述

firefox浏览器里首页dock栏的按钮，除了亮暗色切换和设置以外其他按钮，如收藏、首页、稍后再看、番剧等均无法使用，点击或者悬停均无反应，另外也是firefox中dock栏仅有刷新按钮被整合，返回顶部按钮未被整合，麻烦修复下，感谢

### 预期结果

返回顶部按钮整合进dock栏，dock栏中按钮均完整发挥作用，感谢

**Comment by VVtianchen** [comment]
还有个问题就是Firefox中，设置里无法下滑进行翻页，比如首页选项中，一页显示不全，但是无法下滑翻页
![image](https://github.com/user-attachments/assets/7838c80a-309e-4c58-b7f0-afc2d046d9f9)

**Comment by VVtianchen** [comment]
![image](https://github.com/user-attachments/assets/8819e691-5f6a-44be-bcc6-c97b4312b6bc)
![image](https://github.com/user-attachments/assets/9e75dd88-ba79-4365-ac0e-7c2c3aa22342)

这是未整合返回顶部的按钮，设置内已勾选

**Comment by VVtianchen** [comment]
还有个问题就是firefox中，主页中的页面仅有一页，无法通过往下滑来增加，包括正在关注，个性推荐等，均只有一页，无法下滑显示更多视频
![image](https://github.com/user-attachments/assets/c2f3f970-88ae-4ba5-9850-97ab0d324b36)

**Comment by hakadao** [comment]
沒有重現此問題
Firefox版本：129.0.2 (64-bit)
https://github.com/user-attachments/assets/6c9cee78-4998-40c0-b5d6-f018156ed4cb

**Comment by VVtianchen** [comment]
> 沒有重現此問題 Firefox版本：129.0.2 (64-bit) https://github.com/user-attachments/assets/6c9cee78-4998-40c0-b5d6-f018156ed4cb

抱歉抱歉，在单位电脑会有如上的问题，家里电脑重新试了一下未出现此问题，单位电脑连接的是双屏，有可能是这个问题吗，给您添麻烦了，感谢回复

**Comment by hakadao** [comment]
> > 沒有重現此問題 Firefox版本：129.0.2 (64-bit) https://github.com/user-attachments/assets/6c9cee78-4998-40c0-b5d6-f018156ed4cb
> 
> 
> 
> 抱歉抱歉，在单位电脑会有如上的问题，家里电脑重新试了一下未出现此问题，单位电脑连接的是双屏，有可能是这个问题吗，给您添麻烦了，感谢回复

不清楚你單位電腦有沒有裝其他b站腳本或擴充功能導致的...

**Comment by VVtianchen** [comment]
> > > 沒有重現此問題 Firefox版本：129.0.2 (64-bit) https://github.com/user-attachments/assets/6c9cee78-4998-40c0-b5d6-f018156ed4cb
> > 
> > 
> > 抱歉抱歉，在单位电脑会有如上的问题，家里电脑重新试了一下未出现此问题，单位电脑连接的是双屏，有可能是这个问题吗，给您添麻烦了，感谢回复
> 
> 不清楚你單位電腦有沒有裝其他b站腳本或擴充功能導致的...

以前装过BILI Plus，但是安了BEWLY之后就卸载了

**Comment by VVtianchen** [comment]
> > > 沒有重現此問題 Firefox版本：129.0.2 (64-bit) https://github.com/user-attachments/assets/6c9cee78-4998-40c0-b5d6-f018156ed4cb
> > 
> > 
> > 抱歉抱歉，在单位电脑会有如上的问题，家里电脑重新试了一下未出现此问题，单位电脑连接的是双屏，有可能是这个问题吗，给您添麻烦了，感谢回复
> 
> 不清楚你單位電腦有沒有裝其他b站腳本或擴充功能導致的...

抱歉查到了，单位电脑上的火狐在B站开了“User-Agent Switcher and Manager”这个插件，因为要上一些国内网站所以伪装成了edge，关闭之后bewly就可以正常使用了，多有打扰

**Comment by hakadao** [comment]
特別測了一下 firefox 裝了User-Agent Switcher and Manager後問題也沒有重現
![image](https://github.com/user-attachments/assets/e529168a-3710-4f2f-bcf3-37d225b4c515)
