### ISSUE TITLE
Able to remove tracking parameters from shared links

### ISSUE THREAD

**Issue by NeKoOuO** [BewlyBewly/BewlyBewly#981]
![image](https://github.com/user-attachments/assets/fc1a4368-179b-4f87-bd6c-4a0cc0e8a722)

Every time I use the share link, I have to manually remove those useless tracking parameters. I hope to add a feature that allows me to get a clean link just by clicking the share button.

**Comment by hakadao** [comment]
https://github.com/BewlyBewly/BewlyBewly?tab=readme-ov-file#-introduction
> BewlyBewly mainly focuses on page adjustments and optimization rather than improving functionality and efficiency.

Bilibili Evolved already has a similar feature, and it provides more additional practical functionalities
