### ISSUE TITLE
暗色模式下希望在视频播放页也能加入渐变色背景（类似youtube）

### ISSUE THREAD

**Issue by Versahein** [BewlyBewly/BewlyBewly#992]
### 环境

浏览器 (如 Chrome):
浏览器版本 (如 126.0.6478.126):
BewlyBewly 版本 (如 0.20.1):

### 问题描述

暗色模式下希望在视频播放页也能加入渐变色背景（类似youtube）

**Comment by hakadao** [comment]
暫時不考慮做
