### ISSUE TITLE
不想看此up好像有问题【BUG】

### ISSUE THREAD

**Issue by shaoyouvip** [BewlyBewly/BewlyBewly#995]
### 环境

浏览器 (如 Chrome):Chrome
浏览器版本 (如 126.0.6478.126):版本 128.0.6613.120（正式版本）
BewlyBewly 版本 (如 0.20.1):[v0.29.0]

### 问题描述

不想看此up好像有问题 我选择了不想看此up后刷新页面他就给我出他的视频再次点了，不想看他 刷新又出了，循环了 3-4此刷新没有看到了。
![屏幕截图 2024-09-06 152729](https://github.com/user-attachments/assets/276e3c19-41cc-40d2-9ecd-0ecc24e7d1c0)
![屏幕截图 2024-09-06 152754](https://github.com/user-attachments/assets/17d584ee-8885-4b97-9f75-dd958c96a640)
![屏幕截图 2024-09-06 152807](https://github.com/user-attachments/assets/bd41dc0e-7e28-498a-9ca3-3683cab8dde3)

**Comment by hakadao** [comment]
b站原版的主頁處理也是這樣的，網頁端的操作實質上是心理作用，那時就一直不想做但是一直被人迫着要加，然後我就學b站做了一個讓用戶心理作用變好的功能

要真的不感興趣就用app端的推介

**Comment by shine-fire** [comment]
B站这个功能纯恶心人的，我每次点了以后依旧给我推送，感觉更恶心人了，还不如没有这个功能我还好受点
