### ISSUE TITLE
[建议]希望能在 首页标签栏 里增加一个 正在直播 的选项

### ISSUE THREAD

**Issue by guanchan** [BewlyBewly/BewlyBewly#999]
看直播比较多，现在每次都要在右上角的 动态 里再切到 直播 来查看，非常不方便。
如果能在 首页标签里 加入一个 正在直播 就太好了

**Comment by hakadao** [comment]
![image](https://github.com/user-attachments/assets/5fb06fae-405a-486f-891f-b4a1fc123656)
